// Code generated by codegen/src/Packet.Sdl.CodeGen from
// spec-sdl/v2.2-errata/data-link/yaml/connected.sdl.yaml. DO NOT EDIT. Run
// `dotnet run --project codegen/src/Packet.Sdl.CodeGen` to regenerate.

#include "ax25sdl.h"

static const ActionStep
    data_link_connected_t01_dl_disconnect_request_actions[] = {
        {.verb = "discard_I_frame_queue", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "RC := 0", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "DISC (P = 1)", .kind = AX25SDL_KIND_SIGNAL_LOWER},
        {.verb = "Stop T3", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Start T1", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep data_link_connected_t02_dl_data_request_actions[] = {
    {.verb = "Push on I Frame Queue (note: word order?)",
     .kind = AX25SDL_KIND_INTERNAL_OUT},
};

static const ActionStep
    data_link_connected_t03_i_frame_pops_off_queue_yes_actions[] = {
        {.verb = "Push on I Frame Queue", .kind = AX25SDL_KIND_INTERNAL_OUT},
};

static const ActionStep
    data_link_connected_t03_i_frame_pops_off_queue_no_yes_actions[] = {
        {.verb = "Push on I Frame Queue", .kind = AX25SDL_KIND_INTERNAL_OUT},
};

static const ActionStep
    data_link_connected_t03_i_frame_pops_off_queue_no_no_no_actions[] = {
        {.verb = "N(s) := V(s)", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "N(r) := V(r)", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "P := 0", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "I Command", .kind = AX25SDL_KIND_SIGNAL_LOWER},
        {.verb = "V(s) := V(s) + 1", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Clear Acknowledge Pending", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Stop T3", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Start T1", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_connected_t03_i_frame_pops_off_queue_no_no_yes_actions[] = {
        {.verb = "N(s) := V(s)", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "N(r) := V(r)", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "P := 0", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "I Command", .kind = AX25SDL_KIND_SIGNAL_LOWER},
        {.verb = "V(s) := V(s) + 1", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Clear Acknowledge Pending", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep data_link_connected_t04_dl_unit_data_request_actions[] =
    {
        {.verb = "UI Command", .kind = AX25SDL_KIND_SIGNAL_LOWER},
};

static const ActionStep
    data_link_connected_t05_dl_flow_off_request_yes_actions[] = {
        {.verb = "Set Own Receiver Busy", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "RNR Response", .kind = AX25SDL_KIND_SIGNAL_LOWER},
        {.verb = "Clear Acknowledge Pending", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_connected_t06_dl_flow_on_request_yes_yes_actions[] = {
        {.verb = "Clear Own Receiver Busy", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "RR Command", .kind = AX25SDL_KIND_SIGNAL_LOWER},
        {.verb = "Clear Acknowledge Pending", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_connected_t06_dl_flow_on_request_yes_no_actions[] = {
        {.verb = "Clear Own Receiver Busy", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "RR Command", .kind = AX25SDL_KIND_SIGNAL_LOWER},
        {.verb = "Clear Acknowledge Pending", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Stop T3", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Start T1", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_connected_t07_dl_connect_request_no_actions[] = {
        {.verb = "discard_I_frame_queue", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Establish_Data_Link", .kind = AX25SDL_KIND_SUBROUTINE},
        {.verb = "Set Layer 3 Initiated", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_connected_t07_dl_connect_request_yes_actions[] = {
        {.verb = "discard_I_frame_queue", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Establish_Data_Link", .kind = AX25SDL_KIND_SUBROUTINE},
        {.verb = "Set Layer 3 Initiated", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_connected_t09_control_field_error_no_actions[] = {
        {.verb = "DL-ERROR Indication (L)", .kind = AX25SDL_KIND_SIGNAL_UPPER},
        {.verb = "discard_I_frame_queue", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Establish_Data_Link", .kind = AX25SDL_KIND_SUBROUTINE},
        {.verb = "Set Layer 3 Initiated", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_connected_t09_control_field_error_yes_actions[] = {
        {.verb = "DL-ERROR Indication (L)", .kind = AX25SDL_KIND_SIGNAL_UPPER},
        {.verb = "discard_I_frame_queue", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Establish_Data_Link", .kind = AX25SDL_KIND_SUBROUTINE},
        {.verb = "Set Layer 3 Initiated", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_connected_t10_info_not_permitted_in_frame_no_actions[] = {
        {.verb = "DL-ERROR Indication (M)", .kind = AX25SDL_KIND_SIGNAL_UPPER},
        {.verb = "discard_I_frame_queue", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Establish_Data_Link", .kind = AX25SDL_KIND_SUBROUTINE},
        {.verb = "Set Layer 3 Initiated", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_connected_t10_info_not_permitted_in_frame_yes_actions[] = {
        {.verb = "DL-ERROR Indication (M)", .kind = AX25SDL_KIND_SIGNAL_UPPER},
        {.verb = "discard_I_frame_queue", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Establish_Data_Link", .kind = AX25SDL_KIND_SUBROUTINE},
        {.verb = "Set Layer 3 Initiated", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_connected_t11_u_or_s_frame_length_error_no_actions[] = {
        {.verb = "DL-ERROR Indication (N)", .kind = AX25SDL_KIND_SIGNAL_UPPER},
        {.verb = "discard_I_frame_queue", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Establish_Data_Link", .kind = AX25SDL_KIND_SUBROUTINE},
        {.verb = "Set Layer 3 Initiated", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_connected_t11_u_or_s_frame_length_error_yes_actions[] = {
        {.verb = "DL-ERROR Indication (N)", .kind = AX25SDL_KIND_SIGNAL_UPPER},
        {.verb = "discard_I_frame_queue", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Establish_Data_Link", .kind = AX25SDL_KIND_SUBROUTINE},
        {.verb = "Set Layer 3 Initiated", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep data_link_connected_t12_t1_expiry_actions[] = {
    {.verb = "RC := 1", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "Transmit Enquery", .kind = AX25SDL_KIND_SUBROUTINE},
};

static const ActionStep data_link_connected_t13_t3_expiry_actions[] = {
    {.verb = "RC := 1", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "Transmit Enquery", .kind = AX25SDL_KIND_SUBROUTINE},
};

static const ActionStep data_link_connected_t14_sabm_received_yes_actions[] = {
    {.verb = "F := P", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "set_version_2_0", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "UA", .kind = AX25SDL_KIND_SIGNAL_LOWER},
    {.verb = "Clear Exception Conditions", .kind = AX25SDL_KIND_SUBROUTINE},
    {.verb = "DL-ERROR Indication (F)", .kind = AX25SDL_KIND_SIGNAL_UPPER},
    {.verb = "Stop T1", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "Start T3", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "V(a) := 0", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "V(s) := 0", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "V(r) := 0", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "RC := 0", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep data_link_connected_t14_sabm_received_no_actions[] = {
    {.verb = "F := P", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "set_version_2_0", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "UA", .kind = AX25SDL_KIND_SIGNAL_LOWER},
    {.verb = "Clear Exception Conditions", .kind = AX25SDL_KIND_SUBROUTINE},
    {.verb = "DL-ERROR Indication (F)", .kind = AX25SDL_KIND_SIGNAL_UPPER},
    {.verb = "discard_I_frame_queue", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "DL_CONNECT_indication", .kind = AX25SDL_KIND_SIGNAL_UPPER},
    {.verb = "Stop T1", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "Start T3", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "V(a) := 0", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "V(s) := 0", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "V(r) := 0", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "RC := 0", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep data_link_connected_t15_sabme_received_yes_actions[] = {
    {.verb = "F := P", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "Set Version 2.2", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "UA", .kind = AX25SDL_KIND_SIGNAL_LOWER},
    {.verb = "Clear Exception Conditions", .kind = AX25SDL_KIND_SUBROUTINE},
    {.verb = "DL-ERROR Indication (F)", .kind = AX25SDL_KIND_SIGNAL_UPPER},
    {.verb = "Stop T1", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "Start T3", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "V(a) := 0", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "V(s) := 0", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "V(r) := 0", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "RC := 0", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep data_link_connected_t15_sabme_received_no_actions[] = {
    {.verb = "F := P", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "Set Version 2.2", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "UA", .kind = AX25SDL_KIND_SIGNAL_LOWER},
    {.verb = "Clear Exception Conditions", .kind = AX25SDL_KIND_SUBROUTINE},
    {.verb = "DL-ERROR Indication (F)", .kind = AX25SDL_KIND_SIGNAL_UPPER},
    {.verb = "discard_I_frame_queue", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "DL_CONNECT_indication", .kind = AX25SDL_KIND_SIGNAL_UPPER},
    {.verb = "Stop T1", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "Start T3", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "V(a) := 0", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "V(s) := 0", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "V(r) := 0", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "RC := 0", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep data_link_connected_t16_frmr_received_no_actions[] = {
    {.verb = "DL-ERROR Indication (K)", .kind = AX25SDL_KIND_SIGNAL_UPPER},
    {.verb = "Establish_Data_Link", .kind = AX25SDL_KIND_SUBROUTINE},
    {.verb = "Clear Layer 3 Initiated", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep data_link_connected_t16_frmr_received_yes_actions[] = {
    {.verb = "DL-ERROR Indication (K)", .kind = AX25SDL_KIND_SIGNAL_UPPER},
    {.verb = "Establish_Data_Link", .kind = AX25SDL_KIND_SUBROUTINE},
    {.verb = "Clear Layer 3 Initiated", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep data_link_connected_t17_ua_received_no_actions[] = {
    {.verb = "DL-ERROR Indication (K)", .kind = AX25SDL_KIND_SIGNAL_UPPER},
    {.verb = "Establish_Data_Link", .kind = AX25SDL_KIND_SUBROUTINE},
    {.verb = "Clear Layer 3 Initiated", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep data_link_connected_t17_ua_received_yes_actions[] = {
    {.verb = "DL-ERROR Indication (K)", .kind = AX25SDL_KIND_SIGNAL_UPPER},
    {.verb = "Establish_Data_Link", .kind = AX25SDL_KIND_SUBROUTINE},
    {.verb = "Clear Layer 3 Initiated", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep data_link_connected_t18_ui_received_yes_actions[] = {
    {.verb = "UI Check", .kind = AX25SDL_KIND_SUBROUTINE},
    {.verb = "Enquiry_Response_F_1", .kind = AX25SDL_KIND_SUBROUTINE},
};

static const ActionStep data_link_connected_t18_ui_received_no_actions[] = {
    {.verb = "UI Check", .kind = AX25SDL_KIND_SUBROUTINE},
};

static const ActionStep data_link_connected_t19_disc_received_actions[] = {
    {.verb = "discard_I_frame_queue", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "F := P", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "UA", .kind = AX25SDL_KIND_SIGNAL_LOWER},
    {.verb = "DL_DISCONNECT_indication", .kind = AX25SDL_KIND_SIGNAL_UPPER},
    {.verb = "Stop T3", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "Start T1", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep data_link_connected_t20_dm_received_actions[] = {
    {.verb = "DL-ERROR Indication (E)", .kind = AX25SDL_KIND_SIGNAL_UPPER},
    {.verb = "DL_DISCONNECT_indication", .kind = AX25SDL_KIND_SIGNAL_UPPER},
    {.verb = "discard_I_frame_queue", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "Stop T1", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "Stop T3", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep data_link_connected_t21_rr_received_yes_actions[] = {
    {.verb = "clear_peer_receiver_busy", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "Check Need For Response", .kind = AX25SDL_KIND_SUBROUTINE},
    {.verb = "Check_I_Frame_Acknowledged", .kind = AX25SDL_KIND_SUBROUTINE},
};

static const ActionStep data_link_connected_t21_rr_received_no_no_actions[] = {
    {.verb = "clear_peer_receiver_busy", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "Check Need For Response", .kind = AX25SDL_KIND_SUBROUTINE},
    {.verb = "N(r) Error Recovery", .kind = AX25SDL_KIND_SUBROUTINE},
};

static const ActionStep data_link_connected_t21_rr_received_no_yes_actions[] = {
    {.verb = "clear_peer_receiver_busy", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "Check Need For Response", .kind = AX25SDL_KIND_SUBROUTINE},
    {.verb = "N(r) Error Recovery", .kind = AX25SDL_KIND_SUBROUTINE},
};

static const ActionStep data_link_connected_t22_rnr_received_yes_actions[] = {
    {.verb = "set_peer_receiver_busy", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "Check Need For Response", .kind = AX25SDL_KIND_SUBROUTINE},
    {.verb = "Check_I_Frame_Acknowledged", .kind = AX25SDL_KIND_SUBROUTINE},
};

static const ActionStep data_link_connected_t22_rnr_received_no_no_actions[] = {
    {.verb = "set_peer_receiver_busy", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "Check Need For Response", .kind = AX25SDL_KIND_SUBROUTINE},
    {.verb = "N(r) Error Recovery", .kind = AX25SDL_KIND_SUBROUTINE},
};

static const ActionStep data_link_connected_t22_rnr_received_no_yes_actions[] =
    {
        {.verb = "set_peer_receiver_busy", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Check Need For Response", .kind = AX25SDL_KIND_SUBROUTINE},
        {.verb = "N(r) Error Recovery", .kind = AX25SDL_KIND_SUBROUTINE},
};

static const ActionStep data_link_connected_t23_lm_seize_confirm_yes_actions[] =
    {
        {.verb = "Clear Acknowledge Pending", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Enquiry Response (F = 0)", .kind = AX25SDL_KIND_SUBROUTINE},
        {.verb = "LM_release_request", .kind = AX25SDL_KIND_SIGNAL_LOWER},
};

static const ActionStep data_link_connected_t23_lm_seize_confirm_no_actions[] =
    {
        {.verb = "LM_release_request", .kind = AX25SDL_KIND_SIGNAL_LOWER},
};

static const ActionStep
    data_link_connected_t24_srej_received_yes_yes_actions[] = {
        {.verb = "clear_peer_receiver_busy", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Check Need For Response", .kind = AX25SDL_KIND_SUBROUTINE},
        {.verb = "V(a) := N(r)", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Stop T1", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Start T3", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Select_T1_Value", .kind = AX25SDL_KIND_SUBROUTINE},
        {.verb = "Push Old I Frame N(r) on Queue",
         .kind = AX25SDL_KIND_INTERNAL_OUT},
        {.verb = "LM_data_request", .kind = AX25SDL_KIND_SIGNAL_LOWER},
        {.verb = "Stop T3", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Start T1", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Clear Acknowledge Pending", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep data_link_connected_t24_srej_received_yes_no_actions[] =
    {
        {.verb = "clear_peer_receiver_busy", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Check Need For Response", .kind = AX25SDL_KIND_SUBROUTINE},
        {.verb = "Stop T1", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Start T3", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Select_T1_Value", .kind = AX25SDL_KIND_SUBROUTINE},
        {.verb = "Push Old I Frame N(r) on Queue",
         .kind = AX25SDL_KIND_INTERNAL_OUT},
        {.verb = "LM_data_request", .kind = AX25SDL_KIND_SIGNAL_LOWER},
        {.verb = "Stop T3", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Start T1", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Clear Acknowledge Pending", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep data_link_connected_t24_srej_received_no_no_actions[] =
    {
        {.verb = "clear_peer_receiver_busy", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Check Need For Response", .kind = AX25SDL_KIND_SUBROUTINE},
        {.verb = "N(r) Error Recovery", .kind = AX25SDL_KIND_SUBROUTINE},
};

static const ActionStep data_link_connected_t24_srej_received_no_yes_actions[] =
    {
        {.verb = "clear_peer_receiver_busy", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Check Need For Response", .kind = AX25SDL_KIND_SUBROUTINE},
        {.verb = "N(r) Error Recovery", .kind = AX25SDL_KIND_SUBROUTINE},
};

static const ActionStep data_link_connected_t25_rej_received_no_no_actions[] = {
    {.verb = "clear_peer_receiver_busy", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "Check Need For Response", .kind = AX25SDL_KIND_SUBROUTINE},
    {.verb = "N(r) Error Recovery", .kind = AX25SDL_KIND_SUBROUTINE},
};

static const ActionStep data_link_connected_t25_rej_received_no_yes_actions[] =
    {
        {.verb = "clear_peer_receiver_busy", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Check Need For Response", .kind = AX25SDL_KIND_SUBROUTINE},
        {.verb = "N(r) Error Recovery", .kind = AX25SDL_KIND_SUBROUTINE},
};

static const ActionStep data_link_connected_t25_rej_received_yes_actions[] = {
    {.verb = "clear_peer_receiver_busy", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "Check Need For Response", .kind = AX25SDL_KIND_SUBROUTINE},
    {.verb = "V(a) := N(r)", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "Start T1", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "Stop T3", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "Clear Acknowledge Pending", .kind = AX25SDL_KIND_PROCESSING},
    {.verb = "Select_T1_Value", .kind = AX25SDL_KIND_SUBROUTINE},
    {.verb = "Invoke Retransmission", .kind = AX25SDL_KIND_SUBROUTINE},
};

static const ActionStep data_link_connected_t26_i_received_yes_no_no_actions[] =
    {
        {.verb = "DL-ERROR Indication (O)", .kind = AX25SDL_KIND_SIGNAL_UPPER},
        {.verb = "Establish_Data_Link", .kind = AX25SDL_KIND_SUBROUTINE},
        {.verb = "Clear Layer 3 Initiated", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_connected_t26_i_received_yes_no_yes_actions[] = {
        {.verb = "DL-ERROR Indication (O)", .kind = AX25SDL_KIND_SIGNAL_UPPER},
        {.verb = "Establish_Data_Link", .kind = AX25SDL_KIND_SUBROUTINE},
        {.verb = "Clear Layer 3 Initiated", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_connected_t26_i_received_yes_yes_no_no_actions[] = {
        {.verb = "N(r) Error Recovery", .kind = AX25SDL_KIND_SUBROUTINE},
};

static const ActionStep
    data_link_connected_t26_i_received_yes_yes_no_yes_actions[] = {
        {.verb = "N(r) Error Recovery", .kind = AX25SDL_KIND_SUBROUTINE},
};

static const ActionStep
    data_link_connected_t26_i_received_yes_yes_yes_no_yes_no_no_actions[] = {
        {.verb = "Check_I_Frame_Acknowledged", .kind = AX25SDL_KIND_SUBROUTINE},
        {.verb = "V(r) := V(r) + 1", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Clear Reject Exception", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Decrement Sreject Exception if > 0",
         .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "DL_DATA_indication", .kind = AX25SDL_KIND_SIGNAL_UPPER},
        {.verb = "Retrieve Stored V(r) I Frame",
         .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "DL_DATA_indication", .kind = AX25SDL_KIND_SIGNAL_UPPER},
        {.verb = "V(r) := V(r) + 1", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "LM_seize_request", .kind = AX25SDL_KIND_SIGNAL_LOWER},
        {.verb = "set_acknowledge_pending", .kind = AX25SDL_KIND_PROCESSING},
};

static const LoopRange
    data_link_connected_t26_i_received_yes_yes_yes_no_yes_no_no_loops[] = {
        {.start = 5,
         .length = 3,
         .predicate = "vr_I_frame_stored",
         .test_at_end = false},
};

static const ActionStep
    data_link_connected_t26_i_received_yes_yes_yes_no_yes_no_yes_actions[] = {
        {.verb = "Check_I_Frame_Acknowledged", .kind = AX25SDL_KIND_SUBROUTINE},
        {.verb = "V(r) := V(r) + 1", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Clear Reject Exception", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Decrement Sreject Exception if > 0",
         .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "DL_DATA_indication", .kind = AX25SDL_KIND_SIGNAL_UPPER},
        {.verb = "Retrieve Stored V(r) I Frame",
         .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "DL_DATA_indication", .kind = AX25SDL_KIND_SIGNAL_UPPER},
        {.verb = "V(r) := V(r) + 1", .kind = AX25SDL_KIND_PROCESSING},
};

static const LoopRange
    data_link_connected_t26_i_received_yes_yes_yes_no_yes_no_yes_loops[] = {
        {.start = 5,
         .length = 3,
         .predicate = "vr_I_frame_stored",
         .test_at_end = false},
};

static const ActionStep
    data_link_connected_t26_i_received_yes_yes_yes_no_yes_yes_actions[] = {
        {.verb = "Check_I_Frame_Acknowledged", .kind = AX25SDL_KIND_SUBROUTINE},
        {.verb = "V(r) := V(r) + 1", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Clear Reject Exception", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Decrement Sreject Exception if > 0",
         .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "DL_DATA_indication", .kind = AX25SDL_KIND_SIGNAL_UPPER},
        {.verb = "Retrieve Stored V(r) I Frame",
         .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "DL_DATA_indication", .kind = AX25SDL_KIND_SIGNAL_UPPER},
        {.verb = "V(r) := V(r) + 1", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "F := 1", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "N(r) := V(r)", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "RR", .kind = AX25SDL_KIND_SIGNAL_LOWER},
        {.verb = "Clear Acknowledge Pending", .kind = AX25SDL_KIND_PROCESSING},
};

static const LoopRange
    data_link_connected_t26_i_received_yes_yes_yes_no_yes_yes_loops[] = {
        {.start = 5,
         .length = 3,
         .predicate = "vr_I_frame_stored",
         .test_at_end = false},
};

static const ActionStep
    data_link_connected_t26_i_received_yes_yes_yes_no_no_yes_yes_yes_actions[] =
        {
            {.verb = "Check_I_Frame_Acknowledged",
             .kind = AX25SDL_KIND_SUBROUTINE},
            {.verb = "Discard Contents of I Frame",
             .kind = AX25SDL_KIND_PROCESSING},
            {.verb = "F := 1", .kind = AX25SDL_KIND_PROCESSING},
            {.verb = "N(r) := V(r)", .kind = AX25SDL_KIND_PROCESSING},
            {.verb = "RR", .kind = AX25SDL_KIND_SIGNAL_LOWER},
            {.verb = "Clear Acknowledge Pending",
             .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_connected_t26_i_received_yes_yes_yes_no_no_yes_yes_no_actions[] =
        {
            {.verb = "Check_I_Frame_Acknowledged",
             .kind = AX25SDL_KIND_SUBROUTINE},
            {.verb = "Discard Contents of I Frame",
             .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_connected_t26_i_received_yes_yes_yes_no_no_yes_no_no_actions[] = {
        {.verb = "Check_I_Frame_Acknowledged", .kind = AX25SDL_KIND_SUBROUTINE},
        {.verb = "Discard Contents of I Frame",
         .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "Set Reject Exception", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "F := P", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "N(r) := V(r)", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "REJ", .kind = AX25SDL_KIND_SIGNAL_LOWER},
        {.verb = "Clear Acknowledge Pending", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_connected_t26_i_received_yes_yes_yes_no_no_yes_no_yes_yes_actions
        [] = {
            {.verb = "Check_I_Frame_Acknowledged",
             .kind = AX25SDL_KIND_SUBROUTINE},
            {.verb = "Save Contents of I Frame",
             .kind = AX25SDL_KIND_PROCESSING},
            {.verb = "N(r) := N(s)", .kind = AX25SDL_KIND_PROCESSING},
            {.verb = "F := 0", .kind = AX25SDL_KIND_PROCESSING},
            {.verb = "Increment Sreject Exception",
             .kind = AX25SDL_KIND_PROCESSING},
            {.verb = "SREJ", .kind = AX25SDL_KIND_SIGNAL_LOWER},
};

static const ActionStep
    data_link_connected_t26_i_received_yes_yes_yes_no_no_yes_no_yes_no_yes_actions
        [] = {
            {.verb = "Check_I_Frame_Acknowledged",
             .kind = AX25SDL_KIND_SUBROUTINE},
            {.verb = "Save Contents of I Frame",
             .kind = AX25SDL_KIND_PROCESSING},
            {.verb = "Discard Contents of I Frame",
             .kind = AX25SDL_KIND_PROCESSING},
            {.verb = "Set Reject Exception", .kind = AX25SDL_KIND_PROCESSING},
            {.verb = "F := P", .kind = AX25SDL_KIND_PROCESSING},
            {.verb = "N(r) := V(r)", .kind = AX25SDL_KIND_PROCESSING},
            {.verb = "REJ", .kind = AX25SDL_KIND_SIGNAL_LOWER},
            {.verb = "Clear Acknowledge Pending",
             .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_connected_t26_i_received_yes_yes_yes_no_no_yes_no_yes_no_no_actions
        [] = {
            {.verb = "Check_I_Frame_Acknowledged",
             .kind = AX25SDL_KIND_SUBROUTINE},
            {.verb = "Save Contents of I Frame",
             .kind = AX25SDL_KIND_PROCESSING},
            {.verb = "N(r) := V(r)", .kind = AX25SDL_KIND_PROCESSING},
            {.verb = "F := 1", .kind = AX25SDL_KIND_PROCESSING},
            {.verb = "Increment Sreject Exception",
             .kind = AX25SDL_KIND_PROCESSING},
            {.verb = "SREJ", .kind = AX25SDL_KIND_SIGNAL_LOWER},
};

static const ActionStep
    data_link_connected_t26_i_received_yes_yes_yes_no_no_no_yes_actions[] = {
        {.verb = "Check_I_Frame_Acknowledged", .kind = AX25SDL_KIND_SUBROUTINE},
        {.verb = "Discard Contents of I Frame",
         .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "F := 1", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "N(r) := V(r)", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "RR", .kind = AX25SDL_KIND_SIGNAL_LOWER},
        {.verb = "Clear Acknowledge Pending", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_connected_t26_i_received_yes_yes_yes_no_no_no_no_actions[] = {
        {.verb = "Check_I_Frame_Acknowledged", .kind = AX25SDL_KIND_SUBROUTINE},
        {.verb = "Discard Contents of I Frame",
         .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_connected_t26_i_received_yes_yes_yes_yes_yes_actions[] = {
        {.verb = "Check_I_Frame_Acknowledged", .kind = AX25SDL_KIND_SUBROUTINE},
        {.verb = "Discard Contents of I Frame",
         .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "F := 1", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "N(r) := V(r)", .kind = AX25SDL_KIND_PROCESSING},
        {.verb = "RR", .kind = AX25SDL_KIND_SIGNAL_LOWER},
        {.verb = "Clear Acknowledge Pending", .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep
    data_link_connected_t26_i_received_yes_yes_yes_yes_no_actions[] = {
        {.verb = "Check_I_Frame_Acknowledged", .kind = AX25SDL_KIND_SUBROUTINE},
        {.verb = "Discard Contents of I Frame",
         .kind = AX25SDL_KIND_PROCESSING},
};

static const ActionStep data_link_connected_t26_i_received_no_actions[] = {
    {.verb = "DL-ERROR Indication (O)", .kind = AX25SDL_KIND_SIGNAL_UPPER},
    {.verb = "Discard I Frame", .kind = AX25SDL_KIND_PROCESSING},
};

static const TransitionSpec data_link_connected_transitions[] = {
    {
        .id = "t01_dl_disconnect_request",
        .from = "Connected",
        .on = "DL_DISCONNECT_request",
        .guard = "",
        .actions = data_link_connected_t01_dl_disconnect_request_actions,
        .actions_len = 5,
        .next = "AwaitingRelease",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t02_dl_data_request",
        .from = "Connected",
        .on = "DL_DATA_request",
        .guard = "",
        .actions = data_link_connected_t02_dl_data_request_actions,
        .actions_len = 1,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t03_i_frame_pops_off_queue_yes",
        .from = "Connected",
        .on = "I_frame_pops_off_queue",
        .guard = "peer_receiver_busy",
        .actions = data_link_connected_t03_i_frame_pops_off_queue_yes_actions,
        .actions_len = 1,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t03_i_frame_pops_off_queue_no_yes",
        .from = "Connected",
        .on = "I_frame_pops_off_queue",
        .guard = "not peer_receiver_busy and vs_eq_va_plus_k",
        .actions =
            data_link_connected_t03_i_frame_pops_off_queue_no_yes_actions,
        .actions_len = 1,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t03_i_frame_pops_off_queue_no_no_no",
        .from = "Connected",
        .on = "I_frame_pops_off_queue",
        .guard =
            "not peer_receiver_busy and not vs_eq_va_plus_k and not T1_running",
        .actions =
            data_link_connected_t03_i_frame_pops_off_queue_no_no_no_actions,
        .actions_len = 8,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t03_i_frame_pops_off_queue_no_no_yes",
        .from = "Connected",
        .on = "I_frame_pops_off_queue",
        .guard =
            "not peer_receiver_busy and not vs_eq_va_plus_k and T1_running",
        .actions =
            data_link_connected_t03_i_frame_pops_off_queue_no_no_yes_actions,
        .actions_len = 6,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t04_dl_unit_data_request",
        .from = "Connected",
        .on = "DL_UNIT_DATA_request",
        .guard = "",
        .actions = data_link_connected_t04_dl_unit_data_request_actions,
        .actions_len = 1,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t05_dl_flow_off_request_yes",
        .from = "Connected",
        .on = "DL_FLOW_OFF_request",
        .guard = "own_receiver_busy",
        .actions = data_link_connected_t05_dl_flow_off_request_yes_actions,
        .actions_len = 3,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t05_dl_flow_off_request_no",
        .from = "Connected",
        .on = "DL_FLOW_OFF_request",
        .guard = "not own_receiver_busy",
        .actions = NULL,
        .actions_len = 0,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t06_dl_flow_on_request_no",
        .from = "Connected",
        .on = "DL_FLOW_ON_request",
        .guard = "not own_receiver_busy",
        .actions = NULL,
        .actions_len = 0,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t06_dl_flow_on_request_yes_yes",
        .from = "Connected",
        .on = "DL_FLOW_ON_request",
        .guard = "own_receiver_busy and T1_running",
        .actions = data_link_connected_t06_dl_flow_on_request_yes_yes_actions,
        .actions_len = 3,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t06_dl_flow_on_request_yes_no",
        .from = "Connected",
        .on = "DL_FLOW_ON_request",
        .guard = "own_receiver_busy and not T1_running",
        .actions = data_link_connected_t06_dl_flow_on_request_yes_no_actions,
        .actions_len = 5,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t07_dl_connect_request_no",
        .from = "Connected",
        .on = "DL_CONNECT_request",
        .guard = "not version_2_2",
        .actions = data_link_connected_t07_dl_connect_request_no_actions,
        .actions_len = 3,
        .next = "AwaitingConnection",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t07_dl_connect_request_yes",
        .from = "Connected",
        .on = "DL_CONNECT_request",
        .guard = "version_2_2",
        .actions = data_link_connected_t07_dl_connect_request_yes_actions,
        .actions_len = 3,
        .next = "AwaitingV22Connection",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t08_all_other_primitives__from_upper_layer",
        .from = "Connected",
        .on = "all_other_primitives__from_upper_layer",
        .guard = "",
        .actions = NULL,
        .actions_len = 0,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t09_control_field_error_no",
        .from = "Connected",
        .on = "control_field_error",
        .guard = "not version_2_2",
        .actions = data_link_connected_t09_control_field_error_no_actions,
        .actions_len = 4,
        .next = "AwaitingConnection",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t09_control_field_error_yes",
        .from = "Connected",
        .on = "control_field_error",
        .guard = "version_2_2",
        .actions = data_link_connected_t09_control_field_error_yes_actions,
        .actions_len = 4,
        .next = "AwaitingV22Connection",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t10_info_not_permitted_in_frame_no",
        .from = "Connected",
        .on = "info_not_permitted_in_frame",
        .guard = "not version_2_2",
        .actions =
            data_link_connected_t10_info_not_permitted_in_frame_no_actions,
        .actions_len = 4,
        .next = "AwaitingConnection",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t10_info_not_permitted_in_frame_yes",
        .from = "Connected",
        .on = "info_not_permitted_in_frame",
        .guard = "version_2_2",
        .actions =
            data_link_connected_t10_info_not_permitted_in_frame_yes_actions,
        .actions_len = 4,
        .next = "AwaitingV22Connection",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t11_u_or_s_frame_length_error_no",
        .from = "Connected",
        .on = "u_or_s_frame_length_error",
        .guard = "not version_2_2",
        .actions = data_link_connected_t11_u_or_s_frame_length_error_no_actions,
        .actions_len = 4,
        .next = "AwaitingConnection",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t11_u_or_s_frame_length_error_yes",
        .from = "Connected",
        .on = "u_or_s_frame_length_error",
        .guard = "version_2_2",
        .actions =
            data_link_connected_t11_u_or_s_frame_length_error_yes_actions,
        .actions_len = 4,
        .next = "AwaitingV22Connection",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t12_t1_expiry",
        .from = "Connected",
        .on = "T1_expiry",
        .guard = "",
        .actions = data_link_connected_t12_t1_expiry_actions,
        .actions_len = 2,
        .next = "TimerRecovery",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t13_t3_expiry",
        .from = "Connected",
        .on = "T3_expiry",
        .guard = "",
        .actions = data_link_connected_t13_t3_expiry_actions,
        .actions_len = 2,
        .next = "TimerRecovery",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t14_sabm_received_yes",
        .from = "Connected",
        .on = "SABM_received",
        .guard = "vs_eq_va",
        .actions = data_link_connected_t14_sabm_received_yes_actions,
        .actions_len = 11,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t14_sabm_received_no",
        .from = "Connected",
        .on = "SABM_received",
        .guard = "not vs_eq_va",
        .actions = data_link_connected_t14_sabm_received_no_actions,
        .actions_len = 13,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t15_sabme_received_yes",
        .from = "Connected",
        .on = "SABME_received",
        .guard = "vs_eq_va",
        .actions = data_link_connected_t15_sabme_received_yes_actions,
        .actions_len = 11,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t15_sabme_received_no",
        .from = "Connected",
        .on = "SABME_received",
        .guard = "not vs_eq_va",
        .actions = data_link_connected_t15_sabme_received_no_actions,
        .actions_len = 13,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t16_frmr_received_no",
        .from = "Connected",
        .on = "FRMR_received",
        .guard = "not version_2_2",
        .actions = data_link_connected_t16_frmr_received_no_actions,
        .actions_len = 3,
        .next = "AwaitingConnection",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t16_frmr_received_yes",
        .from = "Connected",
        .on = "FRMR_received",
        .guard = "version_2_2",
        .actions = data_link_connected_t16_frmr_received_yes_actions,
        .actions_len = 3,
        .next = "AwaitingV22Connection",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t17_ua_received_no",
        .from = "Connected",
        .on = "UA_received",
        .guard = "not version_2_2",
        .actions = data_link_connected_t17_ua_received_no_actions,
        .actions_len = 3,
        .next = "AwaitingConnection",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t17_ua_received_yes",
        .from = "Connected",
        .on = "UA_received",
        .guard = "version_2_2",
        .actions = data_link_connected_t17_ua_received_yes_actions,
        .actions_len = 3,
        .next = "AwaitingV22Connection",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t18_ui_received_yes",
        .from = "Connected",
        .on = "UI_received",
        .guard = "P_eq_1",
        .actions = data_link_connected_t18_ui_received_yes_actions,
        .actions_len = 2,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t18_ui_received_no",
        .from = "Connected",
        .on = "UI_received",
        .guard = "not P_eq_1",
        .actions = data_link_connected_t18_ui_received_no_actions,
        .actions_len = 1,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t19_disc_received",
        .from = "Connected",
        .on = "DISC_received",
        .guard = "",
        .actions = data_link_connected_t19_disc_received_actions,
        .actions_len = 6,
        .next = "Disconnected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t20_dm_received",
        .from = "Connected",
        .on = "DM_received",
        .guard = "",
        .actions = data_link_connected_t20_dm_received_actions,
        .actions_len = 5,
        .next = "Disconnected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t21_rr_received_yes",
        .from = "Connected",
        .on = "RR_received",
        .guard = "va_le_nr_le_vs",
        .actions = data_link_connected_t21_rr_received_yes_actions,
        .actions_len = 3,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t21_rr_received_no_no",
        .from = "Connected",
        .on = "RR_received",
        .guard = "not va_le_nr_le_vs and not version_2_2",
        .actions = data_link_connected_t21_rr_received_no_no_actions,
        .actions_len = 3,
        .next = "AwaitingConnection",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t21_rr_received_no_yes",
        .from = "Connected",
        .on = "RR_received",
        .guard = "not va_le_nr_le_vs and version_2_2",
        .actions = data_link_connected_t21_rr_received_no_yes_actions,
        .actions_len = 3,
        .next = "AwaitingV22Connection",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t22_rnr_received_yes",
        .from = "Connected",
        .on = "RNR_received",
        .guard = "va_le_nr_le_vs",
        .actions = data_link_connected_t22_rnr_received_yes_actions,
        .actions_len = 3,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t22_rnr_received_no_no",
        .from = "Connected",
        .on = "RNR_received",
        .guard = "not va_le_nr_le_vs and not version_2_2",
        .actions = data_link_connected_t22_rnr_received_no_no_actions,
        .actions_len = 3,
        .next = "AwaitingConnection",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t22_rnr_received_no_yes",
        .from = "Connected",
        .on = "RNR_received",
        .guard = "not va_le_nr_le_vs and version_2_2",
        .actions = data_link_connected_t22_rnr_received_no_yes_actions,
        .actions_len = 3,
        .next = "AwaitingV22Connection",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t23_lm_seize_confirm_yes",
        .from = "Connected",
        .on = "LM_SEIZE_confirm",
        .guard = "ack_pending",
        .actions = data_link_connected_t23_lm_seize_confirm_yes_actions,
        .actions_len = 3,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t23_lm_seize_confirm_no",
        .from = "Connected",
        .on = "LM_SEIZE_confirm",
        .guard = "not ack_pending",
        .actions = data_link_connected_t23_lm_seize_confirm_no_actions,
        .actions_len = 1,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t24_srej_received_yes_yes",
        .from = "Connected",
        .on = "SREJ_received",
        .guard = "va_le_nr_le_vs and P_or_F_eq_1",
        .actions = data_link_connected_t24_srej_received_yes_yes_actions,
        .actions_len = 11,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t24_srej_received_yes_no",
        .from = "Connected",
        .on = "SREJ_received",
        .guard = "va_le_nr_le_vs and not P_or_F_eq_1",
        .actions = data_link_connected_t24_srej_received_yes_no_actions,
        .actions_len = 10,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t24_srej_received_no_no",
        .from = "Connected",
        .on = "SREJ_received",
        .guard = "not va_le_nr_le_vs and not version_2_2",
        .actions = data_link_connected_t24_srej_received_no_no_actions,
        .actions_len = 3,
        .next = "AwaitingConnection",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t24_srej_received_no_yes",
        .from = "Connected",
        .on = "SREJ_received",
        .guard = "not va_le_nr_le_vs and version_2_2",
        .actions = data_link_connected_t24_srej_received_no_yes_actions,
        .actions_len = 3,
        .next = "AwaitingV22Connection",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t25_rej_received_no_no",
        .from = "Connected",
        .on = "REJ_received",
        .guard = "not va_le_nr_le_vs and not version_2_2",
        .actions = data_link_connected_t25_rej_received_no_no_actions,
        .actions_len = 3,
        .next = "AwaitingConnection",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t25_rej_received_no_yes",
        .from = "Connected",
        .on = "REJ_received",
        .guard = "not va_le_nr_le_vs and version_2_2",
        .actions = data_link_connected_t25_rej_received_no_yes_actions,
        .actions_len = 3,
        .next = "AwaitingV22Connection",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t25_rej_received_yes",
        .from = "Connected",
        .on = "REJ_received",
        .guard = "va_le_nr_le_vs",
        .actions = data_link_connected_t25_rej_received_yes_actions,
        .actions_len = 8,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t26_i_received_yes_no_no",
        .from = "Connected",
        .on = "I_received",
        .guard = "command and not "
                 "info_field_length_le_N1_and_content_is_octet_aligned and not "
                 "version_2_2",
        .actions = data_link_connected_t26_i_received_yes_no_no_actions,
        .actions_len = 3,
        .next = "AwaitingConnection",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t26_i_received_yes_no_yes",
        .from = "Connected",
        .on = "I_received",
        .guard = "command and not "
                 "info_field_length_le_N1_and_content_is_octet_aligned and "
                 "version_2_2",
        .actions = data_link_connected_t26_i_received_yes_no_yes_actions,
        .actions_len = 3,
        .next = "AwaitingV22Connection",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t26_i_received_yes_yes_no_no",
        .from = "Connected",
        .on = "I_received",
        .guard =
            "command and info_field_length_le_N1_and_content_is_octet_aligned "
            "and not va_le_nr_le_vs and not version_2_2",
        .actions = data_link_connected_t26_i_received_yes_yes_no_no_actions,
        .actions_len = 1,
        .next = "AwaitingConnection",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t26_i_received_yes_yes_no_yes",
        .from = "Connected",
        .on = "I_received",
        .guard =
            "command and info_field_length_le_N1_and_content_is_octet_aligned "
            "and not va_le_nr_le_vs and version_2_2",
        .actions = data_link_connected_t26_i_received_yes_yes_no_yes_actions,
        .actions_len = 1,
        .next = "AwaitingV22Connection",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t26_i_received_yes_yes_yes_no_yes_no_no",
        .from = "Connected",
        .on = "I_received",
        .guard =
            "command and info_field_length_le_N1_and_content_is_octet_aligned "
            "and va_le_nr_le_vs and not own_receiver_busy and ns_eq_vr and not "
            "P_eq_1 and not ack_pending",
        .actions =
            data_link_connected_t26_i_received_yes_yes_yes_no_yes_no_no_actions,
        .actions_len = 10,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops =
            data_link_connected_t26_i_received_yes_yes_yes_no_yes_no_no_loops,
        .loops_len = 1,
    },
    {
        .id = "t26_i_received_yes_yes_yes_no_yes_no_yes",
        .from = "Connected",
        .on = "I_received",
        .guard =
            "command and info_field_length_le_N1_and_content_is_octet_aligned "
            "and va_le_nr_le_vs and not own_receiver_busy and ns_eq_vr and not "
            "P_eq_1 and ack_pending",
        .actions =
            data_link_connected_t26_i_received_yes_yes_yes_no_yes_no_yes_actions,
        .actions_len = 8,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops =
            data_link_connected_t26_i_received_yes_yes_yes_no_yes_no_yes_loops,
        .loops_len = 1,
    },
    {
        .id = "t26_i_received_yes_yes_yes_no_yes_yes",
        .from = "Connected",
        .on = "I_received",
        .guard =
            "command and info_field_length_le_N1_and_content_is_octet_aligned "
            "and va_le_nr_le_vs and not own_receiver_busy and ns_eq_vr and "
            "P_eq_1",
        .actions =
            data_link_connected_t26_i_received_yes_yes_yes_no_yes_yes_actions,
        .actions_len = 12,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops =
            data_link_connected_t26_i_received_yes_yes_yes_no_yes_yes_loops,
        .loops_len = 1,
    },
    {
        .id = "t26_i_received_yes_yes_yes_no_no_yes_yes_yes",
        .from = "Connected",
        .on = "I_received",
        .guard =
            "command and info_field_length_le_N1_and_content_is_octet_aligned "
            "and va_le_nr_le_vs and not own_receiver_busy and not ns_eq_vr and "
            "vr_lt_ns_lt_vr_plus_k and reject_exception and P_eq_1",
        .actions =
            data_link_connected_t26_i_received_yes_yes_yes_no_no_yes_yes_yes_actions,
        .actions_len = 6,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t26_i_received_yes_yes_yes_no_no_yes_yes_no",
        .from = "Connected",
        .on = "I_received",
        .guard =
            "command and info_field_length_le_N1_and_content_is_octet_aligned "
            "and va_le_nr_le_vs and not own_receiver_busy and not ns_eq_vr and "
            "vr_lt_ns_lt_vr_plus_k and reject_exception and not P_eq_1",
        .actions =
            data_link_connected_t26_i_received_yes_yes_yes_no_no_yes_yes_no_actions,
        .actions_len = 2,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t26_i_received_yes_yes_yes_no_no_yes_no_no",
        .from = "Connected",
        .on = "I_received",
        .guard =
            "command and info_field_length_le_N1_and_content_is_octet_aligned "
            "and va_le_nr_le_vs and not own_receiver_busy and not ns_eq_vr and "
            "vr_lt_ns_lt_vr_plus_k and not reject_exception and not "
            "SREJ_enabled",
        .actions =
            data_link_connected_t26_i_received_yes_yes_yes_no_no_yes_no_no_actions,
        .actions_len = 7,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t26_i_received_yes_yes_yes_no_no_yes_no_yes_yes",
        .from = "Connected",
        .on = "I_received",
        .guard =
            "command and info_field_length_le_N1_and_content_is_octet_aligned "
            "and va_le_nr_le_vs and not own_receiver_busy and not ns_eq_vr and "
            "vr_lt_ns_lt_vr_plus_k and not reject_exception and SREJ_enabled "
            "and sreject_exception_gt_0",
        .actions =
            data_link_connected_t26_i_received_yes_yes_yes_no_no_yes_no_yes_yes_actions,
        .actions_len = 6,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t26_i_received_yes_yes_yes_no_no_yes_no_yes_no_yes",
        .from = "Connected",
        .on = "I_received",
        .guard =
            "command and info_field_length_le_N1_and_content_is_octet_aligned "
            "and va_le_nr_le_vs and not own_receiver_busy and not ns_eq_vr and "
            "vr_lt_ns_lt_vr_plus_k and not reject_exception and SREJ_enabled "
            "and not sreject_exception_gt_0 and ns_gt_vr_plus_1",
        .actions =
            data_link_connected_t26_i_received_yes_yes_yes_no_no_yes_no_yes_no_yes_actions,
        .actions_len = 8,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t26_i_received_yes_yes_yes_no_no_yes_no_yes_no_no",
        .from = "Connected",
        .on = "I_received",
        .guard =
            "command and info_field_length_le_N1_and_content_is_octet_aligned "
            "and va_le_nr_le_vs and not own_receiver_busy and not ns_eq_vr and "
            "vr_lt_ns_lt_vr_plus_k and not reject_exception and SREJ_enabled "
            "and not sreject_exception_gt_0 and not ns_gt_vr_plus_1",
        .actions =
            data_link_connected_t26_i_received_yes_yes_yes_no_no_yes_no_yes_no_no_actions,
        .actions_len = 6,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t26_i_received_yes_yes_yes_no_no_no_yes",
        .from = "Connected",
        .on = "I_received",
        .guard =
            "command and info_field_length_le_N1_and_content_is_octet_aligned "
            "and va_le_nr_le_vs and not own_receiver_busy and not ns_eq_vr and "
            "not vr_lt_ns_lt_vr_plus_k and P_eq_1",
        .actions =
            data_link_connected_t26_i_received_yes_yes_yes_no_no_no_yes_actions,
        .actions_len = 6,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t26_i_received_yes_yes_yes_no_no_no_no",
        .from = "Connected",
        .on = "I_received",
        .guard =
            "command and info_field_length_le_N1_and_content_is_octet_aligned "
            "and va_le_nr_le_vs and not own_receiver_busy and not ns_eq_vr and "
            "not vr_lt_ns_lt_vr_plus_k and not P_eq_1",
        .actions =
            data_link_connected_t26_i_received_yes_yes_yes_no_no_no_no_actions,
        .actions_len = 2,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t26_i_received_yes_yes_yes_yes_yes",
        .from = "Connected",
        .on = "I_received",
        .guard =
            "command and info_field_length_le_N1_and_content_is_octet_aligned "
            "and va_le_nr_le_vs and own_receiver_busy and P_eq_1",
        .actions =
            data_link_connected_t26_i_received_yes_yes_yes_yes_yes_actions,
        .actions_len = 6,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t26_i_received_yes_yes_yes_yes_no",
        .from = "Connected",
        .on = "I_received",
        .guard =
            "command and info_field_length_le_N1_and_content_is_octet_aligned "
            "and va_le_nr_le_vs and own_receiver_busy and not P_eq_1",
        .actions =
            data_link_connected_t26_i_received_yes_yes_yes_yes_no_actions,
        .actions_len = 2,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
    {
        .id = "t26_i_received_no",
        .from = "Connected",
        .on = "I_received",
        .guard = "not command",
        .actions = data_link_connected_t26_i_received_no_actions,
        .actions_len = 2,
        .next = "Connected",
        .notes = "",
        .references = NULL,
        .references_len = 0,
        .loops = NULL,
        .loops_len = 0,
    },
};

const StatePage data_link_connected = {
    .machine = "data_link",
    .state = "Connected",
    .source = {.spec = "ax.25.2.2.4_Oct_25", .figure = "figc4.4", .url = ""},
    .transitions = data_link_connected_transitions,
    .transitions_len = 68,
};
