// <auto-generated>
//   This file was produced by codegen/src/Packet.Sdl.CodeGen from a *.sdl.yaml under /spec-sdl/.
//   Do not edit by hand. Run `dotnet run --project codegen/src/Packet.Sdl.CodeGen` to regenerate.
// </auto-generated>

using System.Linq;
using AwesomeAssertions;
using Packet.Ax25.Sdl;
using Xunit;

namespace Packet.Ax25.Conformance.Tests;

public class DataLink_TimerRecovery_GeneratedTests
{
    [Fact] public void SourceFigure() => DataLink_TimerRecovery.Source.Figure.Should().Be("figc4.5");

    [Fact] public void TransitionsArePresent() => DataLink_TimerRecovery.Transitions.Count.Should().Be(92);

    [Fact] public void t01_dl_disconnect_request()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t01_dl_disconnect_request");
        t.On.Should().Be(Ax25Event.DLDISCONNECTRequest);
        t.Next.Should().Be("AwaitingRelease");
        t.Actions.Count.Should().Be(5);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.DiscardIFrameQueue);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.RCAssign0);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.DISCPEq1);
        t.Actions[2].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.StopT3);
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be(Ax25ActionVerb.StartT1);
        t.Actions[4].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t02_dl_data_request()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t02_dl_data_request");
        t.On.Should().Be(Ax25Event.DLDATARequest);
        t.Next.Should().Be("TimerRecovery");
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.PushOnIFrameQueue);
        t.Actions[0].Kind.Should().Be(ActionKind.InternalOut);
    }

    [Fact] public void t03_i_frame_pops_off_queue_yes()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t03_i_frame_pops_off_queue_yes");
        t.On.Should().Be(Ax25Event.IFramePopsOffQueue);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.PeerReceiverBusy, false) });
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.PushIFrameOnIQueue);
        t.Actions[0].Kind.Should().Be(ActionKind.InternalOut);
    }

    [Fact] public void t03_i_frame_pops_off_queue_no_yes()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t03_i_frame_pops_off_queue_no_yes");
        t.On.Should().Be(Ax25Event.IFramePopsOffQueue);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.PeerReceiverBusy, true), new GuardTerm(Ax25Guard.VsEqVaPlusK, false) });
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.PushIFrameOnIQueue);
        t.Actions[0].Kind.Should().Be(ActionKind.InternalOut);
    }

    [Fact] public void t03_i_frame_pops_off_queue_no_no_yes()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t03_i_frame_pops_off_queue_no_no_yes");
        t.On.Should().Be(Ax25Event.IFramePopsOffQueue);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.PeerReceiverBusy, true), new GuardTerm(Ax25Guard.VsEqVaPlusK, true), new GuardTerm(Ax25Guard.T1Running, false) });
        t.Actions.Count.Should().Be(6);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.NSAssignVS);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.NRAssignVR);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.PAssign0);
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.ICommand);
        t.Actions[3].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[4].Verb.Should().Be(Ax25ActionVerb.VSAssignVSPlus1);
        t.Actions[4].Kind.Should().Be(ActionKind.Processing);
        t.Actions[5].Verb.Should().Be(Ax25ActionVerb.ClearAcknowledgePending);
        t.Actions[5].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t03_i_frame_pops_off_queue_no_no_no()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t03_i_frame_pops_off_queue_no_no_no");
        t.On.Should().Be(Ax25Event.IFramePopsOffQueue);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.PeerReceiverBusy, true), new GuardTerm(Ax25Guard.VsEqVaPlusK, true), new GuardTerm(Ax25Guard.T1Running, true) });
        t.Actions.Count.Should().Be(8);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.NSAssignVS);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.NRAssignVR);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.PAssign0);
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.ICommand);
        t.Actions[3].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[4].Verb.Should().Be(Ax25ActionVerb.VSAssignVSPlus1);
        t.Actions[4].Kind.Should().Be(ActionKind.Processing);
        t.Actions[5].Verb.Should().Be(Ax25ActionVerb.ClearAcknowledgePending);
        t.Actions[5].Kind.Should().Be(ActionKind.Processing);
        t.Actions[6].Verb.Should().Be(Ax25ActionVerb.StopT3);
        t.Actions[6].Kind.Should().Be(ActionKind.Processing);
        t.Actions[7].Verb.Should().Be(Ax25ActionVerb.StartT1);
        t.Actions[7].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t04_dl_unit_data_request()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t04_dl_unit_data_request");
        t.On.Should().Be(Ax25Event.DLUNITDATARequest);
        t.Next.Should().Be("TimerRecovery");
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.UICommand);
        t.Actions[0].Kind.Should().Be(ActionKind.SignalLower);
    }

    [Fact] public void t05_dl_flow_off_request_yes()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t05_dl_flow_off_request_yes");
        t.On.Should().Be(Ax25Event.DLFLOWOFFRequest);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.OwnReceiverBusy, false) });
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.SetOwnReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.RNRResponseFEq0);
        t.Actions[1].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.ClearAcknowledgePending);
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t05_dl_flow_off_request_no()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t05_dl_flow_off_request_no");
        t.On.Should().Be(Ax25Event.DLFLOWOFFRequest);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.OwnReceiverBusy, true) });
        t.Actions.Count.Should().Be(0);
    }

    [Fact] public void t06_dl_flow_on_request_yes_no()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t06_dl_flow_on_request_yes_no");
        t.On.Should().Be(Ax25Event.DLFLOWONRequest);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.OwnReceiverBusy, false), new GuardTerm(Ax25Guard.T1Running, true) });
        t.Actions.Count.Should().Be(5);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.ClearOwnReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.RRCommandPEq0);
        t.Actions[1].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.ClearAcknowledgePending);
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.StopT3);
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be(Ax25ActionVerb.StartT1);
        t.Actions[4].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t06_dl_flow_on_request_yes_yes()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t06_dl_flow_on_request_yes_yes");
        t.On.Should().Be(Ax25Event.DLFLOWONRequest);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.OwnReceiverBusy, false), new GuardTerm(Ax25Guard.T1Running, false) });
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.ClearOwnReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.RRCommandPEq0);
        t.Actions[1].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.ClearAcknowledgePending);
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t06_dl_flow_on_request_no()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t06_dl_flow_on_request_no");
        t.On.Should().Be(Ax25Event.DLFLOWONRequest);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.OwnReceiverBusy, true) });
        t.Actions.Count.Should().Be(0);
    }

    [Fact] public void t07_dl_connect_request()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t07_dl_connect_request");
        t.On.Should().Be(Ax25Event.DLCONNECTRequest);
        t.Next.Should().Be("TimerRecovery");
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.DiscardIFrameQueue);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.EstablishDataLink);
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.SetLayer3Initiated);
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t08_control_field_error()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t08_control_field_error");
        t.On.Should().Be(Ax25Event.ControlFieldError);
        t.Next.Should().Be("TimerRecovery");
        t.Actions.Count.Should().Be(4);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.DLERRORIndicationL);
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.DiscardIFrameQueue);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.EstablishDataLink);
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.SetLayer3Initiated);
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t09_info_not_permitted_in_frame()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t09_info_not_permitted_in_frame");
        t.On.Should().Be(Ax25Event.InfoNotPermittedInFrame);
        t.Next.Should().Be("TimerRecovery");
        t.Actions.Count.Should().Be(4);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.DLERRORIndicationM);
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.DiscardIFrameQueue);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.EstablishDataLink);
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.SetLayer3Initiated);
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t10_u_or_s_frame_length_error()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t10_u_or_s_frame_length_error");
        t.On.Should().Be(Ax25Event.UOrSFrameLengthError);
        t.Next.Should().Be("TimerRecovery");
        t.Actions.Count.Should().Be(4);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.DLERRORIndicationN);
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.DiscardIFrameQueue);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.EstablishDataLink);
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.SetLayer3Initiated);
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t11_ua_received()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t11_ua_received");
        t.On.Should().Be(Ax25Event.UAReceived);
        t.Next.Should().Be("AwaitingConnection");
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.DLERRORIndicationN);
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.EstablishDataLink);
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.ClearLayer3Initiated);
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t12_dm_received()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t12_dm_received");
        t.On.Should().Be(Ax25Event.DMReceived);
        t.Next.Should().Be("Disconnected");
        t.Actions.Count.Should().Be(5);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.DLERRORIndicationE);
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.DLDISCONNECTIndication);
        t.Actions[1].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.DiscardIFrameQueue);
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.StopT1);
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be(Ax25ActionVerb.StopT3);
        t.Actions[4].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t13_sabm_received_no()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t13_sabm_received_no");
        t.On.Should().Be(Ax25Event.SABMReceived);
        t.Next.Should().Be("Connected");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.VsEqVa, true) });
        t.Actions.Count.Should().Be(12);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.FAssignP);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.SetVersion20);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.UA);
        t.Actions[2].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.ClearExceptionConditions);
        t.Actions[3].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[4].Verb.Should().Be(Ax25ActionVerb.DLERRORIndicationF);
        t.Actions[4].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[5].Verb.Should().Be(Ax25ActionVerb.DiscardIFrameQueue);
        t.Actions[5].Kind.Should().Be(ActionKind.Processing);
        t.Actions[6].Verb.Should().Be(Ax25ActionVerb.DLCONNECTIndication);
        t.Actions[6].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[7].Verb.Should().Be(Ax25ActionVerb.StopT1);
        t.Actions[7].Kind.Should().Be(ActionKind.Processing);
        t.Actions[8].Verb.Should().Be(Ax25ActionVerb.StopT3);
        t.Actions[8].Kind.Should().Be(ActionKind.Processing);
        t.Actions[9].Verb.Should().Be(Ax25ActionVerb.VSAssign0);
        t.Actions[9].Kind.Should().Be(ActionKind.Processing);
        t.Actions[10].Verb.Should().Be(Ax25ActionVerb.VAAssign0);
        t.Actions[10].Kind.Should().Be(ActionKind.Processing);
        t.Actions[11].Verb.Should().Be(Ax25ActionVerb.VRAssign0);
        t.Actions[11].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t13_sabm_received_yes()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t13_sabm_received_yes");
        t.On.Should().Be(Ax25Event.SABMReceived);
        t.Next.Should().Be("Connected");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.VsEqVa, false) });
        t.Actions.Count.Should().Be(5);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.FAssignP);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.SetVersion20);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.UA);
        t.Actions[2].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.ClearExceptionConditions);
        t.Actions[3].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[4].Verb.Should().Be(Ax25ActionVerb.DLERRORIndicationF);
        t.Actions[4].Kind.Should().Be(ActionKind.SignalUpper);
    }

    [Fact] public void t14_sabme_received_no()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t14_sabme_received_no");
        t.On.Should().Be(Ax25Event.SABMEReceived);
        t.Next.Should().Be("Connected");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.VsEqVa, true) });
        t.Actions.Count.Should().Be(12);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.FAssignP);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.SetVersion22);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.UA);
        t.Actions[2].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.ClearExceptionConditions);
        t.Actions[3].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[4].Verb.Should().Be(Ax25ActionVerb.DLERRORIndicationF);
        t.Actions[4].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[5].Verb.Should().Be(Ax25ActionVerb.DiscardIFrameQueue);
        t.Actions[5].Kind.Should().Be(ActionKind.Processing);
        t.Actions[6].Verb.Should().Be(Ax25ActionVerb.DLCONNECTIndication);
        t.Actions[6].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[7].Verb.Should().Be(Ax25ActionVerb.StopT1);
        t.Actions[7].Kind.Should().Be(ActionKind.Processing);
        t.Actions[8].Verb.Should().Be(Ax25ActionVerb.StopT3);
        t.Actions[8].Kind.Should().Be(ActionKind.Processing);
        t.Actions[9].Verb.Should().Be(Ax25ActionVerb.VSAssign0);
        t.Actions[9].Kind.Should().Be(ActionKind.Processing);
        t.Actions[10].Verb.Should().Be(Ax25ActionVerb.VAAssign0);
        t.Actions[10].Kind.Should().Be(ActionKind.Processing);
        t.Actions[11].Verb.Should().Be(Ax25ActionVerb.VRAssign0);
        t.Actions[11].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t14_sabme_received_yes()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t14_sabme_received_yes");
        t.On.Should().Be(Ax25Event.SABMEReceived);
        t.Next.Should().Be("Connected");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.VsEqVa, false) });
        t.Actions.Count.Should().Be(5);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.FAssignP);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.SetVersion22);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.UA);
        t.Actions[2].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.ClearExceptionConditions);
        t.Actions[3].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[4].Verb.Should().Be(Ax25ActionVerb.DLERRORIndicationF);
        t.Actions[4].Kind.Should().Be(ActionKind.SignalUpper);
    }

    [Fact] public void t15_frmr_received()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t15_frmr_received");
        t.On.Should().Be(Ax25Event.FRMRReceived);
        t.Next.Should().Be("AwaitingConnection");
        t.Actions.Count.Should().Be(4);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.DLERRORIndicationK);
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.SetVersion20);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.EstablishDataLink);
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.ClearLayer3Initiated);
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t16_ui_received_yes()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t16_ui_received_yes");
        t.On.Should().Be(Ax25Event.UIReceived);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.PEq1, false) });
        t.Actions.Count.Should().Be(2);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.UICheck);
        t.Actions[0].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.EnquiryResponseF1);
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t16_ui_received_no()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t16_ui_received_no");
        t.On.Should().Be(Ax25Event.UIReceived);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.PEq1, true) });
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.UICheck);
        t.Actions[0].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t17_disc_received()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t17_disc_received");
        t.On.Should().Be(Ax25Event.DISCReceived);
        t.Next.Should().Be("Disconnected");
        t.Actions.Count.Should().Be(6);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.DiscardIFrameQueue);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.FAssignP);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.UA);
        t.Actions[2].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.DLDISCONNECTIndication);
        t.Actions[3].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[4].Verb.Should().Be(Ax25ActionVerb.StopT1);
        t.Actions[4].Kind.Should().Be(ActionKind.Processing);
        t.Actions[5].Verb.Should().Be(Ax25ActionVerb.StopT3);
        t.Actions[5].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t18_rr_received_no_yes_yes()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t18_rr_received_no_yes_yes");
        t.On.Should().Be(Ax25Event.RRReceived);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.ResponseAndFEq1, true), new GuardTerm(Ax25Guard.CommandAndPEq1, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, false) });
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.ClearPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.EnquiryResponseF1);
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.VAAssignNR);
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t18_rr_received_no_yes_no_no()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t18_rr_received_no_yes_no_no");
        t.On.Should().Be(Ax25Event.RRReceived);
        t.Next.Should().Be("AwaitingConnection");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.ResponseAndFEq1, true), new GuardTerm(Ax25Guard.CommandAndPEq1, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, true), new GuardTerm(Ax25Guard.Version22, true) });
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.ClearPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.EnquiryResponseF1);
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.NRRecovery);
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t18_rr_received_no_yes_no_yes()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t18_rr_received_no_yes_no_yes");
        t.On.Should().Be(Ax25Event.RRReceived);
        t.Next.Should().Be("AwaitingV22Connection");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.ResponseAndFEq1, true), new GuardTerm(Ax25Guard.CommandAndPEq1, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, true), new GuardTerm(Ax25Guard.Version22, false) });
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.ClearPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.EnquiryResponseF1);
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.NRRecovery);
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t18_rr_received_no_no_yes()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t18_rr_received_no_no_yes");
        t.On.Should().Be(Ax25Event.RRReceived);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.ResponseAndFEq1, true), new GuardTerm(Ax25Guard.CommandAndPEq1, true), new GuardTerm(Ax25Guard.VaLeNrLeVs, false) });
        t.Actions.Count.Should().Be(2);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.ClearPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.VAAssignNR);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t18_rr_received_no_no_no()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t18_rr_received_no_no_no");
        t.On.Should().Be(Ax25Event.RRReceived);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.ResponseAndFEq1, true), new GuardTerm(Ax25Guard.CommandAndPEq1, true), new GuardTerm(Ax25Guard.VaLeNrLeVs, true) });
        t.Actions.Count.Should().Be(2);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.ClearPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.NRRecovery);
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t18_rr_received_yes_no_no()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t18_rr_received_yes_no_no");
        t.On.Should().Be(Ax25Event.RRReceived);
        t.Next.Should().Be("AwaitingConnection");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.ResponseAndFEq1, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, true), new GuardTerm(Ax25Guard.Version22, true) });
        t.Actions.Count.Should().Be(4);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.ClearPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.StopT1);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.SelectT1Value);
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.NRRecovery);
        t.Actions[3].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t18_rr_received_yes_no_yes()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t18_rr_received_yes_no_yes");
        t.On.Should().Be(Ax25Event.RRReceived);
        t.Next.Should().Be("AwaitingV22Connection");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.ResponseAndFEq1, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, true), new GuardTerm(Ax25Guard.Version22, false) });
        t.Actions.Count.Should().Be(4);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.ClearPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.StopT1);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.SelectT1Value);
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.NRRecovery);
        t.Actions[3].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t18_rr_received_yes_yes_no()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t18_rr_received_yes_yes_no");
        t.On.Should().Be(Ax25Event.RRReceived);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.ResponseAndFEq1, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, false), new GuardTerm(Ax25Guard.VsEqNr, true) });
        t.Actions.Count.Should().Be(8);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.ClearPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.StopT1);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.SelectT1Value);
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.VAAssignNR);
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be(Ax25ActionVerb.InvokeRetransmission);
        t.Actions[4].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[5].Verb.Should().Be(Ax25ActionVerb.StopT3);
        t.Actions[5].Kind.Should().Be(ActionKind.Processing);
        t.Actions[6].Verb.Should().Be(Ax25ActionVerb.StartT1);
        t.Actions[6].Kind.Should().Be(ActionKind.Processing);
        t.Actions[7].Verb.Should().Be(Ax25ActionVerb.SetAcknowledgePending);
        t.Actions[7].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t18_rr_received_yes_yes_yes()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t18_rr_received_yes_yes_yes");
        t.On.Should().Be(Ax25Event.RRReceived);
        t.Next.Should().Be("Connected");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.ResponseAndFEq1, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, false), new GuardTerm(Ax25Guard.VsEqNr, false) });
        t.Actions.Count.Should().Be(6);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.ClearPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.StopT1);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.SelectT1Value);
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.VAAssignNR);
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be(Ax25ActionVerb.StartT3);
        t.Actions[4].Kind.Should().Be(ActionKind.Processing);
        t.Actions[5].Verb.Should().Be(Ax25ActionVerb.RCAssign0);
        t.Actions[5].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t19_rnr_received_no_yes_yes()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t19_rnr_received_no_yes_yes");
        t.On.Should().Be(Ax25Event.RNRReceived);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.ResponseAndFEq1, true), new GuardTerm(Ax25Guard.CommandAndPEq1, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, false) });
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.SetPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.EnquiryResponseF1);
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.VAAssignNR);
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t19_rnr_received_no_yes_no_no()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t19_rnr_received_no_yes_no_no");
        t.On.Should().Be(Ax25Event.RNRReceived);
        t.Next.Should().Be("AwaitingConnection");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.ResponseAndFEq1, true), new GuardTerm(Ax25Guard.CommandAndPEq1, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, true), new GuardTerm(Ax25Guard.Version22, true) });
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.SetPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.EnquiryResponseF1);
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.NRRecovery);
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t19_rnr_received_no_yes_no_yes()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t19_rnr_received_no_yes_no_yes");
        t.On.Should().Be(Ax25Event.RNRReceived);
        t.Next.Should().Be("AwaitingV22Connection");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.ResponseAndFEq1, true), new GuardTerm(Ax25Guard.CommandAndPEq1, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, true), new GuardTerm(Ax25Guard.Version22, false) });
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.SetPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.EnquiryResponseF1);
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.NRRecovery);
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t19_rnr_received_no_no_yes()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t19_rnr_received_no_no_yes");
        t.On.Should().Be(Ax25Event.RNRReceived);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.ResponseAndFEq1, true), new GuardTerm(Ax25Guard.CommandAndPEq1, true), new GuardTerm(Ax25Guard.VaLeNrLeVs, false) });
        t.Actions.Count.Should().Be(2);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.SetPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.VAAssignNR);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t19_rnr_received_no_no_no()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t19_rnr_received_no_no_no");
        t.On.Should().Be(Ax25Event.RNRReceived);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.ResponseAndFEq1, true), new GuardTerm(Ax25Guard.CommandAndPEq1, true), new GuardTerm(Ax25Guard.VaLeNrLeVs, true) });
        t.Actions.Count.Should().Be(2);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.SetPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.NRRecovery);
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t19_rnr_received_yes_no_no()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t19_rnr_received_yes_no_no");
        t.On.Should().Be(Ax25Event.RNRReceived);
        t.Next.Should().Be("AwaitingConnection");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.ResponseAndFEq1, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, true), new GuardTerm(Ax25Guard.Version22, true) });
        t.Actions.Count.Should().Be(4);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.SetPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.StopT1);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.SelectT1Value);
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.NRRecovery);
        t.Actions[3].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t19_rnr_received_yes_no_yes()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t19_rnr_received_yes_no_yes");
        t.On.Should().Be(Ax25Event.RNRReceived);
        t.Next.Should().Be("AwaitingV22Connection");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.ResponseAndFEq1, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, true), new GuardTerm(Ax25Guard.Version22, false) });
        t.Actions.Count.Should().Be(4);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.SetPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.StopT1);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.SelectT1Value);
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.NRRecovery);
        t.Actions[3].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t19_rnr_received_yes_yes_no()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t19_rnr_received_yes_yes_no");
        t.On.Should().Be(Ax25Event.RNRReceived);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.ResponseAndFEq1, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, false), new GuardTerm(Ax25Guard.VsEqNr, true) });
        t.Actions.Count.Should().Be(8);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.SetPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.StopT1);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.SelectT1Value);
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.VAAssignNR);
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be(Ax25ActionVerb.InvokeRetransmission);
        t.Actions[4].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[5].Verb.Should().Be(Ax25ActionVerb.StopT3);
        t.Actions[5].Kind.Should().Be(ActionKind.Processing);
        t.Actions[6].Verb.Should().Be(Ax25ActionVerb.StartT1);
        t.Actions[6].Kind.Should().Be(ActionKind.Processing);
        t.Actions[7].Verb.Should().Be(Ax25ActionVerb.SetAcknowledgePending);
        t.Actions[7].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t19_rnr_received_yes_yes_yes()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t19_rnr_received_yes_yes_yes");
        t.On.Should().Be(Ax25Event.RNRReceived);
        t.Next.Should().Be("Connected");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.ResponseAndFEq1, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, false), new GuardTerm(Ax25Guard.VsEqNr, false) });
        t.Actions.Count.Should().Be(6);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.SetPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.StopT1);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.SelectT1Value);
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.VAAssignNR);
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be(Ax25ActionVerb.StartT3);
        t.Actions[4].Kind.Should().Be(ActionKind.Processing);
        t.Actions[5].Verb.Should().Be(Ax25ActionVerb.RCAssign0);
        t.Actions[5].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t20_lm_seize_confirm_yes()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t20_lm_seize_confirm_yes");
        t.On.Should().Be(Ax25Event.LMSEIZEConfirm);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.AckPending, false) });
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.ClearAcknowledgePending);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.EnquiryResponseFEq0);
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.LMReleaseRequest);
        t.Actions[2].Kind.Should().Be(ActionKind.SignalLower);
    }

    [Fact] public void t20_lm_seize_confirm_no()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t20_lm_seize_confirm_no");
        t.On.Should().Be(Ax25Event.LMSEIZEConfirm);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.AckPending, true) });
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.LMReleaseRequest);
        t.Actions[0].Kind.Should().Be(ActionKind.SignalLower);
    }

    [Fact] public void t21_t1_expiry_no()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t21_t1_expiry_no");
        t.On.Should().Be(Ax25Event.T1Expiry);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.RCEqN2, true) });
        t.Actions.Count.Should().Be(2);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.TransmitEnquiry);
        t.Actions[0].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.RCAssignRCPlus1);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t21_t1_expiry_yes_yes_yes()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t21_t1_expiry_yes_yes_yes");
        t.On.Should().Be(Ax25Event.T1Expiry);
        t.Next.Should().Be("Disconnected");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.RCEqN2, false), new GuardTerm(Ax25Guard.VsEqVa, false), new GuardTerm(Ax25Guard.PeerReceiverBusy, false) });
        t.Actions.Count.Should().Be(4);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.DLERRORIndicationU);
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.DLDISCONNECTIndication);
        t.Actions[1].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.DiscardIFrameQueue);
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.DMResponseFEq0);
        t.Actions[3].Kind.Should().Be(ActionKind.SignalLower);
    }

    [Fact] public void t21_t1_expiry_yes_yes_no()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t21_t1_expiry_yes_yes_no");
        t.On.Should().Be(Ax25Event.T1Expiry);
        t.Next.Should().Be("Disconnected");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.RCEqN2, false), new GuardTerm(Ax25Guard.VsEqVa, false), new GuardTerm(Ax25Guard.PeerReceiverBusy, true) });
        t.Actions.Count.Should().Be(4);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.DLERRORIndicationT);
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.DLDISCONNECTIndication);
        t.Actions[1].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.DiscardIFrameQueue);
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.DMResponseFEq0);
        t.Actions[3].Kind.Should().Be(ActionKind.SignalLower);
    }

    [Fact] public void t21_t1_expiry_yes_no()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t21_t1_expiry_yes_no");
        t.On.Should().Be(Ax25Event.T1Expiry);
        t.Next.Should().Be("Disconnected");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.RCEqN2, false), new GuardTerm(Ax25Guard.VsEqVa, true) });
        t.Actions.Count.Should().Be(4);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.DLERRORIndicationI);
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.DLDISCONNECTIndication);
        t.Actions[1].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.DiscardIFrameQueue);
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.DMResponseFEq0);
        t.Actions[3].Kind.Should().Be(ActionKind.SignalLower);
    }

    [Fact] public void t22_i_received_no()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t22_i_received_no");
        t.On.Should().Be(Ax25Event.IReceived);
        t.Next.Should().Be("Connected");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.Command, true) });
        t.Actions.Count.Should().Be(2);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.DLERRORIndicationO);
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.DiscardIFrame);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t22_i_received_yes_no()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t22_i_received_yes_no");
        t.On.Should().Be(Ax25Event.IReceived);
        t.Next.Should().Be("AwaitingConnection");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.Command, false), new GuardTerm(Ax25Guard.InfoFieldLengthLeN1AndContentIsOctetAligned, true) });
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.DLERRORIndicationO);
        t.Actions[0].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.EstablishDataLink);
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.ClearLayer3Initiated);
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t22_i_received_yes_yes_no()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t22_i_received_yes_yes_no");
        t.On.Should().Be(Ax25Event.IReceived);
        t.Next.Should().Be("AwaitingConnection");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.Command, false), new GuardTerm(Ax25Guard.InfoFieldLengthLeN1AndContentIsOctetAligned, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, true) });
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.NRRecovery);
        t.Actions[0].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t22_i_received_yes_yes_yes_yes_yes()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t22_i_received_yes_yes_yes_yes_yes");
        t.On.Should().Be(Ax25Event.IReceived);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.Command, false), new GuardTerm(Ax25Guard.InfoFieldLengthLeN1AndContentIsOctetAligned, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, false), new GuardTerm(Ax25Guard.OwnReceiverBusy, false), new GuardTerm(Ax25Guard.PEq1, false) });
        t.Actions.Count.Should().Be(6);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.CheckIFrameAcknowledged);
        t.Actions[0].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.DiscardContentsOfIFrame);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.FAssign1);
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.NRAssignVR);
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be(Ax25ActionVerb.RNR);
        t.Actions[4].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[5].Verb.Should().Be(Ax25ActionVerb.ClearAcknowledgePending);
        t.Actions[5].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t22_i_received_yes_yes_yes_yes_no()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t22_i_received_yes_yes_yes_yes_no");
        t.On.Should().Be(Ax25Event.IReceived);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.Command, false), new GuardTerm(Ax25Guard.InfoFieldLengthLeN1AndContentIsOctetAligned, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, false), new GuardTerm(Ax25Guard.OwnReceiverBusy, false), new GuardTerm(Ax25Guard.PEq1, true) });
        t.Actions.Count.Should().Be(2);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.CheckIFrameAcknowledged);
        t.Actions[0].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.DiscardContentsOfIFrame);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t22_i_received_yes_yes_yes_no_yes_yes()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t22_i_received_yes_yes_yes_no_yes_yes");
        t.On.Should().Be(Ax25Event.IReceived);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.Command, false), new GuardTerm(Ax25Guard.InfoFieldLengthLeN1AndContentIsOctetAligned, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, false), new GuardTerm(Ax25Guard.OwnReceiverBusy, true), new GuardTerm(Ax25Guard.NsEqVr, false), new GuardTerm(Ax25Guard.PEq1, false) });
        t.Actions.Count.Should().Be(12);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.CheckIFrameAcknowledged);
        t.Actions[0].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.VRAssignVRPlus1);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.ClearRejectException);
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.DecrementSrejectExceptionIf0);
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be(Ax25ActionVerb.DLDATAIndication);
        t.Actions[4].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[5].Verb.Should().Be(Ax25ActionVerb.RetrieveStoredVRIFrame);
        t.Actions[5].Kind.Should().Be(ActionKind.Processing);
        t.Actions[6].Verb.Should().Be(Ax25ActionVerb.DLDATAIndication);
        t.Actions[6].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[7].Verb.Should().Be(Ax25ActionVerb.VRAssignVR1);
        t.Actions[7].Kind.Should().Be(ActionKind.Processing);
        t.Actions[8].Verb.Should().Be(Ax25ActionVerb.FAssign1);
        t.Actions[8].Kind.Should().Be(ActionKind.Processing);
        t.Actions[9].Verb.Should().Be(Ax25ActionVerb.NRAssignVR);
        t.Actions[9].Kind.Should().Be(ActionKind.Processing);
        t.Actions[10].Verb.Should().Be(Ax25ActionVerb.RR);
        t.Actions[10].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[11].Verb.Should().Be(Ax25ActionVerb.ClearAcknowledgePending);
        t.Actions[11].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t22_i_received_yes_yes_yes_no_yes_no_no()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t22_i_received_yes_yes_yes_no_yes_no_no");
        t.On.Should().Be(Ax25Event.IReceived);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.Command, false), new GuardTerm(Ax25Guard.InfoFieldLengthLeN1AndContentIsOctetAligned, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, false), new GuardTerm(Ax25Guard.OwnReceiverBusy, true), new GuardTerm(Ax25Guard.NsEqVr, false), new GuardTerm(Ax25Guard.PEq1, true), new GuardTerm(Ax25Guard.AckPending, true) });
        t.Actions.Count.Should().Be(10);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.CheckIFrameAcknowledged);
        t.Actions[0].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.VRAssignVRPlus1);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.ClearRejectException);
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.DecrementSrejectExceptionIf0);
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be(Ax25ActionVerb.DLDATAIndication);
        t.Actions[4].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[5].Verb.Should().Be(Ax25ActionVerb.RetrieveStoredVRIFrame);
        t.Actions[5].Kind.Should().Be(ActionKind.Processing);
        t.Actions[6].Verb.Should().Be(Ax25ActionVerb.DLDATAIndication);
        t.Actions[6].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[7].Verb.Should().Be(Ax25ActionVerb.VRAssignVR1);
        t.Actions[7].Kind.Should().Be(ActionKind.Processing);
        t.Actions[8].Verb.Should().Be(Ax25ActionVerb.SetAcknowledgePending);
        t.Actions[8].Kind.Should().Be(ActionKind.Processing);
        t.Actions[9].Verb.Should().Be(Ax25ActionVerb.LMSeizeRequest);
        t.Actions[9].Kind.Should().Be(ActionKind.SignalLower);
    }

    [Fact] public void t22_i_received_yes_yes_yes_no_yes_no_yes()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t22_i_received_yes_yes_yes_no_yes_no_yes");
        t.On.Should().Be(Ax25Event.IReceived);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.Command, false), new GuardTerm(Ax25Guard.InfoFieldLengthLeN1AndContentIsOctetAligned, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, false), new GuardTerm(Ax25Guard.OwnReceiverBusy, true), new GuardTerm(Ax25Guard.NsEqVr, false), new GuardTerm(Ax25Guard.PEq1, true), new GuardTerm(Ax25Guard.AckPending, false) });
        t.Actions.Count.Should().Be(8);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.CheckIFrameAcknowledged);
        t.Actions[0].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.VRAssignVRPlus1);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.ClearRejectException);
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.DecrementSrejectExceptionIf0);
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be(Ax25ActionVerb.DLDATAIndication);
        t.Actions[4].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[5].Verb.Should().Be(Ax25ActionVerb.RetrieveStoredVRIFrame);
        t.Actions[5].Kind.Should().Be(ActionKind.Processing);
        t.Actions[6].Verb.Should().Be(Ax25ActionVerb.DLDATAIndication);
        t.Actions[6].Kind.Should().Be(ActionKind.SignalUpper);
        t.Actions[7].Verb.Should().Be(Ax25ActionVerb.VRAssignVR1);
        t.Actions[7].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t22_i_received_yes_yes_yes_no_no_yes_yes_yes()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t22_i_received_yes_yes_yes_no_no_yes_yes_yes");
        t.On.Should().Be(Ax25Event.IReceived);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.Command, false), new GuardTerm(Ax25Guard.InfoFieldLengthLeN1AndContentIsOctetAligned, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, false), new GuardTerm(Ax25Guard.OwnReceiverBusy, true), new GuardTerm(Ax25Guard.NsEqVr, true), new GuardTerm(Ax25Guard.VrLtNsLtVrPlusK, false), new GuardTerm(Ax25Guard.RejectException, false), new GuardTerm(Ax25Guard.PEq1, false) });
        t.Actions.Count.Should().Be(6);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.CheckIFrameAcknowledged);
        t.Actions[0].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.DiscardContentsOfIFrame);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.FAssign1);
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.NRAssignVR);
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be(Ax25ActionVerb.RR);
        t.Actions[4].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[5].Verb.Should().Be(Ax25ActionVerb.ClearAcknowledgePending);
        t.Actions[5].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t22_i_received_yes_yes_yes_no_no_yes_yes_no()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t22_i_received_yes_yes_yes_no_no_yes_yes_no");
        t.On.Should().Be(Ax25Event.IReceived);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.Command, false), new GuardTerm(Ax25Guard.InfoFieldLengthLeN1AndContentIsOctetAligned, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, false), new GuardTerm(Ax25Guard.OwnReceiverBusy, true), new GuardTerm(Ax25Guard.NsEqVr, true), new GuardTerm(Ax25Guard.VrLtNsLtVrPlusK, false), new GuardTerm(Ax25Guard.RejectException, false), new GuardTerm(Ax25Guard.PEq1, true) });
        t.Actions.Count.Should().Be(2);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.CheckIFrameAcknowledged);
        t.Actions[0].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.DiscardContentsOfIFrame);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t22_i_received_yes_yes_yes_no_no_yes_no_no()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t22_i_received_yes_yes_yes_no_no_yes_no_no");
        t.On.Should().Be(Ax25Event.IReceived);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.Command, false), new GuardTerm(Ax25Guard.InfoFieldLengthLeN1AndContentIsOctetAligned, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, false), new GuardTerm(Ax25Guard.OwnReceiverBusy, true), new GuardTerm(Ax25Guard.NsEqVr, true), new GuardTerm(Ax25Guard.VrLtNsLtVrPlusK, false), new GuardTerm(Ax25Guard.RejectException, true), new GuardTerm(Ax25Guard.SREJEnabled, true) });
        t.Actions.Count.Should().Be(7);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.CheckIFrameAcknowledged);
        t.Actions[0].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.DiscardContentsOfIFrame);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.SetRejectException);
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.FAssignP);
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be(Ax25ActionVerb.NRAssignVR);
        t.Actions[4].Kind.Should().Be(ActionKind.Processing);
        t.Actions[5].Verb.Should().Be(Ax25ActionVerb.REJ);
        t.Actions[5].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[6].Verb.Should().Be(Ax25ActionVerb.SetAcknowledgePending);
        t.Actions[6].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t22_i_received_yes_yes_yes_no_no_yes_no_yes_no_yes()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t22_i_received_yes_yes_yes_no_no_yes_no_yes_no_yes");
        t.On.Should().Be(Ax25Event.IReceived);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.Command, false), new GuardTerm(Ax25Guard.InfoFieldLengthLeN1AndContentIsOctetAligned, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, false), new GuardTerm(Ax25Guard.OwnReceiverBusy, true), new GuardTerm(Ax25Guard.NsEqVr, true), new GuardTerm(Ax25Guard.VrLtNsLtVrPlusK, false), new GuardTerm(Ax25Guard.RejectException, true), new GuardTerm(Ax25Guard.SREJEnabled, false), new GuardTerm(Ax25Guard.SrejectExceptionGt0, true), new GuardTerm(Ax25Guard.NsGtVrPlus1, false) });
        t.Actions.Count.Should().Be(8);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.CheckIFrameAcknowledged);
        t.Actions[0].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.SaveContentsOfIFrame);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.DiscardContentsOfIFrame);
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.SetRejectException);
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be(Ax25ActionVerb.FAssignP);
        t.Actions[4].Kind.Should().Be(ActionKind.Processing);
        t.Actions[5].Verb.Should().Be(Ax25ActionVerb.NRAssignVR);
        t.Actions[5].Kind.Should().Be(ActionKind.Processing);
        t.Actions[6].Verb.Should().Be(Ax25ActionVerb.REJ);
        t.Actions[6].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[7].Verb.Should().Be(Ax25ActionVerb.SetAcknowledgePending);
        t.Actions[7].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t22_i_received_yes_yes_yes_no_no_yes_no_yes_no_no()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t22_i_received_yes_yes_yes_no_no_yes_no_yes_no_no");
        t.On.Should().Be(Ax25Event.IReceived);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.Command, false), new GuardTerm(Ax25Guard.InfoFieldLengthLeN1AndContentIsOctetAligned, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, false), new GuardTerm(Ax25Guard.OwnReceiverBusy, true), new GuardTerm(Ax25Guard.NsEqVr, true), new GuardTerm(Ax25Guard.VrLtNsLtVrPlusK, false), new GuardTerm(Ax25Guard.RejectException, true), new GuardTerm(Ax25Guard.SREJEnabled, false), new GuardTerm(Ax25Guard.SrejectExceptionGt0, true), new GuardTerm(Ax25Guard.NsGtVrPlus1, true) });
        t.Actions.Count.Should().Be(6);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.CheckIFrameAcknowledged);
        t.Actions[0].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.SaveContentsOfIFrame);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.NRAssignVR);
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.FAssign1);
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be(Ax25ActionVerb.SrejectAssignSrejectPlus1);
        t.Actions[4].Kind.Should().Be(ActionKind.Processing);
        t.Actions[5].Verb.Should().Be(Ax25ActionVerb.SREJ);
        t.Actions[5].Kind.Should().Be(ActionKind.SignalLower);
    }

    [Fact] public void t22_i_received_yes_yes_yes_no_no_yes_no_yes_yes()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t22_i_received_yes_yes_yes_no_no_yes_no_yes_yes");
        t.On.Should().Be(Ax25Event.IReceived);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.Command, false), new GuardTerm(Ax25Guard.InfoFieldLengthLeN1AndContentIsOctetAligned, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, false), new GuardTerm(Ax25Guard.OwnReceiverBusy, true), new GuardTerm(Ax25Guard.NsEqVr, true), new GuardTerm(Ax25Guard.VrLtNsLtVrPlusK, false), new GuardTerm(Ax25Guard.RejectException, true), new GuardTerm(Ax25Guard.SREJEnabled, false), new GuardTerm(Ax25Guard.SrejectExceptionGt0, false) });
        t.Actions.Count.Should().Be(6);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.CheckIFrameAcknowledged);
        t.Actions[0].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.SaveContentsOfIFrame);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.NRAssignVR);
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.FAssign0);
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be(Ax25ActionVerb.SrejectAssignSrejectPlus1);
        t.Actions[4].Kind.Should().Be(ActionKind.Processing);
        t.Actions[5].Verb.Should().Be(Ax25ActionVerb.SREJ);
        t.Actions[5].Kind.Should().Be(ActionKind.SignalLower);
    }

    [Fact] public void t22_i_received_yes_yes_yes_no_no_no_yes()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t22_i_received_yes_yes_yes_no_no_no_yes");
        t.On.Should().Be(Ax25Event.IReceived);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.Command, false), new GuardTerm(Ax25Guard.InfoFieldLengthLeN1AndContentIsOctetAligned, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, false), new GuardTerm(Ax25Guard.OwnReceiverBusy, true), new GuardTerm(Ax25Guard.NsEqVr, true), new GuardTerm(Ax25Guard.VrLtNsLtVrPlusK, true), new GuardTerm(Ax25Guard.PEq1, false) });
        t.Actions.Count.Should().Be(6);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.CheckIFrameAcknowledged);
        t.Actions[0].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.DiscardContentsOfIFrame);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.FAssign1);
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.NRAssignVR);
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be(Ax25ActionVerb.RR);
        t.Actions[4].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[5].Verb.Should().Be(Ax25ActionVerb.ClearAcknowledgePending);
        t.Actions[5].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t22_i_received_yes_yes_yes_no_no_no_no()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t22_i_received_yes_yes_yes_no_no_no_no");
        t.On.Should().Be(Ax25Event.IReceived);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.Command, false), new GuardTerm(Ax25Guard.InfoFieldLengthLeN1AndContentIsOctetAligned, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, false), new GuardTerm(Ax25Guard.OwnReceiverBusy, true), new GuardTerm(Ax25Guard.NsEqVr, true), new GuardTerm(Ax25Guard.VrLtNsLtVrPlusK, true), new GuardTerm(Ax25Guard.PEq1, true) });
        t.Actions.Count.Should().Be(2);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.CheckIFrameAcknowledged);
        t.Actions[0].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.DiscardContentsOfIFrame);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t23_rej_received_no_yes_yes_yes()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t23_rej_received_no_yes_yes_yes");
        t.On.Should().Be(Ax25Event.REJReceived);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.ResponseAndFEq1, true), new GuardTerm(Ax25Guard.CommandAndPEq1, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, false), new GuardTerm(Ax25Guard.VsEqNr, false) });
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.ClearPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.EnquiryResponseF1);
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.VAAssignNR);
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t23_rej_received_no_yes_yes_no()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t23_rej_received_no_yes_yes_no");
        t.On.Should().Be(Ax25Event.REJReceived);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.ResponseAndFEq1, true), new GuardTerm(Ax25Guard.CommandAndPEq1, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, false), new GuardTerm(Ax25Guard.VsEqNr, true) });
        t.Actions.Count.Should().Be(7);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.ClearPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.EnquiryResponseF1);
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.VAAssignNR);
        t.Actions[2].Kind.Should().Be(ActionKind.Processing);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.InvokeRetransmission);
        t.Actions[3].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[4].Verb.Should().Be(Ax25ActionVerb.StopT3);
        t.Actions[4].Kind.Should().Be(ActionKind.Processing);
        t.Actions[5].Verb.Should().Be(Ax25ActionVerb.StartT1);
        t.Actions[5].Kind.Should().Be(ActionKind.Processing);
        t.Actions[6].Verb.Should().Be(Ax25ActionVerb.ClearAcknowledgePending);
        t.Actions[6].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t23_rej_received_no_yes_no_yes()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t23_rej_received_no_yes_no_yes");
        t.On.Should().Be(Ax25Event.REJReceived);
        t.Next.Should().Be("AwaitingV22Connection");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.ResponseAndFEq1, true), new GuardTerm(Ax25Guard.CommandAndPEq1, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, true), new GuardTerm(Ax25Guard.Version22, false) });
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.ClearPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.EnquiryResponseF1);
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.NRRecovery);
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t23_rej_received_no_yes_no_no()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t23_rej_received_no_yes_no_no");
        t.On.Should().Be(Ax25Event.REJReceived);
        t.Next.Should().Be("AwaitingConnection");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.ResponseAndFEq1, true), new GuardTerm(Ax25Guard.CommandAndPEq1, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, true), new GuardTerm(Ax25Guard.Version22, true) });
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.ClearPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.EnquiryResponseF1);
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.NRRecovery);
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t23_rej_received_no_no_yes_yes()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t23_rej_received_no_no_yes_yes");
        t.On.Should().Be(Ax25Event.REJReceived);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.ResponseAndFEq1, true), new GuardTerm(Ax25Guard.CommandAndPEq1, true), new GuardTerm(Ax25Guard.VaLeNrLeVs, false), new GuardTerm(Ax25Guard.VsEqNr, false) });
        t.Actions.Count.Should().Be(2);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.ClearPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.VAAssignNR);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t23_rej_received_no_no_yes_no()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t23_rej_received_no_no_yes_no");
        t.On.Should().Be(Ax25Event.REJReceived);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.ResponseAndFEq1, true), new GuardTerm(Ax25Guard.CommandAndPEq1, true), new GuardTerm(Ax25Guard.VaLeNrLeVs, false), new GuardTerm(Ax25Guard.VsEqNr, true) });
        t.Actions.Count.Should().Be(6);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.ClearPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.VAAssignNR);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.InvokeRetransmission);
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.StopT3);
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be(Ax25ActionVerb.StartT1);
        t.Actions[4].Kind.Should().Be(ActionKind.Processing);
        t.Actions[5].Verb.Should().Be(Ax25ActionVerb.ClearAcknowledgePending);
        t.Actions[5].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t23_rej_received_no_no_no_yes()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t23_rej_received_no_no_no_yes");
        t.On.Should().Be(Ax25Event.REJReceived);
        t.Next.Should().Be("AwaitingV22Connection");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.ResponseAndFEq1, true), new GuardTerm(Ax25Guard.CommandAndPEq1, true), new GuardTerm(Ax25Guard.VaLeNrLeVs, true), new GuardTerm(Ax25Guard.Version22, false) });
        t.Actions.Count.Should().Be(2);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.ClearPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.NRRecovery);
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t23_rej_received_no_no_no_no()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t23_rej_received_no_no_no_no");
        t.On.Should().Be(Ax25Event.REJReceived);
        t.Next.Should().Be("AwaitingConnection");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.ResponseAndFEq1, true), new GuardTerm(Ax25Guard.CommandAndPEq1, true), new GuardTerm(Ax25Guard.VaLeNrLeVs, true), new GuardTerm(Ax25Guard.Version22, true) });
        t.Actions.Count.Should().Be(2);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.ClearPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.NRRecovery);
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t23_rej_received_yes_no_yes()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t23_rej_received_yes_no_yes");
        t.On.Should().Be(Ax25Event.REJReceived);
        t.Next.Should().Be("AwaitingV22Connection");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.ResponseAndFEq1, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, true), new GuardTerm(Ax25Guard.Version22, false) });
        t.Actions.Count.Should().Be(4);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.ClearPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.StopT1);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.SelectT1Value);
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.NRRecovery);
        t.Actions[3].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t23_rej_received_yes_no_no()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t23_rej_received_yes_no_no");
        t.On.Should().Be(Ax25Event.REJReceived);
        t.Next.Should().Be("AwaitingConnection");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.ResponseAndFEq1, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, true), new GuardTerm(Ax25Guard.Version22, true) });
        t.Actions.Count.Should().Be(4);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.ClearPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.StopT1);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.SelectT1Value);
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.NRRecovery);
        t.Actions[3].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t23_rej_received_yes_yes_yes()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t23_rej_received_yes_yes_yes");
        t.On.Should().Be(Ax25Event.REJReceived);
        t.Next.Should().Be("Connected");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.ResponseAndFEq1, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, false), new GuardTerm(Ax25Guard.VsEqNr, false) });
        t.Actions.Count.Should().Be(6);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.ClearPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.StopT1);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.SelectT1Value);
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.VAAssignNR);
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be(Ax25ActionVerb.StartT3);
        t.Actions[4].Kind.Should().Be(ActionKind.Processing);
        t.Actions[5].Verb.Should().Be(Ax25ActionVerb.RCAssign0);
        t.Actions[5].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t23_rej_received_yes_yes_no()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t23_rej_received_yes_yes_no");
        t.On.Should().Be(Ax25Event.REJReceived);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.ResponseAndFEq1, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, false), new GuardTerm(Ax25Guard.VsEqNr, true) });
        t.Actions.Count.Should().Be(8);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.ClearPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.StopT1);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.SelectT1Value);
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.VAAssignNR);
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be(Ax25ActionVerb.InvokeRetransmission);
        t.Actions[4].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[5].Verb.Should().Be(Ax25ActionVerb.StopT3);
        t.Actions[5].Kind.Should().Be(ActionKind.Processing);
        t.Actions[6].Verb.Should().Be(Ax25ActionVerb.StartT1);
        t.Actions[6].Kind.Should().Be(ActionKind.Processing);
        t.Actions[7].Verb.Should().Be(Ax25ActionVerb.ClearAcknowledgePending);
        t.Actions[7].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t24_srej_received_no_yes_yes_yes()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t24_srej_received_no_yes_yes_yes");
        t.On.Should().Be(Ax25Event.SREJReceived);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.Response, true), new GuardTerm(Ax25Guard.VaLeNrLeVs, false), new GuardTerm(Ax25Guard.PEq1, false), new GuardTerm(Ax25Guard.VsEqNr, false) });
        t.Actions.Count.Should().Be(3);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.ClearPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.VAAssignNR);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.CheckIFrameAcknowledged);
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t24_srej_received_no_yes_yes_no()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t24_srej_received_no_yes_yes_no");
        t.On.Should().Be(Ax25Event.SREJReceived);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.Response, true), new GuardTerm(Ax25Guard.VaLeNrLeVs, false), new GuardTerm(Ax25Guard.PEq1, false), new GuardTerm(Ax25Guard.VsEqNr, true) });
        t.Actions.Count.Should().Be(8);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.ClearPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.VAAssignNR);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.CheckIFrameAcknowledged);
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.PushOldIFrameNROnQueue);
        t.Actions[3].Kind.Should().Be(ActionKind.InternalOut);
        t.Actions[4].Verb.Should().Be(Ax25ActionVerb.LMDataRequest);
        t.Actions[4].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[5].Verb.Should().Be(Ax25ActionVerb.StopT3);
        t.Actions[5].Kind.Should().Be(ActionKind.Processing);
        t.Actions[6].Verb.Should().Be(Ax25ActionVerb.StartT1);
        t.Actions[6].Kind.Should().Be(ActionKind.Processing);
        t.Actions[7].Verb.Should().Be(Ax25ActionVerb.ClearAcknowledgePending);
        t.Actions[7].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t24_srej_received_no_yes_no_yes()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t24_srej_received_no_yes_no_yes");
        t.On.Should().Be(Ax25Event.SREJReceived);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.Response, true), new GuardTerm(Ax25Guard.VaLeNrLeVs, false), new GuardTerm(Ax25Guard.PEq1, true), new GuardTerm(Ax25Guard.VsEqVa, false) });
        t.Actions.Count.Should().Be(1);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.ClearPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t24_srej_received_no_yes_no_no()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t24_srej_received_no_yes_no_no");
        t.On.Should().Be(Ax25Event.SREJReceived);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.Response, true), new GuardTerm(Ax25Guard.VaLeNrLeVs, false), new GuardTerm(Ax25Guard.PEq1, true), new GuardTerm(Ax25Guard.VsEqVa, true) });
        t.Actions.Count.Should().Be(6);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.ClearPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.PushOldIFrameNROnQueue);
        t.Actions[1].Kind.Should().Be(ActionKind.InternalOut);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.LMDataRequest);
        t.Actions[2].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.StopT3);
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be(Ax25ActionVerb.StartT1);
        t.Actions[4].Kind.Should().Be(ActionKind.Processing);
        t.Actions[5].Verb.Should().Be(Ax25ActionVerb.ClearAcknowledgePending);
        t.Actions[5].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t24_srej_received_no_no_no()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t24_srej_received_no_no_no");
        t.On.Should().Be(Ax25Event.SREJReceived);
        t.Next.Should().Be("AwaitingConnection");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.Response, true), new GuardTerm(Ax25Guard.VaLeNrLeVs, true), new GuardTerm(Ax25Guard.Version22, true) });
        t.Actions.Count.Should().Be(2);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.ClearPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.NRRecovery);
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t24_srej_received_no_no_yes()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t24_srej_received_no_no_yes");
        t.On.Should().Be(Ax25Event.SREJReceived);
        t.Next.Should().Be("AwaitingV22Connection");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.Response, true), new GuardTerm(Ax25Guard.VaLeNrLeVs, true), new GuardTerm(Ax25Guard.Version22, false) });
        t.Actions.Count.Should().Be(2);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.ClearPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.NRRecovery);
        t.Actions[1].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t24_srej_received_yes_no_no()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t24_srej_received_yes_no_no");
        t.On.Should().Be(Ax25Event.SREJReceived);
        t.Next.Should().Be("AwaitingConnection");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.Response, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, true), new GuardTerm(Ax25Guard.Version22, true) });
        t.Actions.Count.Should().Be(4);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.ClearPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.StopT1);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.SelectT1Value);
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.NRRecovery);
        t.Actions[3].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t24_srej_received_yes_no_yes()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t24_srej_received_yes_no_yes");
        t.On.Should().Be(Ax25Event.SREJReceived);
        t.Next.Should().Be("AwaitingV22Connection");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.Response, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, true), new GuardTerm(Ax25Guard.Version22, false) });
        t.Actions.Count.Should().Be(4);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.ClearPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.StopT1);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.SelectT1Value);
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.NRRecovery);
        t.Actions[3].Kind.Should().Be(ActionKind.Subroutine);
    }

    [Fact] public void t24_srej_received_yes_yes_yes_yes()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t24_srej_received_yes_yes_yes_yes");
        t.On.Should().Be(Ax25Event.SREJReceived);
        t.Next.Should().Be("Connected");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.Response, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, false), new GuardTerm(Ax25Guard.FEq1, false), new GuardTerm(Ax25Guard.VsEqNr, false) });
        t.Actions.Count.Should().Be(7);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.ClearPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.StopT1);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.SelectT1Value);
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.VAAssignNR);
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be(Ax25ActionVerb.CheckIFrameAcknowledged);
        t.Actions[4].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[5].Verb.Should().Be(Ax25ActionVerb.StartT3);
        t.Actions[5].Kind.Should().Be(ActionKind.Processing);
        t.Actions[6].Verb.Should().Be(Ax25ActionVerb.RCAssign0);
        t.Actions[6].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t24_srej_received_yes_yes_yes_no()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t24_srej_received_yes_yes_yes_no");
        t.On.Should().Be(Ax25Event.SREJReceived);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.Response, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, false), new GuardTerm(Ax25Guard.FEq1, false), new GuardTerm(Ax25Guard.VsEqNr, true) });
        t.Actions.Count.Should().Be(10);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.ClearPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.StopT1);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.SelectT1Value);
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.VAAssignNR);
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be(Ax25ActionVerb.CheckIFrameAcknowledged);
        t.Actions[4].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[5].Verb.Should().Be(Ax25ActionVerb.PushOldIFrameNROnQueue);
        t.Actions[5].Kind.Should().Be(ActionKind.InternalOut);
        t.Actions[6].Verb.Should().Be(Ax25ActionVerb.LMDataRequest);
        t.Actions[6].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[7].Verb.Should().Be(Ax25ActionVerb.StopT3);
        t.Actions[7].Kind.Should().Be(ActionKind.Processing);
        t.Actions[8].Verb.Should().Be(Ax25ActionVerb.StartT1);
        t.Actions[8].Kind.Should().Be(ActionKind.Processing);
        t.Actions[9].Verb.Should().Be(Ax25ActionVerb.ClearAcknowledgePending);
        t.Actions[9].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t24_srej_received_yes_yes_no_yes()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t24_srej_received_yes_yes_no_yes");
        t.On.Should().Be(Ax25Event.SREJReceived);
        t.Next.Should().Be("Connected");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.Response, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, false), new GuardTerm(Ax25Guard.FEq1, true), new GuardTerm(Ax25Guard.VsEqVa, false) });
        t.Actions.Count.Should().Be(5);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.ClearPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.StopT1);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.SelectT1Value);
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.StartT3);
        t.Actions[3].Kind.Should().Be(ActionKind.Processing);
        t.Actions[4].Verb.Should().Be(Ax25ActionVerb.RCAssign0);
        t.Actions[4].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t24_srej_received_yes_yes_no_no()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t24_srej_received_yes_yes_no_no");
        t.On.Should().Be(Ax25Event.SREJReceived);
        t.Next.Should().Be("TimerRecovery");
        t.Guard.Should().Equal(new GuardTerm[] { new GuardTerm(Ax25Guard.Response, false), new GuardTerm(Ax25Guard.VaLeNrLeVs, false), new GuardTerm(Ax25Guard.FEq1, true), new GuardTerm(Ax25Guard.VsEqVa, true) });
        t.Actions.Count.Should().Be(8);
        t.Actions[0].Verb.Should().Be(Ax25ActionVerb.ClearPeerReceiverBusy);
        t.Actions[0].Kind.Should().Be(ActionKind.Processing);
        t.Actions[1].Verb.Should().Be(Ax25ActionVerb.StopT1);
        t.Actions[1].Kind.Should().Be(ActionKind.Processing);
        t.Actions[2].Verb.Should().Be(Ax25ActionVerb.SelectT1Value);
        t.Actions[2].Kind.Should().Be(ActionKind.Subroutine);
        t.Actions[3].Verb.Should().Be(Ax25ActionVerb.PushOldIFrameNROnQueue);
        t.Actions[3].Kind.Should().Be(ActionKind.InternalOut);
        t.Actions[4].Verb.Should().Be(Ax25ActionVerb.LMDataRequest);
        t.Actions[4].Kind.Should().Be(ActionKind.SignalLower);
        t.Actions[5].Verb.Should().Be(Ax25ActionVerb.StopT3);
        t.Actions[5].Kind.Should().Be(ActionKind.Processing);
        t.Actions[6].Verb.Should().Be(Ax25ActionVerb.StartT1);
        t.Actions[6].Kind.Should().Be(ActionKind.Processing);
        t.Actions[7].Verb.Should().Be(Ax25ActionVerb.ClearAcknowledgePending);
        t.Actions[7].Kind.Should().Be(ActionKind.Processing);
    }

    [Fact] public void t25_all_other_primitives__from_lower_layer()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t25_all_other_primitives__from_lower_layer");
        t.On.Should().Be(Ax25Event.AllOtherPrimitivesFromLowerLayer);
        t.Next.Should().Be("TimerRecovery");
        t.Actions.Count.Should().Be(0);
    }

    [Fact] public void t26_all_other_primitives__from_upper_layer()
    {
        var t = DataLink_TimerRecovery.Transitions.Single(x => x.Id == "t26_all_other_primitives__from_upper_layer");
        t.On.Should().Be(Ax25Event.AllOtherPrimitivesFromUpperLayer);
        t.Next.Should().Be("TimerRecovery");
        t.Actions.Count.Should().Be(0);
    }

}
