// Code generated by codegen/src/Packet.Sdl.CodeGen. DO NOT EDIT.
// The closed set of AX.25 SDL events — see spec-sdl/events.yaml.
// AX25_EVENTS is the runtime enumeration; Ax25Event is derived from it, so the
// value and the type cannot drift apart.

export const AX25_EVENTS = [
  "DISC_received",
  "DL_CONNECT_request",
  "DL_DATA_request",
  "DL_DISCONNECT_request",
  "DL_FLOW_OFF_request",
  "DL_FLOW_ON_request",
  "DL_UNIT_DATA_request",
  "DM_received",
  "FRMR_received",
  "I_frame_pops_off_queue",
  "I_received",
  "LM_SEIZE_confirm",
  "MDL_ERROR_indicate",
  "MDL_NEGOTIATE_confirm",
  "MDL_NEGOTIATE_request",
  "REJ_received",
  "RNR_received",
  "RR_received",
  "SABME_received",
  "SABM_received",
  "SREJ_received",
  "T1_expiry",
  "T2_expiry",
  "T3_expiry",
  "TEST_received",
  "TM201_expiry",
  "UA_received",
  "UI_received",
  "XID_received",
  "XID_response_received",
  "all_other_commands",
  "all_other_primitives__from_lower_layer",
  "all_other_primitives__from_upper_layer",
  "control_field_error",
  "i_or_s_command_received",
  "info_field_permitted_in_frame",
  "info_not_permitted_in_frame",
  "u_or_s_frame_length_error",
] as const;

export type Ax25Event = (typeof AX25_EVENTS)[number];
