// Code generated by codegen/src/Packet.Sdl.CodeGen from spec-sdl/v2.2-errata/data-link/yaml/connected.sdl.yaml.
// DO NOT EDIT. Run `dotnet run --project codegen/src/Packet.Sdl.CodeGen` to regenerate.

import { describe, it, expect } from "vitest";
import { DataLinkConnected } from "./connected.g.js";

describe("DataLinkConnected", () => {
  it("source figure", () => {
    expect(DataLinkConnected.source.figure).toBe("figc4.4");
  });

  it("transitions are present", () => {
    expect(DataLinkConnected.transitions).toHaveLength(68);
  });

  it("t01_dl_disconnect_request", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t01_dl_disconnect_request");
    expect(t, "transition t01_dl_disconnect_request not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("DL_DISCONNECT_request");
    expect(t.next).toBe("AwaitingRelease");
    expect(t.actions).toHaveLength(5);
    expect(t.actions[0].verb).toBe("discard_I_frame_queue");
    expect(t.actions[0].kind).toBe("processing");
    expect(t.actions[1].verb).toBe("RC := 0");
    expect(t.actions[1].kind).toBe("processing");
    expect(t.actions[2].verb).toBe("DISC (P = 1)");
    expect(t.actions[2].kind).toBe("signal_lower");
    expect(t.actions[3].verb).toBe("Stop T3");
    expect(t.actions[3].kind).toBe("processing");
    expect(t.actions[4].verb).toBe("Start T1");
    expect(t.actions[4].kind).toBe("processing");
  });

  it("t02_dl_data_request", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t02_dl_data_request");
    expect(t, "transition t02_dl_data_request not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("DL_DATA_request");
    expect(t.next).toBe("Connected");
    expect(t.actions).toHaveLength(1);
    expect(t.actions[0].verb).toBe("Push on I Frame Queue (note: word order?)");
    expect(t.actions[0].kind).toBe("internal_out");
  });

  it("t03_i_frame_pops_off_queue_yes", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t03_i_frame_pops_off_queue_yes");
    expect(t, "transition t03_i_frame_pops_off_queue_yes not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("I_frame_pops_off_queue");
    expect(t.next).toBe("Connected");
    expect(t.guard).toEqual([{ atom: "peer_receiver_busy", negate: false }]);
    expect(t.actions).toHaveLength(1);
    expect(t.actions[0].verb).toBe("Push on I Frame Queue");
    expect(t.actions[0].kind).toBe("internal_out");
  });

  it("t03_i_frame_pops_off_queue_no_yes", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t03_i_frame_pops_off_queue_no_yes");
    expect(t, "transition t03_i_frame_pops_off_queue_no_yes not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("I_frame_pops_off_queue");
    expect(t.next).toBe("Connected");
    expect(t.guard).toEqual([{ atom: "peer_receiver_busy", negate: true }, { atom: "vs_eq_va_plus_k", negate: false }]);
    expect(t.actions).toHaveLength(1);
    expect(t.actions[0].verb).toBe("Push on I Frame Queue");
    expect(t.actions[0].kind).toBe("internal_out");
  });

  it("t03_i_frame_pops_off_queue_no_no_no", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t03_i_frame_pops_off_queue_no_no_no");
    expect(t, "transition t03_i_frame_pops_off_queue_no_no_no not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("I_frame_pops_off_queue");
    expect(t.next).toBe("Connected");
    expect(t.guard).toEqual([{ atom: "peer_receiver_busy", negate: true }, { atom: "vs_eq_va_plus_k", negate: true }, { atom: "T1_running", negate: true }]);
    expect(t.actions).toHaveLength(8);
    expect(t.actions[0].verb).toBe("N(s) := V(s)");
    expect(t.actions[0].kind).toBe("processing");
    expect(t.actions[1].verb).toBe("N(r) := V(r)");
    expect(t.actions[1].kind).toBe("processing");
    expect(t.actions[2].verb).toBe("P := 0");
    expect(t.actions[2].kind).toBe("processing");
    expect(t.actions[3].verb).toBe("I Command");
    expect(t.actions[3].kind).toBe("signal_lower");
    expect(t.actions[4].verb).toBe("V(s) := V(s) + 1");
    expect(t.actions[4].kind).toBe("processing");
    expect(t.actions[5].verb).toBe("Clear Acknowledge Pending");
    expect(t.actions[5].kind).toBe("processing");
    expect(t.actions[6].verb).toBe("Stop T3");
    expect(t.actions[6].kind).toBe("processing");
    expect(t.actions[7].verb).toBe("Start T1");
    expect(t.actions[7].kind).toBe("processing");
  });

  it("t03_i_frame_pops_off_queue_no_no_yes", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t03_i_frame_pops_off_queue_no_no_yes");
    expect(t, "transition t03_i_frame_pops_off_queue_no_no_yes not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("I_frame_pops_off_queue");
    expect(t.next).toBe("Connected");
    expect(t.guard).toEqual([{ atom: "peer_receiver_busy", negate: true }, { atom: "vs_eq_va_plus_k", negate: true }, { atom: "T1_running", negate: false }]);
    expect(t.actions).toHaveLength(6);
    expect(t.actions[0].verb).toBe("N(s) := V(s)");
    expect(t.actions[0].kind).toBe("processing");
    expect(t.actions[1].verb).toBe("N(r) := V(r)");
    expect(t.actions[1].kind).toBe("processing");
    expect(t.actions[2].verb).toBe("P := 0");
    expect(t.actions[2].kind).toBe("processing");
    expect(t.actions[3].verb).toBe("I Command");
    expect(t.actions[3].kind).toBe("signal_lower");
    expect(t.actions[4].verb).toBe("V(s) := V(s) + 1");
    expect(t.actions[4].kind).toBe("processing");
    expect(t.actions[5].verb).toBe("Clear Acknowledge Pending");
    expect(t.actions[5].kind).toBe("processing");
  });

  it("t04_dl_unit_data_request", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t04_dl_unit_data_request");
    expect(t, "transition t04_dl_unit_data_request not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("DL_UNIT_DATA_request");
    expect(t.next).toBe("Connected");
    expect(t.actions).toHaveLength(1);
    expect(t.actions[0].verb).toBe("UI Command");
    expect(t.actions[0].kind).toBe("signal_lower");
  });

  it("t05_dl_flow_off_request_yes", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t05_dl_flow_off_request_yes");
    expect(t, "transition t05_dl_flow_off_request_yes not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("DL_FLOW_OFF_request");
    expect(t.next).toBe("Connected");
    expect(t.guard).toEqual([{ atom: "own_receiver_busy", negate: false }]);
    expect(t.actions).toHaveLength(3);
    expect(t.actions[0].verb).toBe("Set Own Receiver Busy");
    expect(t.actions[0].kind).toBe("processing");
    expect(t.actions[1].verb).toBe("RNR Response");
    expect(t.actions[1].kind).toBe("signal_lower");
    expect(t.actions[2].verb).toBe("Clear Acknowledge Pending");
    expect(t.actions[2].kind).toBe("processing");
  });

  it("t05_dl_flow_off_request_no", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t05_dl_flow_off_request_no");
    expect(t, "transition t05_dl_flow_off_request_no not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("DL_FLOW_OFF_request");
    expect(t.next).toBe("Connected");
    expect(t.guard).toEqual([{ atom: "own_receiver_busy", negate: true }]);
    expect(t.actions).toHaveLength(0);
  });

  it("t06_dl_flow_on_request_no", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t06_dl_flow_on_request_no");
    expect(t, "transition t06_dl_flow_on_request_no not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("DL_FLOW_ON_request");
    expect(t.next).toBe("Connected");
    expect(t.guard).toEqual([{ atom: "own_receiver_busy", negate: true }]);
    expect(t.actions).toHaveLength(0);
  });

  it("t06_dl_flow_on_request_yes_yes", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t06_dl_flow_on_request_yes_yes");
    expect(t, "transition t06_dl_flow_on_request_yes_yes not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("DL_FLOW_ON_request");
    expect(t.next).toBe("Connected");
    expect(t.guard).toEqual([{ atom: "own_receiver_busy", negate: false }, { atom: "T1_running", negate: false }]);
    expect(t.actions).toHaveLength(3);
    expect(t.actions[0].verb).toBe("Clear Own Receiver Busy");
    expect(t.actions[0].kind).toBe("processing");
    expect(t.actions[1].verb).toBe("RR Command");
    expect(t.actions[1].kind).toBe("signal_lower");
    expect(t.actions[2].verb).toBe("Clear Acknowledge Pending");
    expect(t.actions[2].kind).toBe("processing");
  });

  it("t06_dl_flow_on_request_yes_no", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t06_dl_flow_on_request_yes_no");
    expect(t, "transition t06_dl_flow_on_request_yes_no not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("DL_FLOW_ON_request");
    expect(t.next).toBe("Connected");
    expect(t.guard).toEqual([{ atom: "own_receiver_busy", negate: false }, { atom: "T1_running", negate: true }]);
    expect(t.actions).toHaveLength(5);
    expect(t.actions[0].verb).toBe("Clear Own Receiver Busy");
    expect(t.actions[0].kind).toBe("processing");
    expect(t.actions[1].verb).toBe("RR Command");
    expect(t.actions[1].kind).toBe("signal_lower");
    expect(t.actions[2].verb).toBe("Clear Acknowledge Pending");
    expect(t.actions[2].kind).toBe("processing");
    expect(t.actions[3].verb).toBe("Stop T3");
    expect(t.actions[3].kind).toBe("processing");
    expect(t.actions[4].verb).toBe("Start T1");
    expect(t.actions[4].kind).toBe("processing");
  });

  it("t07_dl_connect_request_no", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t07_dl_connect_request_no");
    expect(t, "transition t07_dl_connect_request_no not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("DL_CONNECT_request");
    expect(t.next).toBe("AwaitingConnection");
    expect(t.guard).toEqual([{ atom: "version_2_2", negate: true }]);
    expect(t.actions).toHaveLength(3);
    expect(t.actions[0].verb).toBe("discard_I_frame_queue");
    expect(t.actions[0].kind).toBe("processing");
    expect(t.actions[1].verb).toBe("Establish_Data_Link");
    expect(t.actions[1].kind).toBe("subroutine");
    expect(t.actions[2].verb).toBe("Set Layer 3 Initiated");
    expect(t.actions[2].kind).toBe("processing");
  });

  it("t07_dl_connect_request_yes", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t07_dl_connect_request_yes");
    expect(t, "transition t07_dl_connect_request_yes not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("DL_CONNECT_request");
    expect(t.next).toBe("AwaitingV22Connection");
    expect(t.guard).toEqual([{ atom: "version_2_2", negate: false }]);
    expect(t.actions).toHaveLength(3);
    expect(t.actions[0].verb).toBe("discard_I_frame_queue");
    expect(t.actions[0].kind).toBe("processing");
    expect(t.actions[1].verb).toBe("Establish_Data_Link");
    expect(t.actions[1].kind).toBe("subroutine");
    expect(t.actions[2].verb).toBe("Set Layer 3 Initiated");
    expect(t.actions[2].kind).toBe("processing");
  });

  it("t08_all_other_primitives__from_upper_layer", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t08_all_other_primitives__from_upper_layer");
    expect(t, "transition t08_all_other_primitives__from_upper_layer not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("all_other_primitives__from_upper_layer");
    expect(t.next).toBe("Connected");
    expect(t.actions).toHaveLength(0);
  });

  it("t09_control_field_error_no", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t09_control_field_error_no");
    expect(t, "transition t09_control_field_error_no not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("control_field_error");
    expect(t.next).toBe("AwaitingConnection");
    expect(t.guard).toEqual([{ atom: "version_2_2", negate: true }]);
    expect(t.actions).toHaveLength(4);
    expect(t.actions[0].verb).toBe("DL-ERROR Indication (L)");
    expect(t.actions[0].kind).toBe("signal_upper");
    expect(t.actions[1].verb).toBe("discard_I_frame_queue");
    expect(t.actions[1].kind).toBe("processing");
    expect(t.actions[2].verb).toBe("Establish_Data_Link");
    expect(t.actions[2].kind).toBe("subroutine");
    expect(t.actions[3].verb).toBe("Set Layer 3 Initiated");
    expect(t.actions[3].kind).toBe("processing");
  });

  it("t09_control_field_error_yes", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t09_control_field_error_yes");
    expect(t, "transition t09_control_field_error_yes not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("control_field_error");
    expect(t.next).toBe("AwaitingV22Connection");
    expect(t.guard).toEqual([{ atom: "version_2_2", negate: false }]);
    expect(t.actions).toHaveLength(4);
    expect(t.actions[0].verb).toBe("DL-ERROR Indication (L)");
    expect(t.actions[0].kind).toBe("signal_upper");
    expect(t.actions[1].verb).toBe("discard_I_frame_queue");
    expect(t.actions[1].kind).toBe("processing");
    expect(t.actions[2].verb).toBe("Establish_Data_Link");
    expect(t.actions[2].kind).toBe("subroutine");
    expect(t.actions[3].verb).toBe("Set Layer 3 Initiated");
    expect(t.actions[3].kind).toBe("processing");
  });

  it("t10_info_not_permitted_in_frame_no", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t10_info_not_permitted_in_frame_no");
    expect(t, "transition t10_info_not_permitted_in_frame_no not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("info_not_permitted_in_frame");
    expect(t.next).toBe("AwaitingConnection");
    expect(t.guard).toEqual([{ atom: "version_2_2", negate: true }]);
    expect(t.actions).toHaveLength(4);
    expect(t.actions[0].verb).toBe("DL-ERROR Indication (M)");
    expect(t.actions[0].kind).toBe("signal_upper");
    expect(t.actions[1].verb).toBe("discard_I_frame_queue");
    expect(t.actions[1].kind).toBe("processing");
    expect(t.actions[2].verb).toBe("Establish_Data_Link");
    expect(t.actions[2].kind).toBe("subroutine");
    expect(t.actions[3].verb).toBe("Set Layer 3 Initiated");
    expect(t.actions[3].kind).toBe("processing");
  });

  it("t10_info_not_permitted_in_frame_yes", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t10_info_not_permitted_in_frame_yes");
    expect(t, "transition t10_info_not_permitted_in_frame_yes not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("info_not_permitted_in_frame");
    expect(t.next).toBe("AwaitingV22Connection");
    expect(t.guard).toEqual([{ atom: "version_2_2", negate: false }]);
    expect(t.actions).toHaveLength(4);
    expect(t.actions[0].verb).toBe("DL-ERROR Indication (M)");
    expect(t.actions[0].kind).toBe("signal_upper");
    expect(t.actions[1].verb).toBe("discard_I_frame_queue");
    expect(t.actions[1].kind).toBe("processing");
    expect(t.actions[2].verb).toBe("Establish_Data_Link");
    expect(t.actions[2].kind).toBe("subroutine");
    expect(t.actions[3].verb).toBe("Set Layer 3 Initiated");
    expect(t.actions[3].kind).toBe("processing");
  });

  it("t11_u_or_s_frame_length_error_no", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t11_u_or_s_frame_length_error_no");
    expect(t, "transition t11_u_or_s_frame_length_error_no not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("u_or_s_frame_length_error");
    expect(t.next).toBe("AwaitingConnection");
    expect(t.guard).toEqual([{ atom: "version_2_2", negate: true }]);
    expect(t.actions).toHaveLength(4);
    expect(t.actions[0].verb).toBe("DL-ERROR Indication (N)");
    expect(t.actions[0].kind).toBe("signal_upper");
    expect(t.actions[1].verb).toBe("discard_I_frame_queue");
    expect(t.actions[1].kind).toBe("processing");
    expect(t.actions[2].verb).toBe("Establish_Data_Link");
    expect(t.actions[2].kind).toBe("subroutine");
    expect(t.actions[3].verb).toBe("Set Layer 3 Initiated");
    expect(t.actions[3].kind).toBe("processing");
  });

  it("t11_u_or_s_frame_length_error_yes", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t11_u_or_s_frame_length_error_yes");
    expect(t, "transition t11_u_or_s_frame_length_error_yes not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("u_or_s_frame_length_error");
    expect(t.next).toBe("AwaitingV22Connection");
    expect(t.guard).toEqual([{ atom: "version_2_2", negate: false }]);
    expect(t.actions).toHaveLength(4);
    expect(t.actions[0].verb).toBe("DL-ERROR Indication (N)");
    expect(t.actions[0].kind).toBe("signal_upper");
    expect(t.actions[1].verb).toBe("discard_I_frame_queue");
    expect(t.actions[1].kind).toBe("processing");
    expect(t.actions[2].verb).toBe("Establish_Data_Link");
    expect(t.actions[2].kind).toBe("subroutine");
    expect(t.actions[3].verb).toBe("Set Layer 3 Initiated");
    expect(t.actions[3].kind).toBe("processing");
  });

  it("t12_t1_expiry", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t12_t1_expiry");
    expect(t, "transition t12_t1_expiry not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("T1_expiry");
    expect(t.next).toBe("TimerRecovery");
    expect(t.actions).toHaveLength(2);
    expect(t.actions[0].verb).toBe("RC := 1");
    expect(t.actions[0].kind).toBe("processing");
    expect(t.actions[1].verb).toBe("Transmit Enquery");
    expect(t.actions[1].kind).toBe("subroutine");
  });

  it("t13_t3_expiry", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t13_t3_expiry");
    expect(t, "transition t13_t3_expiry not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("T3_expiry");
    expect(t.next).toBe("TimerRecovery");
    expect(t.actions).toHaveLength(2);
    expect(t.actions[0].verb).toBe("RC := 1");
    expect(t.actions[0].kind).toBe("processing");
    expect(t.actions[1].verb).toBe("Transmit Enquery");
    expect(t.actions[1].kind).toBe("subroutine");
  });

  it("t14_sabm_received_yes", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t14_sabm_received_yes");
    expect(t, "transition t14_sabm_received_yes not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("SABM_received");
    expect(t.next).toBe("Connected");
    expect(t.guard).toEqual([{ atom: "vs_eq_va", negate: false }]);
    expect(t.actions).toHaveLength(11);
    expect(t.actions[0].verb).toBe("F := P");
    expect(t.actions[0].kind).toBe("processing");
    expect(t.actions[1].verb).toBe("set_version_2_0");
    expect(t.actions[1].kind).toBe("processing");
    expect(t.actions[2].verb).toBe("UA");
    expect(t.actions[2].kind).toBe("signal_lower");
    expect(t.actions[3].verb).toBe("Clear Exception Conditions");
    expect(t.actions[3].kind).toBe("subroutine");
    expect(t.actions[4].verb).toBe("DL-ERROR Indication (F)");
    expect(t.actions[4].kind).toBe("signal_upper");
    expect(t.actions[5].verb).toBe("Stop T1");
    expect(t.actions[5].kind).toBe("processing");
    expect(t.actions[6].verb).toBe("Start T3");
    expect(t.actions[6].kind).toBe("processing");
    expect(t.actions[7].verb).toBe("V(a) := 0");
    expect(t.actions[7].kind).toBe("processing");
    expect(t.actions[8].verb).toBe("V(s) := 0");
    expect(t.actions[8].kind).toBe("processing");
    expect(t.actions[9].verb).toBe("V(r) := 0");
    expect(t.actions[9].kind).toBe("processing");
    expect(t.actions[10].verb).toBe("RC := 0");
    expect(t.actions[10].kind).toBe("processing");
  });

  it("t14_sabm_received_no", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t14_sabm_received_no");
    expect(t, "transition t14_sabm_received_no not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("SABM_received");
    expect(t.next).toBe("Connected");
    expect(t.guard).toEqual([{ atom: "vs_eq_va", negate: true }]);
    expect(t.actions).toHaveLength(13);
    expect(t.actions[0].verb).toBe("F := P");
    expect(t.actions[0].kind).toBe("processing");
    expect(t.actions[1].verb).toBe("set_version_2_0");
    expect(t.actions[1].kind).toBe("processing");
    expect(t.actions[2].verb).toBe("UA");
    expect(t.actions[2].kind).toBe("signal_lower");
    expect(t.actions[3].verb).toBe("Clear Exception Conditions");
    expect(t.actions[3].kind).toBe("subroutine");
    expect(t.actions[4].verb).toBe("DL-ERROR Indication (F)");
    expect(t.actions[4].kind).toBe("signal_upper");
    expect(t.actions[5].verb).toBe("discard_I_frame_queue");
    expect(t.actions[5].kind).toBe("processing");
    expect(t.actions[6].verb).toBe("DL_CONNECT_indication");
    expect(t.actions[6].kind).toBe("signal_upper");
    expect(t.actions[7].verb).toBe("Stop T1");
    expect(t.actions[7].kind).toBe("processing");
    expect(t.actions[8].verb).toBe("Start T3");
    expect(t.actions[8].kind).toBe("processing");
    expect(t.actions[9].verb).toBe("V(a) := 0");
    expect(t.actions[9].kind).toBe("processing");
    expect(t.actions[10].verb).toBe("V(s) := 0");
    expect(t.actions[10].kind).toBe("processing");
    expect(t.actions[11].verb).toBe("V(r) := 0");
    expect(t.actions[11].kind).toBe("processing");
    expect(t.actions[12].verb).toBe("RC := 0");
    expect(t.actions[12].kind).toBe("processing");
  });

  it("t15_sabme_received_yes", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t15_sabme_received_yes");
    expect(t, "transition t15_sabme_received_yes not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("SABME_received");
    expect(t.next).toBe("Connected");
    expect(t.guard).toEqual([{ atom: "vs_eq_va", negate: false }]);
    expect(t.actions).toHaveLength(11);
    expect(t.actions[0].verb).toBe("F := P");
    expect(t.actions[0].kind).toBe("processing");
    expect(t.actions[1].verb).toBe("Set Version 2.2");
    expect(t.actions[1].kind).toBe("processing");
    expect(t.actions[2].verb).toBe("UA");
    expect(t.actions[2].kind).toBe("signal_lower");
    expect(t.actions[3].verb).toBe("Clear Exception Conditions");
    expect(t.actions[3].kind).toBe("subroutine");
    expect(t.actions[4].verb).toBe("DL-ERROR Indication (F)");
    expect(t.actions[4].kind).toBe("signal_upper");
    expect(t.actions[5].verb).toBe("Stop T1");
    expect(t.actions[5].kind).toBe("processing");
    expect(t.actions[6].verb).toBe("Start T3");
    expect(t.actions[6].kind).toBe("processing");
    expect(t.actions[7].verb).toBe("V(a) := 0");
    expect(t.actions[7].kind).toBe("processing");
    expect(t.actions[8].verb).toBe("V(s) := 0");
    expect(t.actions[8].kind).toBe("processing");
    expect(t.actions[9].verb).toBe("V(r) := 0");
    expect(t.actions[9].kind).toBe("processing");
    expect(t.actions[10].verb).toBe("RC := 0");
    expect(t.actions[10].kind).toBe("processing");
  });

  it("t15_sabme_received_no", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t15_sabme_received_no");
    expect(t, "transition t15_sabme_received_no not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("SABME_received");
    expect(t.next).toBe("Connected");
    expect(t.guard).toEqual([{ atom: "vs_eq_va", negate: true }]);
    expect(t.actions).toHaveLength(13);
    expect(t.actions[0].verb).toBe("F := P");
    expect(t.actions[0].kind).toBe("processing");
    expect(t.actions[1].verb).toBe("Set Version 2.2");
    expect(t.actions[1].kind).toBe("processing");
    expect(t.actions[2].verb).toBe("UA");
    expect(t.actions[2].kind).toBe("signal_lower");
    expect(t.actions[3].verb).toBe("Clear Exception Conditions");
    expect(t.actions[3].kind).toBe("subroutine");
    expect(t.actions[4].verb).toBe("DL-ERROR Indication (F)");
    expect(t.actions[4].kind).toBe("signal_upper");
    expect(t.actions[5].verb).toBe("discard_I_frame_queue");
    expect(t.actions[5].kind).toBe("processing");
    expect(t.actions[6].verb).toBe("DL_CONNECT_indication");
    expect(t.actions[6].kind).toBe("signal_upper");
    expect(t.actions[7].verb).toBe("Stop T1");
    expect(t.actions[7].kind).toBe("processing");
    expect(t.actions[8].verb).toBe("Start T3");
    expect(t.actions[8].kind).toBe("processing");
    expect(t.actions[9].verb).toBe("V(a) := 0");
    expect(t.actions[9].kind).toBe("processing");
    expect(t.actions[10].verb).toBe("V(s) := 0");
    expect(t.actions[10].kind).toBe("processing");
    expect(t.actions[11].verb).toBe("V(r) := 0");
    expect(t.actions[11].kind).toBe("processing");
    expect(t.actions[12].verb).toBe("RC := 0");
    expect(t.actions[12].kind).toBe("processing");
  });

  it("t16_frmr_received_no", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t16_frmr_received_no");
    expect(t, "transition t16_frmr_received_no not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("FRMR_received");
    expect(t.next).toBe("AwaitingConnection");
    expect(t.guard).toEqual([{ atom: "version_2_2", negate: true }]);
    expect(t.actions).toHaveLength(3);
    expect(t.actions[0].verb).toBe("DL-ERROR Indication (K)");
    expect(t.actions[0].kind).toBe("signal_upper");
    expect(t.actions[1].verb).toBe("Establish_Data_Link");
    expect(t.actions[1].kind).toBe("subroutine");
    expect(t.actions[2].verb).toBe("Clear Layer 3 Initiated");
    expect(t.actions[2].kind).toBe("processing");
  });

  it("t16_frmr_received_yes", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t16_frmr_received_yes");
    expect(t, "transition t16_frmr_received_yes not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("FRMR_received");
    expect(t.next).toBe("AwaitingV22Connection");
    expect(t.guard).toEqual([{ atom: "version_2_2", negate: false }]);
    expect(t.actions).toHaveLength(3);
    expect(t.actions[0].verb).toBe("DL-ERROR Indication (K)");
    expect(t.actions[0].kind).toBe("signal_upper");
    expect(t.actions[1].verb).toBe("Establish_Data_Link");
    expect(t.actions[1].kind).toBe("subroutine");
    expect(t.actions[2].verb).toBe("Clear Layer 3 Initiated");
    expect(t.actions[2].kind).toBe("processing");
  });

  it("t17_ua_received_no", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t17_ua_received_no");
    expect(t, "transition t17_ua_received_no not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("UA_received");
    expect(t.next).toBe("AwaitingConnection");
    expect(t.guard).toEqual([{ atom: "version_2_2", negate: true }]);
    expect(t.actions).toHaveLength(3);
    expect(t.actions[0].verb).toBe("DL-ERROR Indication (K)");
    expect(t.actions[0].kind).toBe("signal_upper");
    expect(t.actions[1].verb).toBe("Establish_Data_Link");
    expect(t.actions[1].kind).toBe("subroutine");
    expect(t.actions[2].verb).toBe("Clear Layer 3 Initiated");
    expect(t.actions[2].kind).toBe("processing");
  });

  it("t17_ua_received_yes", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t17_ua_received_yes");
    expect(t, "transition t17_ua_received_yes not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("UA_received");
    expect(t.next).toBe("AwaitingV22Connection");
    expect(t.guard).toEqual([{ atom: "version_2_2", negate: false }]);
    expect(t.actions).toHaveLength(3);
    expect(t.actions[0].verb).toBe("DL-ERROR Indication (K)");
    expect(t.actions[0].kind).toBe("signal_upper");
    expect(t.actions[1].verb).toBe("Establish_Data_Link");
    expect(t.actions[1].kind).toBe("subroutine");
    expect(t.actions[2].verb).toBe("Clear Layer 3 Initiated");
    expect(t.actions[2].kind).toBe("processing");
  });

  it("t18_ui_received_yes", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t18_ui_received_yes");
    expect(t, "transition t18_ui_received_yes not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("UI_received");
    expect(t.next).toBe("Connected");
    expect(t.guard).toEqual([{ atom: "P_eq_1", negate: false }]);
    expect(t.actions).toHaveLength(2);
    expect(t.actions[0].verb).toBe("UI Check");
    expect(t.actions[0].kind).toBe("subroutine");
    expect(t.actions[1].verb).toBe("Enquiry_Response_F_1");
    expect(t.actions[1].kind).toBe("subroutine");
  });

  it("t18_ui_received_no", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t18_ui_received_no");
    expect(t, "transition t18_ui_received_no not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("UI_received");
    expect(t.next).toBe("Connected");
    expect(t.guard).toEqual([{ atom: "P_eq_1", negate: true }]);
    expect(t.actions).toHaveLength(1);
    expect(t.actions[0].verb).toBe("UI Check");
    expect(t.actions[0].kind).toBe("subroutine");
  });

  it("t19_disc_received", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t19_disc_received");
    expect(t, "transition t19_disc_received not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("DISC_received");
    expect(t.next).toBe("Disconnected");
    expect(t.actions).toHaveLength(6);
    expect(t.actions[0].verb).toBe("discard_I_frame_queue");
    expect(t.actions[0].kind).toBe("processing");
    expect(t.actions[1].verb).toBe("F := P");
    expect(t.actions[1].kind).toBe("processing");
    expect(t.actions[2].verb).toBe("UA");
    expect(t.actions[2].kind).toBe("signal_lower");
    expect(t.actions[3].verb).toBe("DL_DISCONNECT_indication");
    expect(t.actions[3].kind).toBe("signal_upper");
    expect(t.actions[4].verb).toBe("Stop T3");
    expect(t.actions[4].kind).toBe("processing");
    expect(t.actions[5].verb).toBe("Start T1");
    expect(t.actions[5].kind).toBe("processing");
  });

  it("t20_dm_received", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t20_dm_received");
    expect(t, "transition t20_dm_received not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("DM_received");
    expect(t.next).toBe("Disconnected");
    expect(t.actions).toHaveLength(5);
    expect(t.actions[0].verb).toBe("DL-ERROR Indication (E)");
    expect(t.actions[0].kind).toBe("signal_upper");
    expect(t.actions[1].verb).toBe("DL_DISCONNECT_indication");
    expect(t.actions[1].kind).toBe("signal_upper");
    expect(t.actions[2].verb).toBe("discard_I_frame_queue");
    expect(t.actions[2].kind).toBe("processing");
    expect(t.actions[3].verb).toBe("Stop T1");
    expect(t.actions[3].kind).toBe("processing");
    expect(t.actions[4].verb).toBe("Stop T3");
    expect(t.actions[4].kind).toBe("processing");
  });

  it("t21_rr_received_yes", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t21_rr_received_yes");
    expect(t, "transition t21_rr_received_yes not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("RR_received");
    expect(t.next).toBe("Connected");
    expect(t.guard).toEqual([{ atom: "va_le_nr_le_vs", negate: false }]);
    expect(t.actions).toHaveLength(3);
    expect(t.actions[0].verb).toBe("clear_peer_receiver_busy");
    expect(t.actions[0].kind).toBe("processing");
    expect(t.actions[1].verb).toBe("Check Need For Response");
    expect(t.actions[1].kind).toBe("subroutine");
    expect(t.actions[2].verb).toBe("Check_I_Frame_Acknowledged");
    expect(t.actions[2].kind).toBe("subroutine");
  });

  it("t21_rr_received_no_no", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t21_rr_received_no_no");
    expect(t, "transition t21_rr_received_no_no not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("RR_received");
    expect(t.next).toBe("AwaitingConnection");
    expect(t.guard).toEqual([{ atom: "va_le_nr_le_vs", negate: true }, { atom: "version_2_2", negate: true }]);
    expect(t.actions).toHaveLength(3);
    expect(t.actions[0].verb).toBe("clear_peer_receiver_busy");
    expect(t.actions[0].kind).toBe("processing");
    expect(t.actions[1].verb).toBe("Check Need For Response");
    expect(t.actions[1].kind).toBe("subroutine");
    expect(t.actions[2].verb).toBe("N(r) Error Recovery");
    expect(t.actions[2].kind).toBe("subroutine");
  });

  it("t21_rr_received_no_yes", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t21_rr_received_no_yes");
    expect(t, "transition t21_rr_received_no_yes not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("RR_received");
    expect(t.next).toBe("AwaitingV22Connection");
    expect(t.guard).toEqual([{ atom: "va_le_nr_le_vs", negate: true }, { atom: "version_2_2", negate: false }]);
    expect(t.actions).toHaveLength(3);
    expect(t.actions[0].verb).toBe("clear_peer_receiver_busy");
    expect(t.actions[0].kind).toBe("processing");
    expect(t.actions[1].verb).toBe("Check Need For Response");
    expect(t.actions[1].kind).toBe("subroutine");
    expect(t.actions[2].verb).toBe("N(r) Error Recovery");
    expect(t.actions[2].kind).toBe("subroutine");
  });

  it("t22_rnr_received_yes", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t22_rnr_received_yes");
    expect(t, "transition t22_rnr_received_yes not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("RNR_received");
    expect(t.next).toBe("Connected");
    expect(t.guard).toEqual([{ atom: "va_le_nr_le_vs", negate: false }]);
    expect(t.actions).toHaveLength(3);
    expect(t.actions[0].verb).toBe("set_peer_receiver_busy");
    expect(t.actions[0].kind).toBe("processing");
    expect(t.actions[1].verb).toBe("Check Need For Response");
    expect(t.actions[1].kind).toBe("subroutine");
    expect(t.actions[2].verb).toBe("Check_I_Frame_Acknowledged");
    expect(t.actions[2].kind).toBe("subroutine");
  });

  it("t22_rnr_received_no_no", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t22_rnr_received_no_no");
    expect(t, "transition t22_rnr_received_no_no not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("RNR_received");
    expect(t.next).toBe("AwaitingConnection");
    expect(t.guard).toEqual([{ atom: "va_le_nr_le_vs", negate: true }, { atom: "version_2_2", negate: true }]);
    expect(t.actions).toHaveLength(3);
    expect(t.actions[0].verb).toBe("set_peer_receiver_busy");
    expect(t.actions[0].kind).toBe("processing");
    expect(t.actions[1].verb).toBe("Check Need For Response");
    expect(t.actions[1].kind).toBe("subroutine");
    expect(t.actions[2].verb).toBe("N(r) Error Recovery");
    expect(t.actions[2].kind).toBe("subroutine");
  });

  it("t22_rnr_received_no_yes", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t22_rnr_received_no_yes");
    expect(t, "transition t22_rnr_received_no_yes not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("RNR_received");
    expect(t.next).toBe("AwaitingV22Connection");
    expect(t.guard).toEqual([{ atom: "va_le_nr_le_vs", negate: true }, { atom: "version_2_2", negate: false }]);
    expect(t.actions).toHaveLength(3);
    expect(t.actions[0].verb).toBe("set_peer_receiver_busy");
    expect(t.actions[0].kind).toBe("processing");
    expect(t.actions[1].verb).toBe("Check Need For Response");
    expect(t.actions[1].kind).toBe("subroutine");
    expect(t.actions[2].verb).toBe("N(r) Error Recovery");
    expect(t.actions[2].kind).toBe("subroutine");
  });

  it("t23_lm_seize_confirm_yes", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t23_lm_seize_confirm_yes");
    expect(t, "transition t23_lm_seize_confirm_yes not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("LM_SEIZE_confirm");
    expect(t.next).toBe("Connected");
    expect(t.guard).toEqual([{ atom: "ack_pending", negate: false }]);
    expect(t.actions).toHaveLength(3);
    expect(t.actions[0].verb).toBe("Clear Acknowledge Pending");
    expect(t.actions[0].kind).toBe("processing");
    expect(t.actions[1].verb).toBe("Enquiry Response (F = 0)");
    expect(t.actions[1].kind).toBe("subroutine");
    expect(t.actions[2].verb).toBe("LM_release_request");
    expect(t.actions[2].kind).toBe("signal_lower");
  });

  it("t23_lm_seize_confirm_no", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t23_lm_seize_confirm_no");
    expect(t, "transition t23_lm_seize_confirm_no not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("LM_SEIZE_confirm");
    expect(t.next).toBe("Connected");
    expect(t.guard).toEqual([{ atom: "ack_pending", negate: true }]);
    expect(t.actions).toHaveLength(1);
    expect(t.actions[0].verb).toBe("LM_release_request");
    expect(t.actions[0].kind).toBe("signal_lower");
  });

  it("t24_srej_received_yes_yes", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t24_srej_received_yes_yes");
    expect(t, "transition t24_srej_received_yes_yes not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("SREJ_received");
    expect(t.next).toBe("Connected");
    expect(t.guard).toEqual([{ atom: "va_le_nr_le_vs", negate: false }, { atom: "P_or_F_eq_1", negate: false }]);
    expect(t.actions).toHaveLength(11);
    expect(t.actions[0].verb).toBe("clear_peer_receiver_busy");
    expect(t.actions[0].kind).toBe("processing");
    expect(t.actions[1].verb).toBe("Check Need For Response");
    expect(t.actions[1].kind).toBe("subroutine");
    expect(t.actions[2].verb).toBe("V(a) := N(r)");
    expect(t.actions[2].kind).toBe("processing");
    expect(t.actions[3].verb).toBe("Stop T1");
    expect(t.actions[3].kind).toBe("processing");
    expect(t.actions[4].verb).toBe("Start T3");
    expect(t.actions[4].kind).toBe("processing");
    expect(t.actions[5].verb).toBe("Select_T1_Value");
    expect(t.actions[5].kind).toBe("subroutine");
    expect(t.actions[6].verb).toBe("Push Old I Frame N(r) on Queue");
    expect(t.actions[6].kind).toBe("internal_out");
    expect(t.actions[7].verb).toBe("LM_data_request");
    expect(t.actions[7].kind).toBe("signal_lower");
    expect(t.actions[8].verb).toBe("Stop T3");
    expect(t.actions[8].kind).toBe("processing");
    expect(t.actions[9].verb).toBe("Start T1");
    expect(t.actions[9].kind).toBe("processing");
    expect(t.actions[10].verb).toBe("Clear Acknowledge Pending");
    expect(t.actions[10].kind).toBe("processing");
  });

  it("t24_srej_received_yes_no", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t24_srej_received_yes_no");
    expect(t, "transition t24_srej_received_yes_no not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("SREJ_received");
    expect(t.next).toBe("Connected");
    expect(t.guard).toEqual([{ atom: "va_le_nr_le_vs", negate: false }, { atom: "P_or_F_eq_1", negate: true }]);
    expect(t.actions).toHaveLength(10);
    expect(t.actions[0].verb).toBe("clear_peer_receiver_busy");
    expect(t.actions[0].kind).toBe("processing");
    expect(t.actions[1].verb).toBe("Check Need For Response");
    expect(t.actions[1].kind).toBe("subroutine");
    expect(t.actions[2].verb).toBe("Stop T1");
    expect(t.actions[2].kind).toBe("processing");
    expect(t.actions[3].verb).toBe("Start T3");
    expect(t.actions[3].kind).toBe("processing");
    expect(t.actions[4].verb).toBe("Select_T1_Value");
    expect(t.actions[4].kind).toBe("subroutine");
    expect(t.actions[5].verb).toBe("Push Old I Frame N(r) on Queue");
    expect(t.actions[5].kind).toBe("internal_out");
    expect(t.actions[6].verb).toBe("LM_data_request");
    expect(t.actions[6].kind).toBe("signal_lower");
    expect(t.actions[7].verb).toBe("Stop T3");
    expect(t.actions[7].kind).toBe("processing");
    expect(t.actions[8].verb).toBe("Start T1");
    expect(t.actions[8].kind).toBe("processing");
    expect(t.actions[9].verb).toBe("Clear Acknowledge Pending");
    expect(t.actions[9].kind).toBe("processing");
  });

  it("t24_srej_received_no_no", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t24_srej_received_no_no");
    expect(t, "transition t24_srej_received_no_no not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("SREJ_received");
    expect(t.next).toBe("AwaitingConnection");
    expect(t.guard).toEqual([{ atom: "va_le_nr_le_vs", negate: true }, { atom: "version_2_2", negate: true }]);
    expect(t.actions).toHaveLength(3);
    expect(t.actions[0].verb).toBe("clear_peer_receiver_busy");
    expect(t.actions[0].kind).toBe("processing");
    expect(t.actions[1].verb).toBe("Check Need For Response");
    expect(t.actions[1].kind).toBe("subroutine");
    expect(t.actions[2].verb).toBe("N(r) Error Recovery");
    expect(t.actions[2].kind).toBe("subroutine");
  });

  it("t24_srej_received_no_yes", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t24_srej_received_no_yes");
    expect(t, "transition t24_srej_received_no_yes not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("SREJ_received");
    expect(t.next).toBe("AwaitingV22Connection");
    expect(t.guard).toEqual([{ atom: "va_le_nr_le_vs", negate: true }, { atom: "version_2_2", negate: false }]);
    expect(t.actions).toHaveLength(3);
    expect(t.actions[0].verb).toBe("clear_peer_receiver_busy");
    expect(t.actions[0].kind).toBe("processing");
    expect(t.actions[1].verb).toBe("Check Need For Response");
    expect(t.actions[1].kind).toBe("subroutine");
    expect(t.actions[2].verb).toBe("N(r) Error Recovery");
    expect(t.actions[2].kind).toBe("subroutine");
  });

  it("t25_rej_received_no_no", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t25_rej_received_no_no");
    expect(t, "transition t25_rej_received_no_no not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("REJ_received");
    expect(t.next).toBe("AwaitingConnection");
    expect(t.guard).toEqual([{ atom: "va_le_nr_le_vs", negate: true }, { atom: "version_2_2", negate: true }]);
    expect(t.actions).toHaveLength(3);
    expect(t.actions[0].verb).toBe("clear_peer_receiver_busy");
    expect(t.actions[0].kind).toBe("processing");
    expect(t.actions[1].verb).toBe("Check Need For Response");
    expect(t.actions[1].kind).toBe("subroutine");
    expect(t.actions[2].verb).toBe("N(r) Error Recovery");
    expect(t.actions[2].kind).toBe("subroutine");
  });

  it("t25_rej_received_no_yes", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t25_rej_received_no_yes");
    expect(t, "transition t25_rej_received_no_yes not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("REJ_received");
    expect(t.next).toBe("AwaitingV22Connection");
    expect(t.guard).toEqual([{ atom: "va_le_nr_le_vs", negate: true }, { atom: "version_2_2", negate: false }]);
    expect(t.actions).toHaveLength(3);
    expect(t.actions[0].verb).toBe("clear_peer_receiver_busy");
    expect(t.actions[0].kind).toBe("processing");
    expect(t.actions[1].verb).toBe("Check Need For Response");
    expect(t.actions[1].kind).toBe("subroutine");
    expect(t.actions[2].verb).toBe("N(r) Error Recovery");
    expect(t.actions[2].kind).toBe("subroutine");
  });

  it("t25_rej_received_yes", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t25_rej_received_yes");
    expect(t, "transition t25_rej_received_yes not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("REJ_received");
    expect(t.next).toBe("Connected");
    expect(t.guard).toEqual([{ atom: "va_le_nr_le_vs", negate: false }]);
    expect(t.actions).toHaveLength(8);
    expect(t.actions[0].verb).toBe("clear_peer_receiver_busy");
    expect(t.actions[0].kind).toBe("processing");
    expect(t.actions[1].verb).toBe("Check Need For Response");
    expect(t.actions[1].kind).toBe("subroutine");
    expect(t.actions[2].verb).toBe("V(a) := N(r)");
    expect(t.actions[2].kind).toBe("processing");
    expect(t.actions[3].verb).toBe("Start T1");
    expect(t.actions[3].kind).toBe("processing");
    expect(t.actions[4].verb).toBe("Stop T3");
    expect(t.actions[4].kind).toBe("processing");
    expect(t.actions[5].verb).toBe("Clear Acknowledge Pending");
    expect(t.actions[5].kind).toBe("processing");
    expect(t.actions[6].verb).toBe("Select_T1_Value");
    expect(t.actions[6].kind).toBe("subroutine");
    expect(t.actions[7].verb).toBe("Invoke Retransmission");
    expect(t.actions[7].kind).toBe("subroutine");
  });

  it("t26_i_received_yes_no_no", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t26_i_received_yes_no_no");
    expect(t, "transition t26_i_received_yes_no_no not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("I_received");
    expect(t.next).toBe("AwaitingConnection");
    expect(t.guard).toEqual([{ atom: "command", negate: false }, { atom: "info_field_length_le_N1_and_content_is_octet_aligned", negate: true }, { atom: "version_2_2", negate: true }]);
    expect(t.actions).toHaveLength(3);
    expect(t.actions[0].verb).toBe("DL-ERROR Indication (O)");
    expect(t.actions[0].kind).toBe("signal_upper");
    expect(t.actions[1].verb).toBe("Establish_Data_Link");
    expect(t.actions[1].kind).toBe("subroutine");
    expect(t.actions[2].verb).toBe("Clear Layer 3 Initiated");
    expect(t.actions[2].kind).toBe("processing");
  });

  it("t26_i_received_yes_no_yes", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t26_i_received_yes_no_yes");
    expect(t, "transition t26_i_received_yes_no_yes not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("I_received");
    expect(t.next).toBe("AwaitingV22Connection");
    expect(t.guard).toEqual([{ atom: "command", negate: false }, { atom: "info_field_length_le_N1_and_content_is_octet_aligned", negate: true }, { atom: "version_2_2", negate: false }]);
    expect(t.actions).toHaveLength(3);
    expect(t.actions[0].verb).toBe("DL-ERROR Indication (O)");
    expect(t.actions[0].kind).toBe("signal_upper");
    expect(t.actions[1].verb).toBe("Establish_Data_Link");
    expect(t.actions[1].kind).toBe("subroutine");
    expect(t.actions[2].verb).toBe("Clear Layer 3 Initiated");
    expect(t.actions[2].kind).toBe("processing");
  });

  it("t26_i_received_yes_yes_no_no", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t26_i_received_yes_yes_no_no");
    expect(t, "transition t26_i_received_yes_yes_no_no not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("I_received");
    expect(t.next).toBe("AwaitingConnection");
    expect(t.guard).toEqual([{ atom: "command", negate: false }, { atom: "info_field_length_le_N1_and_content_is_octet_aligned", negate: false }, { atom: "va_le_nr_le_vs", negate: true }, { atom: "version_2_2", negate: true }]);
    expect(t.actions).toHaveLength(1);
    expect(t.actions[0].verb).toBe("N(r) Error Recovery");
    expect(t.actions[0].kind).toBe("subroutine");
  });

  it("t26_i_received_yes_yes_no_yes", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t26_i_received_yes_yes_no_yes");
    expect(t, "transition t26_i_received_yes_yes_no_yes not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("I_received");
    expect(t.next).toBe("AwaitingV22Connection");
    expect(t.guard).toEqual([{ atom: "command", negate: false }, { atom: "info_field_length_le_N1_and_content_is_octet_aligned", negate: false }, { atom: "va_le_nr_le_vs", negate: true }, { atom: "version_2_2", negate: false }]);
    expect(t.actions).toHaveLength(1);
    expect(t.actions[0].verb).toBe("N(r) Error Recovery");
    expect(t.actions[0].kind).toBe("subroutine");
  });

  it("t26_i_received_yes_yes_yes_no_yes_no_no", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t26_i_received_yes_yes_yes_no_yes_no_no");
    expect(t, "transition t26_i_received_yes_yes_yes_no_yes_no_no not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("I_received");
    expect(t.next).toBe("Connected");
    expect(t.guard).toEqual([{ atom: "command", negate: false }, { atom: "info_field_length_le_N1_and_content_is_octet_aligned", negate: false }, { atom: "va_le_nr_le_vs", negate: false }, { atom: "own_receiver_busy", negate: true }, { atom: "ns_eq_vr", negate: false }, { atom: "P_eq_1", negate: true }, { atom: "ack_pending", negate: true }]);
    expect(t.actions).toHaveLength(10);
    expect(t.actions[0].verb).toBe("Check_I_Frame_Acknowledged");
    expect(t.actions[0].kind).toBe("subroutine");
    expect(t.actions[1].verb).toBe("V(r) := V(r) + 1");
    expect(t.actions[1].kind).toBe("processing");
    expect(t.actions[2].verb).toBe("Clear Reject Exception");
    expect(t.actions[2].kind).toBe("processing");
    expect(t.actions[3].verb).toBe("Decrement Sreject Exception if > 0");
    expect(t.actions[3].kind).toBe("processing");
    expect(t.actions[4].verb).toBe("DL_DATA_indication");
    expect(t.actions[4].kind).toBe("signal_upper");
    expect(t.actions[5].verb).toBe("Retrieve Stored V(r) I Frame");
    expect(t.actions[5].kind).toBe("processing");
    expect(t.actions[6].verb).toBe("DL_DATA_indication");
    expect(t.actions[6].kind).toBe("signal_upper");
    expect(t.actions[7].verb).toBe("V(r) := V(r) + 1");
    expect(t.actions[7].kind).toBe("processing");
    expect(t.actions[8].verb).toBe("LM_seize_request");
    expect(t.actions[8].kind).toBe("signal_lower");
    expect(t.actions[9].verb).toBe("set_acknowledge_pending");
    expect(t.actions[9].kind).toBe("processing");
  });

  it("t26_i_received_yes_yes_yes_no_yes_no_yes", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t26_i_received_yes_yes_yes_no_yes_no_yes");
    expect(t, "transition t26_i_received_yes_yes_yes_no_yes_no_yes not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("I_received");
    expect(t.next).toBe("Connected");
    expect(t.guard).toEqual([{ atom: "command", negate: false }, { atom: "info_field_length_le_N1_and_content_is_octet_aligned", negate: false }, { atom: "va_le_nr_le_vs", negate: false }, { atom: "own_receiver_busy", negate: true }, { atom: "ns_eq_vr", negate: false }, { atom: "P_eq_1", negate: true }, { atom: "ack_pending", negate: false }]);
    expect(t.actions).toHaveLength(8);
    expect(t.actions[0].verb).toBe("Check_I_Frame_Acknowledged");
    expect(t.actions[0].kind).toBe("subroutine");
    expect(t.actions[1].verb).toBe("V(r) := V(r) + 1");
    expect(t.actions[1].kind).toBe("processing");
    expect(t.actions[2].verb).toBe("Clear Reject Exception");
    expect(t.actions[2].kind).toBe("processing");
    expect(t.actions[3].verb).toBe("Decrement Sreject Exception if > 0");
    expect(t.actions[3].kind).toBe("processing");
    expect(t.actions[4].verb).toBe("DL_DATA_indication");
    expect(t.actions[4].kind).toBe("signal_upper");
    expect(t.actions[5].verb).toBe("Retrieve Stored V(r) I Frame");
    expect(t.actions[5].kind).toBe("processing");
    expect(t.actions[6].verb).toBe("DL_DATA_indication");
    expect(t.actions[6].kind).toBe("signal_upper");
    expect(t.actions[7].verb).toBe("V(r) := V(r) + 1");
    expect(t.actions[7].kind).toBe("processing");
  });

  it("t26_i_received_yes_yes_yes_no_yes_yes", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t26_i_received_yes_yes_yes_no_yes_yes");
    expect(t, "transition t26_i_received_yes_yes_yes_no_yes_yes not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("I_received");
    expect(t.next).toBe("Connected");
    expect(t.guard).toEqual([{ atom: "command", negate: false }, { atom: "info_field_length_le_N1_and_content_is_octet_aligned", negate: false }, { atom: "va_le_nr_le_vs", negate: false }, { atom: "own_receiver_busy", negate: true }, { atom: "ns_eq_vr", negate: false }, { atom: "P_eq_1", negate: false }]);
    expect(t.actions).toHaveLength(12);
    expect(t.actions[0].verb).toBe("Check_I_Frame_Acknowledged");
    expect(t.actions[0].kind).toBe("subroutine");
    expect(t.actions[1].verb).toBe("V(r) := V(r) + 1");
    expect(t.actions[1].kind).toBe("processing");
    expect(t.actions[2].verb).toBe("Clear Reject Exception");
    expect(t.actions[2].kind).toBe("processing");
    expect(t.actions[3].verb).toBe("Decrement Sreject Exception if > 0");
    expect(t.actions[3].kind).toBe("processing");
    expect(t.actions[4].verb).toBe("DL_DATA_indication");
    expect(t.actions[4].kind).toBe("signal_upper");
    expect(t.actions[5].verb).toBe("Retrieve Stored V(r) I Frame");
    expect(t.actions[5].kind).toBe("processing");
    expect(t.actions[6].verb).toBe("DL_DATA_indication");
    expect(t.actions[6].kind).toBe("signal_upper");
    expect(t.actions[7].verb).toBe("V(r) := V(r) + 1");
    expect(t.actions[7].kind).toBe("processing");
    expect(t.actions[8].verb).toBe("F := 1");
    expect(t.actions[8].kind).toBe("processing");
    expect(t.actions[9].verb).toBe("N(r) := V(r)");
    expect(t.actions[9].kind).toBe("processing");
    expect(t.actions[10].verb).toBe("RR");
    expect(t.actions[10].kind).toBe("signal_lower");
    expect(t.actions[11].verb).toBe("Clear Acknowledge Pending");
    expect(t.actions[11].kind).toBe("processing");
  });

  it("t26_i_received_yes_yes_yes_no_no_yes_yes_yes", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t26_i_received_yes_yes_yes_no_no_yes_yes_yes");
    expect(t, "transition t26_i_received_yes_yes_yes_no_no_yes_yes_yes not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("I_received");
    expect(t.next).toBe("Connected");
    expect(t.guard).toEqual([{ atom: "command", negate: false }, { atom: "info_field_length_le_N1_and_content_is_octet_aligned", negate: false }, { atom: "va_le_nr_le_vs", negate: false }, { atom: "own_receiver_busy", negate: true }, { atom: "ns_eq_vr", negate: true }, { atom: "vr_lt_ns_lt_vr_plus_k", negate: false }, { atom: "reject_exception", negate: false }, { atom: "P_eq_1", negate: false }]);
    expect(t.actions).toHaveLength(6);
    expect(t.actions[0].verb).toBe("Check_I_Frame_Acknowledged");
    expect(t.actions[0].kind).toBe("subroutine");
    expect(t.actions[1].verb).toBe("Discard Contents of I Frame");
    expect(t.actions[1].kind).toBe("processing");
    expect(t.actions[2].verb).toBe("F := 1");
    expect(t.actions[2].kind).toBe("processing");
    expect(t.actions[3].verb).toBe("N(r) := V(r)");
    expect(t.actions[3].kind).toBe("processing");
    expect(t.actions[4].verb).toBe("RR");
    expect(t.actions[4].kind).toBe("signal_lower");
    expect(t.actions[5].verb).toBe("Clear Acknowledge Pending");
    expect(t.actions[5].kind).toBe("processing");
  });

  it("t26_i_received_yes_yes_yes_no_no_yes_yes_no", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t26_i_received_yes_yes_yes_no_no_yes_yes_no");
    expect(t, "transition t26_i_received_yes_yes_yes_no_no_yes_yes_no not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("I_received");
    expect(t.next).toBe("Connected");
    expect(t.guard).toEqual([{ atom: "command", negate: false }, { atom: "info_field_length_le_N1_and_content_is_octet_aligned", negate: false }, { atom: "va_le_nr_le_vs", negate: false }, { atom: "own_receiver_busy", negate: true }, { atom: "ns_eq_vr", negate: true }, { atom: "vr_lt_ns_lt_vr_plus_k", negate: false }, { atom: "reject_exception", negate: false }, { atom: "P_eq_1", negate: true }]);
    expect(t.actions).toHaveLength(2);
    expect(t.actions[0].verb).toBe("Check_I_Frame_Acknowledged");
    expect(t.actions[0].kind).toBe("subroutine");
    expect(t.actions[1].verb).toBe("Discard Contents of I Frame");
    expect(t.actions[1].kind).toBe("processing");
  });

  it("t26_i_received_yes_yes_yes_no_no_yes_no_no", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t26_i_received_yes_yes_yes_no_no_yes_no_no");
    expect(t, "transition t26_i_received_yes_yes_yes_no_no_yes_no_no not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("I_received");
    expect(t.next).toBe("Connected");
    expect(t.guard).toEqual([{ atom: "command", negate: false }, { atom: "info_field_length_le_N1_and_content_is_octet_aligned", negate: false }, { atom: "va_le_nr_le_vs", negate: false }, { atom: "own_receiver_busy", negate: true }, { atom: "ns_eq_vr", negate: true }, { atom: "vr_lt_ns_lt_vr_plus_k", negate: false }, { atom: "reject_exception", negate: true }, { atom: "SREJ_enabled", negate: true }]);
    expect(t.actions).toHaveLength(7);
    expect(t.actions[0].verb).toBe("Check_I_Frame_Acknowledged");
    expect(t.actions[0].kind).toBe("subroutine");
    expect(t.actions[1].verb).toBe("Discard Contents of I Frame");
    expect(t.actions[1].kind).toBe("processing");
    expect(t.actions[2].verb).toBe("Set Reject Exception");
    expect(t.actions[2].kind).toBe("processing");
    expect(t.actions[3].verb).toBe("F := P");
    expect(t.actions[3].kind).toBe("processing");
    expect(t.actions[4].verb).toBe("N(r) := V(r)");
    expect(t.actions[4].kind).toBe("processing");
    expect(t.actions[5].verb).toBe("REJ");
    expect(t.actions[5].kind).toBe("signal_lower");
    expect(t.actions[6].verb).toBe("Clear Acknowledge Pending");
    expect(t.actions[6].kind).toBe("processing");
  });

  it("t26_i_received_yes_yes_yes_no_no_yes_no_yes_yes", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t26_i_received_yes_yes_yes_no_no_yes_no_yes_yes");
    expect(t, "transition t26_i_received_yes_yes_yes_no_no_yes_no_yes_yes not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("I_received");
    expect(t.next).toBe("Connected");
    expect(t.guard).toEqual([{ atom: "command", negate: false }, { atom: "info_field_length_le_N1_and_content_is_octet_aligned", negate: false }, { atom: "va_le_nr_le_vs", negate: false }, { atom: "own_receiver_busy", negate: true }, { atom: "ns_eq_vr", negate: true }, { atom: "vr_lt_ns_lt_vr_plus_k", negate: false }, { atom: "reject_exception", negate: true }, { atom: "SREJ_enabled", negate: false }, { atom: "sreject_exception_gt_0", negate: false }]);
    expect(t.actions).toHaveLength(6);
    expect(t.actions[0].verb).toBe("Check_I_Frame_Acknowledged");
    expect(t.actions[0].kind).toBe("subroutine");
    expect(t.actions[1].verb).toBe("Save Contents of I Frame");
    expect(t.actions[1].kind).toBe("processing");
    expect(t.actions[2].verb).toBe("N(r) := N(s)");
    expect(t.actions[2].kind).toBe("processing");
    expect(t.actions[3].verb).toBe("F := 0");
    expect(t.actions[3].kind).toBe("processing");
    expect(t.actions[4].verb).toBe("Increment Sreject Exception");
    expect(t.actions[4].kind).toBe("processing");
    expect(t.actions[5].verb).toBe("SREJ");
    expect(t.actions[5].kind).toBe("signal_lower");
  });

  it("t26_i_received_yes_yes_yes_no_no_yes_no_yes_no_yes", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t26_i_received_yes_yes_yes_no_no_yes_no_yes_no_yes");
    expect(t, "transition t26_i_received_yes_yes_yes_no_no_yes_no_yes_no_yes not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("I_received");
    expect(t.next).toBe("Connected");
    expect(t.guard).toEqual([{ atom: "command", negate: false }, { atom: "info_field_length_le_N1_and_content_is_octet_aligned", negate: false }, { atom: "va_le_nr_le_vs", negate: false }, { atom: "own_receiver_busy", negate: true }, { atom: "ns_eq_vr", negate: true }, { atom: "vr_lt_ns_lt_vr_plus_k", negate: false }, { atom: "reject_exception", negate: true }, { atom: "SREJ_enabled", negate: false }, { atom: "sreject_exception_gt_0", negate: true }, { atom: "ns_gt_vr_plus_1", negate: false }]);
    expect(t.actions).toHaveLength(8);
    expect(t.actions[0].verb).toBe("Check_I_Frame_Acknowledged");
    expect(t.actions[0].kind).toBe("subroutine");
    expect(t.actions[1].verb).toBe("Save Contents of I Frame");
    expect(t.actions[1].kind).toBe("processing");
    expect(t.actions[2].verb).toBe("Discard Contents of I Frame");
    expect(t.actions[2].kind).toBe("processing");
    expect(t.actions[3].verb).toBe("Set Reject Exception");
    expect(t.actions[3].kind).toBe("processing");
    expect(t.actions[4].verb).toBe("F := P");
    expect(t.actions[4].kind).toBe("processing");
    expect(t.actions[5].verb).toBe("N(r) := V(r)");
    expect(t.actions[5].kind).toBe("processing");
    expect(t.actions[6].verb).toBe("REJ");
    expect(t.actions[6].kind).toBe("signal_lower");
    expect(t.actions[7].verb).toBe("Clear Acknowledge Pending");
    expect(t.actions[7].kind).toBe("processing");
  });

  it("t26_i_received_yes_yes_yes_no_no_yes_no_yes_no_no", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t26_i_received_yes_yes_yes_no_no_yes_no_yes_no_no");
    expect(t, "transition t26_i_received_yes_yes_yes_no_no_yes_no_yes_no_no not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("I_received");
    expect(t.next).toBe("Connected");
    expect(t.guard).toEqual([{ atom: "command", negate: false }, { atom: "info_field_length_le_N1_and_content_is_octet_aligned", negate: false }, { atom: "va_le_nr_le_vs", negate: false }, { atom: "own_receiver_busy", negate: true }, { atom: "ns_eq_vr", negate: true }, { atom: "vr_lt_ns_lt_vr_plus_k", negate: false }, { atom: "reject_exception", negate: true }, { atom: "SREJ_enabled", negate: false }, { atom: "sreject_exception_gt_0", negate: true }, { atom: "ns_gt_vr_plus_1", negate: true }]);
    expect(t.actions).toHaveLength(6);
    expect(t.actions[0].verb).toBe("Check_I_Frame_Acknowledged");
    expect(t.actions[0].kind).toBe("subroutine");
    expect(t.actions[1].verb).toBe("Save Contents of I Frame");
    expect(t.actions[1].kind).toBe("processing");
    expect(t.actions[2].verb).toBe("N(r) := V(r)");
    expect(t.actions[2].kind).toBe("processing");
    expect(t.actions[3].verb).toBe("F := 1");
    expect(t.actions[3].kind).toBe("processing");
    expect(t.actions[4].verb).toBe("Increment Sreject Exception");
    expect(t.actions[4].kind).toBe("processing");
    expect(t.actions[5].verb).toBe("SREJ");
    expect(t.actions[5].kind).toBe("signal_lower");
  });

  it("t26_i_received_yes_yes_yes_no_no_no_yes", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t26_i_received_yes_yes_yes_no_no_no_yes");
    expect(t, "transition t26_i_received_yes_yes_yes_no_no_no_yes not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("I_received");
    expect(t.next).toBe("Connected");
    expect(t.guard).toEqual([{ atom: "command", negate: false }, { atom: "info_field_length_le_N1_and_content_is_octet_aligned", negate: false }, { atom: "va_le_nr_le_vs", negate: false }, { atom: "own_receiver_busy", negate: true }, { atom: "ns_eq_vr", negate: true }, { atom: "vr_lt_ns_lt_vr_plus_k", negate: true }, { atom: "P_eq_1", negate: false }]);
    expect(t.actions).toHaveLength(6);
    expect(t.actions[0].verb).toBe("Check_I_Frame_Acknowledged");
    expect(t.actions[0].kind).toBe("subroutine");
    expect(t.actions[1].verb).toBe("Discard Contents of I Frame");
    expect(t.actions[1].kind).toBe("processing");
    expect(t.actions[2].verb).toBe("F := 1");
    expect(t.actions[2].kind).toBe("processing");
    expect(t.actions[3].verb).toBe("N(r) := V(r)");
    expect(t.actions[3].kind).toBe("processing");
    expect(t.actions[4].verb).toBe("RR");
    expect(t.actions[4].kind).toBe("signal_lower");
    expect(t.actions[5].verb).toBe("Clear Acknowledge Pending");
    expect(t.actions[5].kind).toBe("processing");
  });

  it("t26_i_received_yes_yes_yes_no_no_no_no", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t26_i_received_yes_yes_yes_no_no_no_no");
    expect(t, "transition t26_i_received_yes_yes_yes_no_no_no_no not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("I_received");
    expect(t.next).toBe("Connected");
    expect(t.guard).toEqual([{ atom: "command", negate: false }, { atom: "info_field_length_le_N1_and_content_is_octet_aligned", negate: false }, { atom: "va_le_nr_le_vs", negate: false }, { atom: "own_receiver_busy", negate: true }, { atom: "ns_eq_vr", negate: true }, { atom: "vr_lt_ns_lt_vr_plus_k", negate: true }, { atom: "P_eq_1", negate: true }]);
    expect(t.actions).toHaveLength(2);
    expect(t.actions[0].verb).toBe("Check_I_Frame_Acknowledged");
    expect(t.actions[0].kind).toBe("subroutine");
    expect(t.actions[1].verb).toBe("Discard Contents of I Frame");
    expect(t.actions[1].kind).toBe("processing");
  });

  it("t26_i_received_yes_yes_yes_yes_yes", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t26_i_received_yes_yes_yes_yes_yes");
    expect(t, "transition t26_i_received_yes_yes_yes_yes_yes not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("I_received");
    expect(t.next).toBe("Connected");
    expect(t.guard).toEqual([{ atom: "command", negate: false }, { atom: "info_field_length_le_N1_and_content_is_octet_aligned", negate: false }, { atom: "va_le_nr_le_vs", negate: false }, { atom: "own_receiver_busy", negate: false }, { atom: "P_eq_1", negate: false }]);
    expect(t.actions).toHaveLength(6);
    expect(t.actions[0].verb).toBe("Check_I_Frame_Acknowledged");
    expect(t.actions[0].kind).toBe("subroutine");
    expect(t.actions[1].verb).toBe("Discard Contents of I Frame");
    expect(t.actions[1].kind).toBe("processing");
    expect(t.actions[2].verb).toBe("F := 1");
    expect(t.actions[2].kind).toBe("processing");
    expect(t.actions[3].verb).toBe("N(r) := V(r)");
    expect(t.actions[3].kind).toBe("processing");
    expect(t.actions[4].verb).toBe("RR");
    expect(t.actions[4].kind).toBe("signal_lower");
    expect(t.actions[5].verb).toBe("Clear Acknowledge Pending");
    expect(t.actions[5].kind).toBe("processing");
  });

  it("t26_i_received_yes_yes_yes_yes_no", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t26_i_received_yes_yes_yes_yes_no");
    expect(t, "transition t26_i_received_yes_yes_yes_yes_no not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("I_received");
    expect(t.next).toBe("Connected");
    expect(t.guard).toEqual([{ atom: "command", negate: false }, { atom: "info_field_length_le_N1_and_content_is_octet_aligned", negate: false }, { atom: "va_le_nr_le_vs", negate: false }, { atom: "own_receiver_busy", negate: false }, { atom: "P_eq_1", negate: true }]);
    expect(t.actions).toHaveLength(2);
    expect(t.actions[0].verb).toBe("Check_I_Frame_Acknowledged");
    expect(t.actions[0].kind).toBe("subroutine");
    expect(t.actions[1].verb).toBe("Discard Contents of I Frame");
    expect(t.actions[1].kind).toBe("processing");
  });

  it("t26_i_received_no", () => {
    const t = DataLinkConnected.transitions.find((x) => x.id === "t26_i_received_no");
    expect(t, "transition t26_i_received_no not found").toBeDefined();
    if (!t) return;
    expect(t.on).toBe("I_received");
    expect(t.next).toBe("Connected");
    expect(t.guard).toEqual([{ atom: "command", negate: true }]);
    expect(t.actions).toHaveLength(2);
    expect(t.actions[0].verb).toBe("DL-ERROR Indication (O)");
    expect(t.actions[0].kind).toBe("signal_upper");
    expect(t.actions[1].verb).toBe("Discard I Frame");
    expect(t.actions[1].kind).toBe("processing");
  });

});
