// Code generated by codegen/src/Packet.Sdl.CodeGen. DO NOT EDIT.
// The closed set generated from spec-sdl/predicates.yaml.

/// The closed set of canonical AX.25 SDL guard atoms (figc4.x decision
/// predicates), one variant per distinct predicate across every page +
/// subroutine. A transition's [`TransitionSpec::guard`](crate::TransitionSpec) is a
/// conjunction of these atoms (each optionally negated — see
/// [`GuardTerm`](crate::GuardTerm)); enumerating them lets a guard evaluator bind
/// every atom exhaustively.
#[derive(Debug, PartialEq, Eq, Clone, Copy, Hash)]
pub enum Ax25Guard {
    /// `F_eq_1`
    FEq1,
    /// `F_eq_1_and_frame_eq_RR_or_frame_eq_RNR_or_frame_eq_I`
    FEq1AndFrameEqRROrFrameEqRNROrFrameEqI,
    /// `P_eq_1`
    PEq1,
    /// `P_or_F_eq_1`
    POrFEq1,
    /// `RC_eq_0`
    RCEq0,
    /// `RC_eq_N2`
    RCEqN2,
    /// `RC_eq_NM201`
    RCEqNM201,
    /// `SREJ_enabled`
    SREJEnabled,
    /// `T1_expired`
    T1Expired,
    /// `T1_running`
    T1Running,
    /// `able_to_establish`
    AbleToEstablish,
    /// `ack_pending`
    AckPending,
    /// `command`
    Command,
    /// `command_and_P_eq_1`
    CommandAndPEq1,
    /// `info_field_length_le_N1_and_content_is_octet_aligned`
    InfoFieldLengthLeN1AndContentIsOctetAligned,
    /// `layer_3_initiated`
    Layer3Initiated,
    /// `mod_128`
    Mod128,
    /// `mod_8`
    Mod8,
    /// `nr_eq_va`
    NrEqVa,
    /// `nr_eq_vs`
    NrEqVs,
    /// `ns_eq_vr`
    NsEqVr,
    /// `ns_gt_vr_plus_1`
    NsGtVrPlus1,
    /// `out_of_sequence_frames_in_receive_buffer`
    OutOfSequenceFramesInReceiveBuffer,
    /// `own_receiver_busy`
    OwnReceiverBusy,
    /// `peer_receiver_busy`
    PeerReceiverBusy,
    /// `reject_exception`
    RejectException,
    /// `response`
    Response,
    /// `response_and_F_eq_1`
    ResponseAndFEq1,
    /// `sreject_exception_gt_0`
    SrejectExceptionGt0,
    /// `va_le_nr_le_vs`
    VaLeNrLeVs,
    /// `version_2_2`
    Version22,
    /// `vr_I_frame_stored`
    VrIFrameStored,
    /// `vr_lt_ns_lt_vr_plus_k`
    VrLtNsLtVrPlusK,
    /// `vs_eq_X`
    VsEqX,
    /// `vs_eq_nr`
    VsEqNr,
    /// `vs_eq_va`
    VsEqVa,
    /// `vs_eq_va_plus_k`
    VsEqVaPlusK,
}
