# Code generated by codegen/src/Packet.Sdl.CodeGen from spec-sdl/v2.2-errata/data-link/yaml/connected.sdl.yaml.
# DO NOT EDIT. Run `dotnet run --project codegen/src/Packet.Sdl.CodeGen` to regenerate.

from . import DATA_LINK_CONNECTED
from .types import ActionKind


def test_source_figure() -> None:
    assert DATA_LINK_CONNECTED.source.figure == "figc4.4"


def test_transitions_are_present() -> None:
    assert len(DATA_LINK_CONNECTED.transitions) == 68


def test_t01_dl_disconnect_request() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t01_dl_disconnect_request"),
        None,
    )
    assert t is not None, "transition t01_dl_disconnect_request not found"
    assert t.on == "DL_DISCONNECT_request"
    assert t.next == "AwaitingRelease"
    assert len(t.actions) == 5
    assert t.actions[0].verb == "discard_I_frame_queue"
    assert t.actions[0].kind == ActionKind.PROCESSING
    assert t.actions[1].verb == "RC := 0"
    assert t.actions[1].kind == ActionKind.PROCESSING
    assert t.actions[2].verb == "DISC (P = 1)"
    assert t.actions[2].kind == ActionKind.SIGNAL_LOWER
    assert t.actions[3].verb == "Stop T3"
    assert t.actions[3].kind == ActionKind.PROCESSING
    assert t.actions[4].verb == "Start T1"
    assert t.actions[4].kind == ActionKind.PROCESSING


def test_t02_dl_data_request() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t02_dl_data_request"),
        None,
    )
    assert t is not None, "transition t02_dl_data_request not found"
    assert t.on == "DL_DATA_request"
    assert t.next == "Connected"
    assert len(t.actions) == 1
    assert t.actions[0].verb == "Push on I Frame Queue (note: word order?)"
    assert t.actions[0].kind == ActionKind.INTERNAL_OUT


def test_t03_i_frame_pops_off_queue_yes() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t03_i_frame_pops_off_queue_yes"),
        None,
    )
    assert t is not None, "transition t03_i_frame_pops_off_queue_yes not found"
    assert t.on == "I_frame_pops_off_queue"
    assert t.next == "Connected"
    assert t.guard == "peer_receiver_busy"
    assert len(t.actions) == 1
    assert t.actions[0].verb == "Push on I Frame Queue"
    assert t.actions[0].kind == ActionKind.INTERNAL_OUT


def test_t03_i_frame_pops_off_queue_no_yes() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t03_i_frame_pops_off_queue_no_yes"),
        None,
    )
    assert t is not None, "transition t03_i_frame_pops_off_queue_no_yes not found"
    assert t.on == "I_frame_pops_off_queue"
    assert t.next == "Connected"
    assert t.guard == "not peer_receiver_busy and vs_eq_va_plus_k"
    assert len(t.actions) == 1
    assert t.actions[0].verb == "Push on I Frame Queue"
    assert t.actions[0].kind == ActionKind.INTERNAL_OUT


def test_t03_i_frame_pops_off_queue_no_no_no() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t03_i_frame_pops_off_queue_no_no_no"),
        None,
    )
    assert t is not None, "transition t03_i_frame_pops_off_queue_no_no_no not found"
    assert t.on == "I_frame_pops_off_queue"
    assert t.next == "Connected"
    assert t.guard == "not peer_receiver_busy and not vs_eq_va_plus_k and not T1_running"
    assert len(t.actions) == 8
    assert t.actions[0].verb == "N(s) := V(s)"
    assert t.actions[0].kind == ActionKind.PROCESSING
    assert t.actions[1].verb == "N(r) := V(r)"
    assert t.actions[1].kind == ActionKind.PROCESSING
    assert t.actions[2].verb == "P := 0"
    assert t.actions[2].kind == ActionKind.PROCESSING
    assert t.actions[3].verb == "I Command"
    assert t.actions[3].kind == ActionKind.SIGNAL_LOWER
    assert t.actions[4].verb == "V(s) := V(s) + 1"
    assert t.actions[4].kind == ActionKind.PROCESSING
    assert t.actions[5].verb == "Clear Acknowledge Pending"
    assert t.actions[5].kind == ActionKind.PROCESSING
    assert t.actions[6].verb == "Stop T3"
    assert t.actions[6].kind == ActionKind.PROCESSING
    assert t.actions[7].verb == "Start T1"
    assert t.actions[7].kind == ActionKind.PROCESSING


def test_t03_i_frame_pops_off_queue_no_no_yes() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t03_i_frame_pops_off_queue_no_no_yes"),
        None,
    )
    assert t is not None, "transition t03_i_frame_pops_off_queue_no_no_yes not found"
    assert t.on == "I_frame_pops_off_queue"
    assert t.next == "Connected"
    assert t.guard == "not peer_receiver_busy and not vs_eq_va_plus_k and T1_running"
    assert len(t.actions) == 6
    assert t.actions[0].verb == "N(s) := V(s)"
    assert t.actions[0].kind == ActionKind.PROCESSING
    assert t.actions[1].verb == "N(r) := V(r)"
    assert t.actions[1].kind == ActionKind.PROCESSING
    assert t.actions[2].verb == "P := 0"
    assert t.actions[2].kind == ActionKind.PROCESSING
    assert t.actions[3].verb == "I Command"
    assert t.actions[3].kind == ActionKind.SIGNAL_LOWER
    assert t.actions[4].verb == "V(s) := V(s) + 1"
    assert t.actions[4].kind == ActionKind.PROCESSING
    assert t.actions[5].verb == "Clear Acknowledge Pending"
    assert t.actions[5].kind == ActionKind.PROCESSING


def test_t04_dl_unit_data_request() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t04_dl_unit_data_request"),
        None,
    )
    assert t is not None, "transition t04_dl_unit_data_request not found"
    assert t.on == "DL_UNIT_DATA_request"
    assert t.next == "Connected"
    assert len(t.actions) == 1
    assert t.actions[0].verb == "UI Command"
    assert t.actions[0].kind == ActionKind.SIGNAL_LOWER


def test_t05_dl_flow_off_request_yes() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t05_dl_flow_off_request_yes"),
        None,
    )
    assert t is not None, "transition t05_dl_flow_off_request_yes not found"
    assert t.on == "DL_FLOW_OFF_request"
    assert t.next == "Connected"
    assert t.guard == "own_receiver_busy"
    assert len(t.actions) == 3
    assert t.actions[0].verb == "Set Own Receiver Busy"
    assert t.actions[0].kind == ActionKind.PROCESSING
    assert t.actions[1].verb == "RNR Response"
    assert t.actions[1].kind == ActionKind.SIGNAL_LOWER
    assert t.actions[2].verb == "Clear Acknowledge Pending"
    assert t.actions[2].kind == ActionKind.PROCESSING


def test_t05_dl_flow_off_request_no() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t05_dl_flow_off_request_no"),
        None,
    )
    assert t is not None, "transition t05_dl_flow_off_request_no not found"
    assert t.on == "DL_FLOW_OFF_request"
    assert t.next == "Connected"
    assert t.guard == "not own_receiver_busy"
    assert len(t.actions) == 0


def test_t06_dl_flow_on_request_no() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t06_dl_flow_on_request_no"),
        None,
    )
    assert t is not None, "transition t06_dl_flow_on_request_no not found"
    assert t.on == "DL_FLOW_ON_request"
    assert t.next == "Connected"
    assert t.guard == "not own_receiver_busy"
    assert len(t.actions) == 0


def test_t06_dl_flow_on_request_yes_yes() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t06_dl_flow_on_request_yes_yes"),
        None,
    )
    assert t is not None, "transition t06_dl_flow_on_request_yes_yes not found"
    assert t.on == "DL_FLOW_ON_request"
    assert t.next == "Connected"
    assert t.guard == "own_receiver_busy and T1_running"
    assert len(t.actions) == 3
    assert t.actions[0].verb == "Clear Own Receiver Busy"
    assert t.actions[0].kind == ActionKind.PROCESSING
    assert t.actions[1].verb == "RR Command"
    assert t.actions[1].kind == ActionKind.SIGNAL_LOWER
    assert t.actions[2].verb == "Clear Acknowledge Pending"
    assert t.actions[2].kind == ActionKind.PROCESSING


def test_t06_dl_flow_on_request_yes_no() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t06_dl_flow_on_request_yes_no"),
        None,
    )
    assert t is not None, "transition t06_dl_flow_on_request_yes_no not found"
    assert t.on == "DL_FLOW_ON_request"
    assert t.next == "Connected"
    assert t.guard == "own_receiver_busy and not T1_running"
    assert len(t.actions) == 5
    assert t.actions[0].verb == "Clear Own Receiver Busy"
    assert t.actions[0].kind == ActionKind.PROCESSING
    assert t.actions[1].verb == "RR Command"
    assert t.actions[1].kind == ActionKind.SIGNAL_LOWER
    assert t.actions[2].verb == "Clear Acknowledge Pending"
    assert t.actions[2].kind == ActionKind.PROCESSING
    assert t.actions[3].verb == "Stop T3"
    assert t.actions[3].kind == ActionKind.PROCESSING
    assert t.actions[4].verb == "Start T1"
    assert t.actions[4].kind == ActionKind.PROCESSING


def test_t07_dl_connect_request_no() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t07_dl_connect_request_no"),
        None,
    )
    assert t is not None, "transition t07_dl_connect_request_no not found"
    assert t.on == "DL_CONNECT_request"
    assert t.next == "AwaitingConnection"
    assert t.guard == "not version_2_2"
    assert len(t.actions) == 3
    assert t.actions[0].verb == "discard_I_frame_queue"
    assert t.actions[0].kind == ActionKind.PROCESSING
    assert t.actions[1].verb == "Establish_Data_Link"
    assert t.actions[1].kind == ActionKind.SUBROUTINE
    assert t.actions[2].verb == "Set Layer 3 Initiated"
    assert t.actions[2].kind == ActionKind.PROCESSING


def test_t07_dl_connect_request_yes() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t07_dl_connect_request_yes"),
        None,
    )
    assert t is not None, "transition t07_dl_connect_request_yes not found"
    assert t.on == "DL_CONNECT_request"
    assert t.next == "AwaitingV22Connection"
    assert t.guard == "version_2_2"
    assert len(t.actions) == 3
    assert t.actions[0].verb == "discard_I_frame_queue"
    assert t.actions[0].kind == ActionKind.PROCESSING
    assert t.actions[1].verb == "Establish_Data_Link"
    assert t.actions[1].kind == ActionKind.SUBROUTINE
    assert t.actions[2].verb == "Set Layer 3 Initiated"
    assert t.actions[2].kind == ActionKind.PROCESSING


def test_t08_all_other_primitives__from_upper_layer() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t08_all_other_primitives__from_upper_layer"),
        None,
    )
    assert t is not None, "transition t08_all_other_primitives__from_upper_layer not found"
    assert t.on == "all_other_primitives__from_upper_layer"
    assert t.next == "Connected"
    assert len(t.actions) == 0


def test_t09_control_field_error_no() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t09_control_field_error_no"),
        None,
    )
    assert t is not None, "transition t09_control_field_error_no not found"
    assert t.on == "control_field_error"
    assert t.next == "AwaitingConnection"
    assert t.guard == "not version_2_2"
    assert len(t.actions) == 4
    assert t.actions[0].verb == "DL-ERROR Indication (L)"
    assert t.actions[0].kind == ActionKind.SIGNAL_UPPER
    assert t.actions[1].verb == "discard_I_frame_queue"
    assert t.actions[1].kind == ActionKind.PROCESSING
    assert t.actions[2].verb == "Establish_Data_Link"
    assert t.actions[2].kind == ActionKind.SUBROUTINE
    assert t.actions[3].verb == "Set Layer 3 Initiated"
    assert t.actions[3].kind == ActionKind.PROCESSING


def test_t09_control_field_error_yes() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t09_control_field_error_yes"),
        None,
    )
    assert t is not None, "transition t09_control_field_error_yes not found"
    assert t.on == "control_field_error"
    assert t.next == "AwaitingV22Connection"
    assert t.guard == "version_2_2"
    assert len(t.actions) == 4
    assert t.actions[0].verb == "DL-ERROR Indication (L)"
    assert t.actions[0].kind == ActionKind.SIGNAL_UPPER
    assert t.actions[1].verb == "discard_I_frame_queue"
    assert t.actions[1].kind == ActionKind.PROCESSING
    assert t.actions[2].verb == "Establish_Data_Link"
    assert t.actions[2].kind == ActionKind.SUBROUTINE
    assert t.actions[3].verb == "Set Layer 3 Initiated"
    assert t.actions[3].kind == ActionKind.PROCESSING


def test_t10_info_not_permitted_in_frame_no() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t10_info_not_permitted_in_frame_no"),
        None,
    )
    assert t is not None, "transition t10_info_not_permitted_in_frame_no not found"
    assert t.on == "info_not_permitted_in_frame"
    assert t.next == "AwaitingConnection"
    assert t.guard == "not version_2_2"
    assert len(t.actions) == 4
    assert t.actions[0].verb == "DL-ERROR Indication (M)"
    assert t.actions[0].kind == ActionKind.SIGNAL_UPPER
    assert t.actions[1].verb == "discard_I_frame_queue"
    assert t.actions[1].kind == ActionKind.PROCESSING
    assert t.actions[2].verb == "Establish_Data_Link"
    assert t.actions[2].kind == ActionKind.SUBROUTINE
    assert t.actions[3].verb == "Set Layer 3 Initiated"
    assert t.actions[3].kind == ActionKind.PROCESSING


def test_t10_info_not_permitted_in_frame_yes() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t10_info_not_permitted_in_frame_yes"),
        None,
    )
    assert t is not None, "transition t10_info_not_permitted_in_frame_yes not found"
    assert t.on == "info_not_permitted_in_frame"
    assert t.next == "AwaitingV22Connection"
    assert t.guard == "version_2_2"
    assert len(t.actions) == 4
    assert t.actions[0].verb == "DL-ERROR Indication (M)"
    assert t.actions[0].kind == ActionKind.SIGNAL_UPPER
    assert t.actions[1].verb == "discard_I_frame_queue"
    assert t.actions[1].kind == ActionKind.PROCESSING
    assert t.actions[2].verb == "Establish_Data_Link"
    assert t.actions[2].kind == ActionKind.SUBROUTINE
    assert t.actions[3].verb == "Set Layer 3 Initiated"
    assert t.actions[3].kind == ActionKind.PROCESSING


def test_t11_u_or_s_frame_length_error_no() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t11_u_or_s_frame_length_error_no"),
        None,
    )
    assert t is not None, "transition t11_u_or_s_frame_length_error_no not found"
    assert t.on == "u_or_s_frame_length_error"
    assert t.next == "AwaitingConnection"
    assert t.guard == "not version_2_2"
    assert len(t.actions) == 4
    assert t.actions[0].verb == "DL-ERROR Indication (N)"
    assert t.actions[0].kind == ActionKind.SIGNAL_UPPER
    assert t.actions[1].verb == "discard_I_frame_queue"
    assert t.actions[1].kind == ActionKind.PROCESSING
    assert t.actions[2].verb == "Establish_Data_Link"
    assert t.actions[2].kind == ActionKind.SUBROUTINE
    assert t.actions[3].verb == "Set Layer 3 Initiated"
    assert t.actions[3].kind == ActionKind.PROCESSING


def test_t11_u_or_s_frame_length_error_yes() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t11_u_or_s_frame_length_error_yes"),
        None,
    )
    assert t is not None, "transition t11_u_or_s_frame_length_error_yes not found"
    assert t.on == "u_or_s_frame_length_error"
    assert t.next == "AwaitingV22Connection"
    assert t.guard == "version_2_2"
    assert len(t.actions) == 4
    assert t.actions[0].verb == "DL-ERROR Indication (N)"
    assert t.actions[0].kind == ActionKind.SIGNAL_UPPER
    assert t.actions[1].verb == "discard_I_frame_queue"
    assert t.actions[1].kind == ActionKind.PROCESSING
    assert t.actions[2].verb == "Establish_Data_Link"
    assert t.actions[2].kind == ActionKind.SUBROUTINE
    assert t.actions[3].verb == "Set Layer 3 Initiated"
    assert t.actions[3].kind == ActionKind.PROCESSING


def test_t12_t1_expiry() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t12_t1_expiry"),
        None,
    )
    assert t is not None, "transition t12_t1_expiry not found"
    assert t.on == "T1_expiry"
    assert t.next == "TimerRecovery"
    assert len(t.actions) == 2
    assert t.actions[0].verb == "RC := 1"
    assert t.actions[0].kind == ActionKind.PROCESSING
    assert t.actions[1].verb == "Transmit Enquery"
    assert t.actions[1].kind == ActionKind.SUBROUTINE


def test_t13_t3_expiry() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t13_t3_expiry"),
        None,
    )
    assert t is not None, "transition t13_t3_expiry not found"
    assert t.on == "T3_expiry"
    assert t.next == "TimerRecovery"
    assert len(t.actions) == 2
    assert t.actions[0].verb == "RC := 1"
    assert t.actions[0].kind == ActionKind.PROCESSING
    assert t.actions[1].verb == "Transmit Enquery"
    assert t.actions[1].kind == ActionKind.SUBROUTINE


def test_t14_sabm_received_yes() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t14_sabm_received_yes"),
        None,
    )
    assert t is not None, "transition t14_sabm_received_yes not found"
    assert t.on == "SABM_received"
    assert t.next == "Connected"
    assert t.guard == "vs_eq_va"
    assert len(t.actions) == 11
    assert t.actions[0].verb == "F := P"
    assert t.actions[0].kind == ActionKind.PROCESSING
    assert t.actions[1].verb == "set_version_2_0"
    assert t.actions[1].kind == ActionKind.PROCESSING
    assert t.actions[2].verb == "UA"
    assert t.actions[2].kind == ActionKind.SIGNAL_LOWER
    assert t.actions[3].verb == "Clear Exception Conditions"
    assert t.actions[3].kind == ActionKind.SUBROUTINE
    assert t.actions[4].verb == "DL-ERROR Indication (F)"
    assert t.actions[4].kind == ActionKind.SIGNAL_UPPER
    assert t.actions[5].verb == "Stop T1"
    assert t.actions[5].kind == ActionKind.PROCESSING
    assert t.actions[6].verb == "Start T3"
    assert t.actions[6].kind == ActionKind.PROCESSING
    assert t.actions[7].verb == "V(a) := 0"
    assert t.actions[7].kind == ActionKind.PROCESSING
    assert t.actions[8].verb == "V(s) := 0"
    assert t.actions[8].kind == ActionKind.PROCESSING
    assert t.actions[9].verb == "V(r) := 0"
    assert t.actions[9].kind == ActionKind.PROCESSING
    assert t.actions[10].verb == "RC := 0"
    assert t.actions[10].kind == ActionKind.PROCESSING


def test_t14_sabm_received_no() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t14_sabm_received_no"),
        None,
    )
    assert t is not None, "transition t14_sabm_received_no not found"
    assert t.on == "SABM_received"
    assert t.next == "Connected"
    assert t.guard == "not vs_eq_va"
    assert len(t.actions) == 13
    assert t.actions[0].verb == "F := P"
    assert t.actions[0].kind == ActionKind.PROCESSING
    assert t.actions[1].verb == "set_version_2_0"
    assert t.actions[1].kind == ActionKind.PROCESSING
    assert t.actions[2].verb == "UA"
    assert t.actions[2].kind == ActionKind.SIGNAL_LOWER
    assert t.actions[3].verb == "Clear Exception Conditions"
    assert t.actions[3].kind == ActionKind.SUBROUTINE
    assert t.actions[4].verb == "DL-ERROR Indication (F)"
    assert t.actions[4].kind == ActionKind.SIGNAL_UPPER
    assert t.actions[5].verb == "discard_I_frame_queue"
    assert t.actions[5].kind == ActionKind.PROCESSING
    assert t.actions[6].verb == "DL_CONNECT_indication"
    assert t.actions[6].kind == ActionKind.SIGNAL_UPPER
    assert t.actions[7].verb == "Stop T1"
    assert t.actions[7].kind == ActionKind.PROCESSING
    assert t.actions[8].verb == "Start T3"
    assert t.actions[8].kind == ActionKind.PROCESSING
    assert t.actions[9].verb == "V(a) := 0"
    assert t.actions[9].kind == ActionKind.PROCESSING
    assert t.actions[10].verb == "V(s) := 0"
    assert t.actions[10].kind == ActionKind.PROCESSING
    assert t.actions[11].verb == "V(r) := 0"
    assert t.actions[11].kind == ActionKind.PROCESSING
    assert t.actions[12].verb == "RC := 0"
    assert t.actions[12].kind == ActionKind.PROCESSING


def test_t15_sabme_received_yes() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t15_sabme_received_yes"),
        None,
    )
    assert t is not None, "transition t15_sabme_received_yes not found"
    assert t.on == "SABME_received"
    assert t.next == "Connected"
    assert t.guard == "vs_eq_va"
    assert len(t.actions) == 11
    assert t.actions[0].verb == "F := P"
    assert t.actions[0].kind == ActionKind.PROCESSING
    assert t.actions[1].verb == "Set Version 2.2"
    assert t.actions[1].kind == ActionKind.PROCESSING
    assert t.actions[2].verb == "UA"
    assert t.actions[2].kind == ActionKind.SIGNAL_LOWER
    assert t.actions[3].verb == "Clear Exception Conditions"
    assert t.actions[3].kind == ActionKind.SUBROUTINE
    assert t.actions[4].verb == "DL-ERROR Indication (F)"
    assert t.actions[4].kind == ActionKind.SIGNAL_UPPER
    assert t.actions[5].verb == "Stop T1"
    assert t.actions[5].kind == ActionKind.PROCESSING
    assert t.actions[6].verb == "Start T3"
    assert t.actions[6].kind == ActionKind.PROCESSING
    assert t.actions[7].verb == "V(a) := 0"
    assert t.actions[7].kind == ActionKind.PROCESSING
    assert t.actions[8].verb == "V(s) := 0"
    assert t.actions[8].kind == ActionKind.PROCESSING
    assert t.actions[9].verb == "V(r) := 0"
    assert t.actions[9].kind == ActionKind.PROCESSING
    assert t.actions[10].verb == "RC := 0"
    assert t.actions[10].kind == ActionKind.PROCESSING


def test_t15_sabme_received_no() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t15_sabme_received_no"),
        None,
    )
    assert t is not None, "transition t15_sabme_received_no not found"
    assert t.on == "SABME_received"
    assert t.next == "Connected"
    assert t.guard == "not vs_eq_va"
    assert len(t.actions) == 13
    assert t.actions[0].verb == "F := P"
    assert t.actions[0].kind == ActionKind.PROCESSING
    assert t.actions[1].verb == "Set Version 2.2"
    assert t.actions[1].kind == ActionKind.PROCESSING
    assert t.actions[2].verb == "UA"
    assert t.actions[2].kind == ActionKind.SIGNAL_LOWER
    assert t.actions[3].verb == "Clear Exception Conditions"
    assert t.actions[3].kind == ActionKind.SUBROUTINE
    assert t.actions[4].verb == "DL-ERROR Indication (F)"
    assert t.actions[4].kind == ActionKind.SIGNAL_UPPER
    assert t.actions[5].verb == "discard_I_frame_queue"
    assert t.actions[5].kind == ActionKind.PROCESSING
    assert t.actions[6].verb == "DL_CONNECT_indication"
    assert t.actions[6].kind == ActionKind.SIGNAL_UPPER
    assert t.actions[7].verb == "Stop T1"
    assert t.actions[7].kind == ActionKind.PROCESSING
    assert t.actions[8].verb == "Start T3"
    assert t.actions[8].kind == ActionKind.PROCESSING
    assert t.actions[9].verb == "V(a) := 0"
    assert t.actions[9].kind == ActionKind.PROCESSING
    assert t.actions[10].verb == "V(s) := 0"
    assert t.actions[10].kind == ActionKind.PROCESSING
    assert t.actions[11].verb == "V(r) := 0"
    assert t.actions[11].kind == ActionKind.PROCESSING
    assert t.actions[12].verb == "RC := 0"
    assert t.actions[12].kind == ActionKind.PROCESSING


def test_t16_frmr_received_no() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t16_frmr_received_no"),
        None,
    )
    assert t is not None, "transition t16_frmr_received_no not found"
    assert t.on == "FRMR_received"
    assert t.next == "AwaitingConnection"
    assert t.guard == "not version_2_2"
    assert len(t.actions) == 3
    assert t.actions[0].verb == "DL-ERROR Indication (K)"
    assert t.actions[0].kind == ActionKind.SIGNAL_UPPER
    assert t.actions[1].verb == "Establish_Data_Link"
    assert t.actions[1].kind == ActionKind.SUBROUTINE
    assert t.actions[2].verb == "Clear Layer 3 Initiated"
    assert t.actions[2].kind == ActionKind.PROCESSING


def test_t16_frmr_received_yes() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t16_frmr_received_yes"),
        None,
    )
    assert t is not None, "transition t16_frmr_received_yes not found"
    assert t.on == "FRMR_received"
    assert t.next == "AwaitingV22Connection"
    assert t.guard == "version_2_2"
    assert len(t.actions) == 3
    assert t.actions[0].verb == "DL-ERROR Indication (K)"
    assert t.actions[0].kind == ActionKind.SIGNAL_UPPER
    assert t.actions[1].verb == "Establish_Data_Link"
    assert t.actions[1].kind == ActionKind.SUBROUTINE
    assert t.actions[2].verb == "Clear Layer 3 Initiated"
    assert t.actions[2].kind == ActionKind.PROCESSING


def test_t17_ua_received_no() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t17_ua_received_no"),
        None,
    )
    assert t is not None, "transition t17_ua_received_no not found"
    assert t.on == "UA_received"
    assert t.next == "AwaitingConnection"
    assert t.guard == "not version_2_2"
    assert len(t.actions) == 3
    assert t.actions[0].verb == "DL-ERROR Indication (K)"
    assert t.actions[0].kind == ActionKind.SIGNAL_UPPER
    assert t.actions[1].verb == "Establish_Data_Link"
    assert t.actions[1].kind == ActionKind.SUBROUTINE
    assert t.actions[2].verb == "Clear Layer 3 Initiated"
    assert t.actions[2].kind == ActionKind.PROCESSING


def test_t17_ua_received_yes() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t17_ua_received_yes"),
        None,
    )
    assert t is not None, "transition t17_ua_received_yes not found"
    assert t.on == "UA_received"
    assert t.next == "AwaitingV22Connection"
    assert t.guard == "version_2_2"
    assert len(t.actions) == 3
    assert t.actions[0].verb == "DL-ERROR Indication (K)"
    assert t.actions[0].kind == ActionKind.SIGNAL_UPPER
    assert t.actions[1].verb == "Establish_Data_Link"
    assert t.actions[1].kind == ActionKind.SUBROUTINE
    assert t.actions[2].verb == "Clear Layer 3 Initiated"
    assert t.actions[2].kind == ActionKind.PROCESSING


def test_t18_ui_received_yes() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t18_ui_received_yes"),
        None,
    )
    assert t is not None, "transition t18_ui_received_yes not found"
    assert t.on == "UI_received"
    assert t.next == "Connected"
    assert t.guard == "P_eq_1"
    assert len(t.actions) == 2
    assert t.actions[0].verb == "UI Check"
    assert t.actions[0].kind == ActionKind.SUBROUTINE
    assert t.actions[1].verb == "Enquiry_Response_F_1"
    assert t.actions[1].kind == ActionKind.SUBROUTINE


def test_t18_ui_received_no() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t18_ui_received_no"),
        None,
    )
    assert t is not None, "transition t18_ui_received_no not found"
    assert t.on == "UI_received"
    assert t.next == "Connected"
    assert t.guard == "not P_eq_1"
    assert len(t.actions) == 1
    assert t.actions[0].verb == "UI Check"
    assert t.actions[0].kind == ActionKind.SUBROUTINE


def test_t19_disc_received() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t19_disc_received"),
        None,
    )
    assert t is not None, "transition t19_disc_received not found"
    assert t.on == "DISC_received"
    assert t.next == "Disconnected"
    assert len(t.actions) == 6
    assert t.actions[0].verb == "discard_I_frame_queue"
    assert t.actions[0].kind == ActionKind.PROCESSING
    assert t.actions[1].verb == "F := P"
    assert t.actions[1].kind == ActionKind.PROCESSING
    assert t.actions[2].verb == "UA"
    assert t.actions[2].kind == ActionKind.SIGNAL_LOWER
    assert t.actions[3].verb == "DL_DISCONNECT_indication"
    assert t.actions[3].kind == ActionKind.SIGNAL_UPPER
    assert t.actions[4].verb == "Stop T3"
    assert t.actions[4].kind == ActionKind.PROCESSING
    assert t.actions[5].verb == "Start T1"
    assert t.actions[5].kind == ActionKind.PROCESSING


def test_t20_dm_received() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t20_dm_received"),
        None,
    )
    assert t is not None, "transition t20_dm_received not found"
    assert t.on == "DM_received"
    assert t.next == "Disconnected"
    assert len(t.actions) == 5
    assert t.actions[0].verb == "DL-ERROR Indication (E)"
    assert t.actions[0].kind == ActionKind.SIGNAL_UPPER
    assert t.actions[1].verb == "DL_DISCONNECT_indication"
    assert t.actions[1].kind == ActionKind.SIGNAL_UPPER
    assert t.actions[2].verb == "discard_I_frame_queue"
    assert t.actions[2].kind == ActionKind.PROCESSING
    assert t.actions[3].verb == "Stop T1"
    assert t.actions[3].kind == ActionKind.PROCESSING
    assert t.actions[4].verb == "Stop T3"
    assert t.actions[4].kind == ActionKind.PROCESSING


def test_t21_rr_received_yes() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t21_rr_received_yes"),
        None,
    )
    assert t is not None, "transition t21_rr_received_yes not found"
    assert t.on == "RR_received"
    assert t.next == "Connected"
    assert t.guard == "va_le_nr_le_vs"
    assert len(t.actions) == 3
    assert t.actions[0].verb == "clear_peer_receiver_busy"
    assert t.actions[0].kind == ActionKind.PROCESSING
    assert t.actions[1].verb == "Check Need For Response"
    assert t.actions[1].kind == ActionKind.SUBROUTINE
    assert t.actions[2].verb == "Check_I_Frame_Acknowledged"
    assert t.actions[2].kind == ActionKind.SUBROUTINE


def test_t21_rr_received_no_no() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t21_rr_received_no_no"),
        None,
    )
    assert t is not None, "transition t21_rr_received_no_no not found"
    assert t.on == "RR_received"
    assert t.next == "AwaitingConnection"
    assert t.guard == "not va_le_nr_le_vs and not version_2_2"
    assert len(t.actions) == 3
    assert t.actions[0].verb == "clear_peer_receiver_busy"
    assert t.actions[0].kind == ActionKind.PROCESSING
    assert t.actions[1].verb == "Check Need For Response"
    assert t.actions[1].kind == ActionKind.SUBROUTINE
    assert t.actions[2].verb == "N(r) Error Recovery"
    assert t.actions[2].kind == ActionKind.SUBROUTINE


def test_t21_rr_received_no_yes() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t21_rr_received_no_yes"),
        None,
    )
    assert t is not None, "transition t21_rr_received_no_yes not found"
    assert t.on == "RR_received"
    assert t.next == "AwaitingV22Connection"
    assert t.guard == "not va_le_nr_le_vs and version_2_2"
    assert len(t.actions) == 3
    assert t.actions[0].verb == "clear_peer_receiver_busy"
    assert t.actions[0].kind == ActionKind.PROCESSING
    assert t.actions[1].verb == "Check Need For Response"
    assert t.actions[1].kind == ActionKind.SUBROUTINE
    assert t.actions[2].verb == "N(r) Error Recovery"
    assert t.actions[2].kind == ActionKind.SUBROUTINE


def test_t22_rnr_received_yes() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t22_rnr_received_yes"),
        None,
    )
    assert t is not None, "transition t22_rnr_received_yes not found"
    assert t.on == "RNR_received"
    assert t.next == "Connected"
    assert t.guard == "va_le_nr_le_vs"
    assert len(t.actions) == 3
    assert t.actions[0].verb == "set_peer_receiver_busy"
    assert t.actions[0].kind == ActionKind.PROCESSING
    assert t.actions[1].verb == "Check Need For Response"
    assert t.actions[1].kind == ActionKind.SUBROUTINE
    assert t.actions[2].verb == "Check_I_Frame_Acknowledged"
    assert t.actions[2].kind == ActionKind.SUBROUTINE


def test_t22_rnr_received_no_no() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t22_rnr_received_no_no"),
        None,
    )
    assert t is not None, "transition t22_rnr_received_no_no not found"
    assert t.on == "RNR_received"
    assert t.next == "AwaitingConnection"
    assert t.guard == "not va_le_nr_le_vs and not version_2_2"
    assert len(t.actions) == 3
    assert t.actions[0].verb == "set_peer_receiver_busy"
    assert t.actions[0].kind == ActionKind.PROCESSING
    assert t.actions[1].verb == "Check Need For Response"
    assert t.actions[1].kind == ActionKind.SUBROUTINE
    assert t.actions[2].verb == "N(r) Error Recovery"
    assert t.actions[2].kind == ActionKind.SUBROUTINE


def test_t22_rnr_received_no_yes() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t22_rnr_received_no_yes"),
        None,
    )
    assert t is not None, "transition t22_rnr_received_no_yes not found"
    assert t.on == "RNR_received"
    assert t.next == "AwaitingV22Connection"
    assert t.guard == "not va_le_nr_le_vs and version_2_2"
    assert len(t.actions) == 3
    assert t.actions[0].verb == "set_peer_receiver_busy"
    assert t.actions[0].kind == ActionKind.PROCESSING
    assert t.actions[1].verb == "Check Need For Response"
    assert t.actions[1].kind == ActionKind.SUBROUTINE
    assert t.actions[2].verb == "N(r) Error Recovery"
    assert t.actions[2].kind == ActionKind.SUBROUTINE


def test_t23_lm_seize_confirm_yes() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t23_lm_seize_confirm_yes"),
        None,
    )
    assert t is not None, "transition t23_lm_seize_confirm_yes not found"
    assert t.on == "LM_SEIZE_confirm"
    assert t.next == "Connected"
    assert t.guard == "ack_pending"
    assert len(t.actions) == 3
    assert t.actions[0].verb == "Clear Acknowledge Pending"
    assert t.actions[0].kind == ActionKind.PROCESSING
    assert t.actions[1].verb == "Enquiry Response (F = 0)"
    assert t.actions[1].kind == ActionKind.SUBROUTINE
    assert t.actions[2].verb == "LM_release_request"
    assert t.actions[2].kind == ActionKind.SIGNAL_LOWER


def test_t23_lm_seize_confirm_no() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t23_lm_seize_confirm_no"),
        None,
    )
    assert t is not None, "transition t23_lm_seize_confirm_no not found"
    assert t.on == "LM_SEIZE_confirm"
    assert t.next == "Connected"
    assert t.guard == "not ack_pending"
    assert len(t.actions) == 1
    assert t.actions[0].verb == "LM_release_request"
    assert t.actions[0].kind == ActionKind.SIGNAL_LOWER


def test_t24_srej_received_yes_yes() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t24_srej_received_yes_yes"),
        None,
    )
    assert t is not None, "transition t24_srej_received_yes_yes not found"
    assert t.on == "SREJ_received"
    assert t.next == "Connected"
    assert t.guard == "va_le_nr_le_vs and P_or_F_eq_1"
    assert len(t.actions) == 11
    assert t.actions[0].verb == "clear_peer_receiver_busy"
    assert t.actions[0].kind == ActionKind.PROCESSING
    assert t.actions[1].verb == "Check Need For Response"
    assert t.actions[1].kind == ActionKind.SUBROUTINE
    assert t.actions[2].verb == "V(a) := N(r)"
    assert t.actions[2].kind == ActionKind.PROCESSING
    assert t.actions[3].verb == "Stop T1"
    assert t.actions[3].kind == ActionKind.PROCESSING
    assert t.actions[4].verb == "Start T3"
    assert t.actions[4].kind == ActionKind.PROCESSING
    assert t.actions[5].verb == "Select_T1_Value"
    assert t.actions[5].kind == ActionKind.SUBROUTINE
    assert t.actions[6].verb == "Push Old I Frame N(r) on Queue"
    assert t.actions[6].kind == ActionKind.INTERNAL_OUT
    assert t.actions[7].verb == "LM_data_request"
    assert t.actions[7].kind == ActionKind.SIGNAL_LOWER
    assert t.actions[8].verb == "Stop T3"
    assert t.actions[8].kind == ActionKind.PROCESSING
    assert t.actions[9].verb == "Start T1"
    assert t.actions[9].kind == ActionKind.PROCESSING
    assert t.actions[10].verb == "Clear Acknowledge Pending"
    assert t.actions[10].kind == ActionKind.PROCESSING


def test_t24_srej_received_yes_no() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t24_srej_received_yes_no"),
        None,
    )
    assert t is not None, "transition t24_srej_received_yes_no not found"
    assert t.on == "SREJ_received"
    assert t.next == "Connected"
    assert t.guard == "va_le_nr_le_vs and not P_or_F_eq_1"
    assert len(t.actions) == 10
    assert t.actions[0].verb == "clear_peer_receiver_busy"
    assert t.actions[0].kind == ActionKind.PROCESSING
    assert t.actions[1].verb == "Check Need For Response"
    assert t.actions[1].kind == ActionKind.SUBROUTINE
    assert t.actions[2].verb == "Stop T1"
    assert t.actions[2].kind == ActionKind.PROCESSING
    assert t.actions[3].verb == "Start T3"
    assert t.actions[3].kind == ActionKind.PROCESSING
    assert t.actions[4].verb == "Select_T1_Value"
    assert t.actions[4].kind == ActionKind.SUBROUTINE
    assert t.actions[5].verb == "Push Old I Frame N(r) on Queue"
    assert t.actions[5].kind == ActionKind.INTERNAL_OUT
    assert t.actions[6].verb == "LM_data_request"
    assert t.actions[6].kind == ActionKind.SIGNAL_LOWER
    assert t.actions[7].verb == "Stop T3"
    assert t.actions[7].kind == ActionKind.PROCESSING
    assert t.actions[8].verb == "Start T1"
    assert t.actions[8].kind == ActionKind.PROCESSING
    assert t.actions[9].verb == "Clear Acknowledge Pending"
    assert t.actions[9].kind == ActionKind.PROCESSING


def test_t24_srej_received_no_no() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t24_srej_received_no_no"),
        None,
    )
    assert t is not None, "transition t24_srej_received_no_no not found"
    assert t.on == "SREJ_received"
    assert t.next == "AwaitingConnection"
    assert t.guard == "not va_le_nr_le_vs and not version_2_2"
    assert len(t.actions) == 3
    assert t.actions[0].verb == "clear_peer_receiver_busy"
    assert t.actions[0].kind == ActionKind.PROCESSING
    assert t.actions[1].verb == "Check Need For Response"
    assert t.actions[1].kind == ActionKind.SUBROUTINE
    assert t.actions[2].verb == "N(r) Error Recovery"
    assert t.actions[2].kind == ActionKind.SUBROUTINE


def test_t24_srej_received_no_yes() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t24_srej_received_no_yes"),
        None,
    )
    assert t is not None, "transition t24_srej_received_no_yes not found"
    assert t.on == "SREJ_received"
    assert t.next == "AwaitingV22Connection"
    assert t.guard == "not va_le_nr_le_vs and version_2_2"
    assert len(t.actions) == 3
    assert t.actions[0].verb == "clear_peer_receiver_busy"
    assert t.actions[0].kind == ActionKind.PROCESSING
    assert t.actions[1].verb == "Check Need For Response"
    assert t.actions[1].kind == ActionKind.SUBROUTINE
    assert t.actions[2].verb == "N(r) Error Recovery"
    assert t.actions[2].kind == ActionKind.SUBROUTINE


def test_t25_rej_received_no_no() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t25_rej_received_no_no"),
        None,
    )
    assert t is not None, "transition t25_rej_received_no_no not found"
    assert t.on == "REJ_received"
    assert t.next == "AwaitingConnection"
    assert t.guard == "not va_le_nr_le_vs and not version_2_2"
    assert len(t.actions) == 3
    assert t.actions[0].verb == "clear_peer_receiver_busy"
    assert t.actions[0].kind == ActionKind.PROCESSING
    assert t.actions[1].verb == "Check Need For Response"
    assert t.actions[1].kind == ActionKind.SUBROUTINE
    assert t.actions[2].verb == "N(r) Error Recovery"
    assert t.actions[2].kind == ActionKind.SUBROUTINE


def test_t25_rej_received_no_yes() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t25_rej_received_no_yes"),
        None,
    )
    assert t is not None, "transition t25_rej_received_no_yes not found"
    assert t.on == "REJ_received"
    assert t.next == "AwaitingV22Connection"
    assert t.guard == "not va_le_nr_le_vs and version_2_2"
    assert len(t.actions) == 3
    assert t.actions[0].verb == "clear_peer_receiver_busy"
    assert t.actions[0].kind == ActionKind.PROCESSING
    assert t.actions[1].verb == "Check Need For Response"
    assert t.actions[1].kind == ActionKind.SUBROUTINE
    assert t.actions[2].verb == "N(r) Error Recovery"
    assert t.actions[2].kind == ActionKind.SUBROUTINE


def test_t25_rej_received_yes() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t25_rej_received_yes"),
        None,
    )
    assert t is not None, "transition t25_rej_received_yes not found"
    assert t.on == "REJ_received"
    assert t.next == "Connected"
    assert t.guard == "va_le_nr_le_vs"
    assert len(t.actions) == 8
    assert t.actions[0].verb == "clear_peer_receiver_busy"
    assert t.actions[0].kind == ActionKind.PROCESSING
    assert t.actions[1].verb == "Check Need For Response"
    assert t.actions[1].kind == ActionKind.SUBROUTINE
    assert t.actions[2].verb == "V(a) := N(r)"
    assert t.actions[2].kind == ActionKind.PROCESSING
    assert t.actions[3].verb == "Start T1"
    assert t.actions[3].kind == ActionKind.PROCESSING
    assert t.actions[4].verb == "Stop T3"
    assert t.actions[4].kind == ActionKind.PROCESSING
    assert t.actions[5].verb == "Clear Acknowledge Pending"
    assert t.actions[5].kind == ActionKind.PROCESSING
    assert t.actions[6].verb == "Select_T1_Value"
    assert t.actions[6].kind == ActionKind.SUBROUTINE
    assert t.actions[7].verb == "Invoke Retransmission"
    assert t.actions[7].kind == ActionKind.SUBROUTINE


def test_t26_i_received_yes_no_no() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t26_i_received_yes_no_no"),
        None,
    )
    assert t is not None, "transition t26_i_received_yes_no_no not found"
    assert t.on == "I_received"
    assert t.next == "AwaitingConnection"
    assert t.guard == "command and not info_field_length_le_N1_and_content_is_octet_aligned and not version_2_2"
    assert len(t.actions) == 3
    assert t.actions[0].verb == "DL-ERROR Indication (O)"
    assert t.actions[0].kind == ActionKind.SIGNAL_UPPER
    assert t.actions[1].verb == "Establish_Data_Link"
    assert t.actions[1].kind == ActionKind.SUBROUTINE
    assert t.actions[2].verb == "Clear Layer 3 Initiated"
    assert t.actions[2].kind == ActionKind.PROCESSING


def test_t26_i_received_yes_no_yes() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t26_i_received_yes_no_yes"),
        None,
    )
    assert t is not None, "transition t26_i_received_yes_no_yes not found"
    assert t.on == "I_received"
    assert t.next == "AwaitingV22Connection"
    assert t.guard == "command and not info_field_length_le_N1_and_content_is_octet_aligned and version_2_2"
    assert len(t.actions) == 3
    assert t.actions[0].verb == "DL-ERROR Indication (O)"
    assert t.actions[0].kind == ActionKind.SIGNAL_UPPER
    assert t.actions[1].verb == "Establish_Data_Link"
    assert t.actions[1].kind == ActionKind.SUBROUTINE
    assert t.actions[2].verb == "Clear Layer 3 Initiated"
    assert t.actions[2].kind == ActionKind.PROCESSING


def test_t26_i_received_yes_yes_no_no() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t26_i_received_yes_yes_no_no"),
        None,
    )
    assert t is not None, "transition t26_i_received_yes_yes_no_no not found"
    assert t.on == "I_received"
    assert t.next == "AwaitingConnection"
    assert t.guard == "command and info_field_length_le_N1_and_content_is_octet_aligned and not va_le_nr_le_vs and not version_2_2"
    assert len(t.actions) == 1
    assert t.actions[0].verb == "N(r) Error Recovery"
    assert t.actions[0].kind == ActionKind.SUBROUTINE


def test_t26_i_received_yes_yes_no_yes() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t26_i_received_yes_yes_no_yes"),
        None,
    )
    assert t is not None, "transition t26_i_received_yes_yes_no_yes not found"
    assert t.on == "I_received"
    assert t.next == "AwaitingV22Connection"
    assert t.guard == "command and info_field_length_le_N1_and_content_is_octet_aligned and not va_le_nr_le_vs and version_2_2"
    assert len(t.actions) == 1
    assert t.actions[0].verb == "N(r) Error Recovery"
    assert t.actions[0].kind == ActionKind.SUBROUTINE


def test_t26_i_received_yes_yes_yes_no_yes_no_no() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t26_i_received_yes_yes_yes_no_yes_no_no"),
        None,
    )
    assert t is not None, "transition t26_i_received_yes_yes_yes_no_yes_no_no not found"
    assert t.on == "I_received"
    assert t.next == "Connected"
    assert t.guard == "command and info_field_length_le_N1_and_content_is_octet_aligned and va_le_nr_le_vs and not own_receiver_busy and ns_eq_vr and not P_eq_1 and not ack_pending"
    assert len(t.actions) == 10
    assert t.actions[0].verb == "Check_I_Frame_Acknowledged"
    assert t.actions[0].kind == ActionKind.SUBROUTINE
    assert t.actions[1].verb == "V(r) := V(r) + 1"
    assert t.actions[1].kind == ActionKind.PROCESSING
    assert t.actions[2].verb == "Clear Reject Exception"
    assert t.actions[2].kind == ActionKind.PROCESSING
    assert t.actions[3].verb == "Decrement Sreject Exception if > 0"
    assert t.actions[3].kind == ActionKind.PROCESSING
    assert t.actions[4].verb == "DL_DATA_indication"
    assert t.actions[4].kind == ActionKind.SIGNAL_UPPER
    assert t.actions[5].verb == "Retrieve Stored V(r) I Frame"
    assert t.actions[5].kind == ActionKind.PROCESSING
    assert t.actions[6].verb == "DL_DATA_indication"
    assert t.actions[6].kind == ActionKind.SIGNAL_UPPER
    assert t.actions[7].verb == "V(r) := V(r) + 1"
    assert t.actions[7].kind == ActionKind.PROCESSING
    assert t.actions[8].verb == "LM_seize_request"
    assert t.actions[8].kind == ActionKind.SIGNAL_LOWER
    assert t.actions[9].verb == "set_acknowledge_pending"
    assert t.actions[9].kind == ActionKind.PROCESSING


def test_t26_i_received_yes_yes_yes_no_yes_no_yes() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t26_i_received_yes_yes_yes_no_yes_no_yes"),
        None,
    )
    assert t is not None, "transition t26_i_received_yes_yes_yes_no_yes_no_yes not found"
    assert t.on == "I_received"
    assert t.next == "Connected"
    assert t.guard == "command and info_field_length_le_N1_and_content_is_octet_aligned and va_le_nr_le_vs and not own_receiver_busy and ns_eq_vr and not P_eq_1 and ack_pending"
    assert len(t.actions) == 8
    assert t.actions[0].verb == "Check_I_Frame_Acknowledged"
    assert t.actions[0].kind == ActionKind.SUBROUTINE
    assert t.actions[1].verb == "V(r) := V(r) + 1"
    assert t.actions[1].kind == ActionKind.PROCESSING
    assert t.actions[2].verb == "Clear Reject Exception"
    assert t.actions[2].kind == ActionKind.PROCESSING
    assert t.actions[3].verb == "Decrement Sreject Exception if > 0"
    assert t.actions[3].kind == ActionKind.PROCESSING
    assert t.actions[4].verb == "DL_DATA_indication"
    assert t.actions[4].kind == ActionKind.SIGNAL_UPPER
    assert t.actions[5].verb == "Retrieve Stored V(r) I Frame"
    assert t.actions[5].kind == ActionKind.PROCESSING
    assert t.actions[6].verb == "DL_DATA_indication"
    assert t.actions[6].kind == ActionKind.SIGNAL_UPPER
    assert t.actions[7].verb == "V(r) := V(r) + 1"
    assert t.actions[7].kind == ActionKind.PROCESSING


def test_t26_i_received_yes_yes_yes_no_yes_yes() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t26_i_received_yes_yes_yes_no_yes_yes"),
        None,
    )
    assert t is not None, "transition t26_i_received_yes_yes_yes_no_yes_yes not found"
    assert t.on == "I_received"
    assert t.next == "Connected"
    assert t.guard == "command and info_field_length_le_N1_and_content_is_octet_aligned and va_le_nr_le_vs and not own_receiver_busy and ns_eq_vr and P_eq_1"
    assert len(t.actions) == 12
    assert t.actions[0].verb == "Check_I_Frame_Acknowledged"
    assert t.actions[0].kind == ActionKind.SUBROUTINE
    assert t.actions[1].verb == "V(r) := V(r) + 1"
    assert t.actions[1].kind == ActionKind.PROCESSING
    assert t.actions[2].verb == "Clear Reject Exception"
    assert t.actions[2].kind == ActionKind.PROCESSING
    assert t.actions[3].verb == "Decrement Sreject Exception if > 0"
    assert t.actions[3].kind == ActionKind.PROCESSING
    assert t.actions[4].verb == "DL_DATA_indication"
    assert t.actions[4].kind == ActionKind.SIGNAL_UPPER
    assert t.actions[5].verb == "Retrieve Stored V(r) I Frame"
    assert t.actions[5].kind == ActionKind.PROCESSING
    assert t.actions[6].verb == "DL_DATA_indication"
    assert t.actions[6].kind == ActionKind.SIGNAL_UPPER
    assert t.actions[7].verb == "V(r) := V(r) + 1"
    assert t.actions[7].kind == ActionKind.PROCESSING
    assert t.actions[8].verb == "F := 1"
    assert t.actions[8].kind == ActionKind.PROCESSING
    assert t.actions[9].verb == "N(r) := V(r)"
    assert t.actions[9].kind == ActionKind.PROCESSING
    assert t.actions[10].verb == "RR"
    assert t.actions[10].kind == ActionKind.SIGNAL_LOWER
    assert t.actions[11].verb == "Clear Acknowledge Pending"
    assert t.actions[11].kind == ActionKind.PROCESSING


def test_t26_i_received_yes_yes_yes_no_no_yes_yes_yes() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t26_i_received_yes_yes_yes_no_no_yes_yes_yes"),
        None,
    )
    assert t is not None, "transition t26_i_received_yes_yes_yes_no_no_yes_yes_yes not found"
    assert t.on == "I_received"
    assert t.next == "Connected"
    assert t.guard == "command and info_field_length_le_N1_and_content_is_octet_aligned and va_le_nr_le_vs and not own_receiver_busy and not ns_eq_vr and vr_lt_ns_lt_vr_plus_k and reject_exception and P_eq_1"
    assert len(t.actions) == 6
    assert t.actions[0].verb == "Check_I_Frame_Acknowledged"
    assert t.actions[0].kind == ActionKind.SUBROUTINE
    assert t.actions[1].verb == "Discard Contents of I Frame"
    assert t.actions[1].kind == ActionKind.PROCESSING
    assert t.actions[2].verb == "F := 1"
    assert t.actions[2].kind == ActionKind.PROCESSING
    assert t.actions[3].verb == "N(r) := V(r)"
    assert t.actions[3].kind == ActionKind.PROCESSING
    assert t.actions[4].verb == "RR"
    assert t.actions[4].kind == ActionKind.SIGNAL_LOWER
    assert t.actions[5].verb == "Clear Acknowledge Pending"
    assert t.actions[5].kind == ActionKind.PROCESSING


def test_t26_i_received_yes_yes_yes_no_no_yes_yes_no() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t26_i_received_yes_yes_yes_no_no_yes_yes_no"),
        None,
    )
    assert t is not None, "transition t26_i_received_yes_yes_yes_no_no_yes_yes_no not found"
    assert t.on == "I_received"
    assert t.next == "Connected"
    assert t.guard == "command and info_field_length_le_N1_and_content_is_octet_aligned and va_le_nr_le_vs and not own_receiver_busy and not ns_eq_vr and vr_lt_ns_lt_vr_plus_k and reject_exception and not P_eq_1"
    assert len(t.actions) == 2
    assert t.actions[0].verb == "Check_I_Frame_Acknowledged"
    assert t.actions[0].kind == ActionKind.SUBROUTINE
    assert t.actions[1].verb == "Discard Contents of I Frame"
    assert t.actions[1].kind == ActionKind.PROCESSING


def test_t26_i_received_yes_yes_yes_no_no_yes_no_no() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t26_i_received_yes_yes_yes_no_no_yes_no_no"),
        None,
    )
    assert t is not None, "transition t26_i_received_yes_yes_yes_no_no_yes_no_no not found"
    assert t.on == "I_received"
    assert t.next == "Connected"
    assert t.guard == "command and info_field_length_le_N1_and_content_is_octet_aligned and va_le_nr_le_vs and not own_receiver_busy and not ns_eq_vr and vr_lt_ns_lt_vr_plus_k and not reject_exception and not SREJ_enabled"
    assert len(t.actions) == 7
    assert t.actions[0].verb == "Check_I_Frame_Acknowledged"
    assert t.actions[0].kind == ActionKind.SUBROUTINE
    assert t.actions[1].verb == "Discard Contents of I Frame"
    assert t.actions[1].kind == ActionKind.PROCESSING
    assert t.actions[2].verb == "Set Reject Exception"
    assert t.actions[2].kind == ActionKind.PROCESSING
    assert t.actions[3].verb == "F := P"
    assert t.actions[3].kind == ActionKind.PROCESSING
    assert t.actions[4].verb == "N(r) := V(r)"
    assert t.actions[4].kind == ActionKind.PROCESSING
    assert t.actions[5].verb == "REJ"
    assert t.actions[5].kind == ActionKind.SIGNAL_LOWER
    assert t.actions[6].verb == "Clear Acknowledge Pending"
    assert t.actions[6].kind == ActionKind.PROCESSING


def test_t26_i_received_yes_yes_yes_no_no_yes_no_yes_yes() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t26_i_received_yes_yes_yes_no_no_yes_no_yes_yes"),
        None,
    )
    assert t is not None, "transition t26_i_received_yes_yes_yes_no_no_yes_no_yes_yes not found"
    assert t.on == "I_received"
    assert t.next == "Connected"
    assert t.guard == "command and info_field_length_le_N1_and_content_is_octet_aligned and va_le_nr_le_vs and not own_receiver_busy and not ns_eq_vr and vr_lt_ns_lt_vr_plus_k and not reject_exception and SREJ_enabled and sreject_exception_gt_0"
    assert len(t.actions) == 6
    assert t.actions[0].verb == "Check_I_Frame_Acknowledged"
    assert t.actions[0].kind == ActionKind.SUBROUTINE
    assert t.actions[1].verb == "Save Contents of I Frame"
    assert t.actions[1].kind == ActionKind.PROCESSING
    assert t.actions[2].verb == "N(r) := N(s)"
    assert t.actions[2].kind == ActionKind.PROCESSING
    assert t.actions[3].verb == "F := 0"
    assert t.actions[3].kind == ActionKind.PROCESSING
    assert t.actions[4].verb == "Increment Sreject Exception"
    assert t.actions[4].kind == ActionKind.PROCESSING
    assert t.actions[5].verb == "SREJ"
    assert t.actions[5].kind == ActionKind.SIGNAL_LOWER


def test_t26_i_received_yes_yes_yes_no_no_yes_no_yes_no_yes() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t26_i_received_yes_yes_yes_no_no_yes_no_yes_no_yes"),
        None,
    )
    assert t is not None, "transition t26_i_received_yes_yes_yes_no_no_yes_no_yes_no_yes not found"
    assert t.on == "I_received"
    assert t.next == "Connected"
    assert t.guard == "command and info_field_length_le_N1_and_content_is_octet_aligned and va_le_nr_le_vs and not own_receiver_busy and not ns_eq_vr and vr_lt_ns_lt_vr_plus_k and not reject_exception and SREJ_enabled and not sreject_exception_gt_0 and ns_gt_vr_plus_1"
    assert len(t.actions) == 8
    assert t.actions[0].verb == "Check_I_Frame_Acknowledged"
    assert t.actions[0].kind == ActionKind.SUBROUTINE
    assert t.actions[1].verb == "Save Contents of I Frame"
    assert t.actions[1].kind == ActionKind.PROCESSING
    assert t.actions[2].verb == "Discard Contents of I Frame"
    assert t.actions[2].kind == ActionKind.PROCESSING
    assert t.actions[3].verb == "Set Reject Exception"
    assert t.actions[3].kind == ActionKind.PROCESSING
    assert t.actions[4].verb == "F := P"
    assert t.actions[4].kind == ActionKind.PROCESSING
    assert t.actions[5].verb == "N(r) := V(r)"
    assert t.actions[5].kind == ActionKind.PROCESSING
    assert t.actions[6].verb == "REJ"
    assert t.actions[6].kind == ActionKind.SIGNAL_LOWER
    assert t.actions[7].verb == "Clear Acknowledge Pending"
    assert t.actions[7].kind == ActionKind.PROCESSING


def test_t26_i_received_yes_yes_yes_no_no_yes_no_yes_no_no() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t26_i_received_yes_yes_yes_no_no_yes_no_yes_no_no"),
        None,
    )
    assert t is not None, "transition t26_i_received_yes_yes_yes_no_no_yes_no_yes_no_no not found"
    assert t.on == "I_received"
    assert t.next == "Connected"
    assert t.guard == "command and info_field_length_le_N1_and_content_is_octet_aligned and va_le_nr_le_vs and not own_receiver_busy and not ns_eq_vr and vr_lt_ns_lt_vr_plus_k and not reject_exception and SREJ_enabled and not sreject_exception_gt_0 and not ns_gt_vr_plus_1"
    assert len(t.actions) == 6
    assert t.actions[0].verb == "Check_I_Frame_Acknowledged"
    assert t.actions[0].kind == ActionKind.SUBROUTINE
    assert t.actions[1].verb == "Save Contents of I Frame"
    assert t.actions[1].kind == ActionKind.PROCESSING
    assert t.actions[2].verb == "N(r) := V(r)"
    assert t.actions[2].kind == ActionKind.PROCESSING
    assert t.actions[3].verb == "F := 1"
    assert t.actions[3].kind == ActionKind.PROCESSING
    assert t.actions[4].verb == "Increment Sreject Exception"
    assert t.actions[4].kind == ActionKind.PROCESSING
    assert t.actions[5].verb == "SREJ"
    assert t.actions[5].kind == ActionKind.SIGNAL_LOWER


def test_t26_i_received_yes_yes_yes_no_no_no_yes() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t26_i_received_yes_yes_yes_no_no_no_yes"),
        None,
    )
    assert t is not None, "transition t26_i_received_yes_yes_yes_no_no_no_yes not found"
    assert t.on == "I_received"
    assert t.next == "Connected"
    assert t.guard == "command and info_field_length_le_N1_and_content_is_octet_aligned and va_le_nr_le_vs and not own_receiver_busy and not ns_eq_vr and not vr_lt_ns_lt_vr_plus_k and P_eq_1"
    assert len(t.actions) == 6
    assert t.actions[0].verb == "Check_I_Frame_Acknowledged"
    assert t.actions[0].kind == ActionKind.SUBROUTINE
    assert t.actions[1].verb == "Discard Contents of I Frame"
    assert t.actions[1].kind == ActionKind.PROCESSING
    assert t.actions[2].verb == "F := 1"
    assert t.actions[2].kind == ActionKind.PROCESSING
    assert t.actions[3].verb == "N(r) := V(r)"
    assert t.actions[3].kind == ActionKind.PROCESSING
    assert t.actions[4].verb == "RR"
    assert t.actions[4].kind == ActionKind.SIGNAL_LOWER
    assert t.actions[5].verb == "Clear Acknowledge Pending"
    assert t.actions[5].kind == ActionKind.PROCESSING


def test_t26_i_received_yes_yes_yes_no_no_no_no() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t26_i_received_yes_yes_yes_no_no_no_no"),
        None,
    )
    assert t is not None, "transition t26_i_received_yes_yes_yes_no_no_no_no not found"
    assert t.on == "I_received"
    assert t.next == "Connected"
    assert t.guard == "command and info_field_length_le_N1_and_content_is_octet_aligned and va_le_nr_le_vs and not own_receiver_busy and not ns_eq_vr and not vr_lt_ns_lt_vr_plus_k and not P_eq_1"
    assert len(t.actions) == 2
    assert t.actions[0].verb == "Check_I_Frame_Acknowledged"
    assert t.actions[0].kind == ActionKind.SUBROUTINE
    assert t.actions[1].verb == "Discard Contents of I Frame"
    assert t.actions[1].kind == ActionKind.PROCESSING


def test_t26_i_received_yes_yes_yes_yes_yes() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t26_i_received_yes_yes_yes_yes_yes"),
        None,
    )
    assert t is not None, "transition t26_i_received_yes_yes_yes_yes_yes not found"
    assert t.on == "I_received"
    assert t.next == "Connected"
    assert t.guard == "command and info_field_length_le_N1_and_content_is_octet_aligned and va_le_nr_le_vs and own_receiver_busy and P_eq_1"
    assert len(t.actions) == 6
    assert t.actions[0].verb == "Check_I_Frame_Acknowledged"
    assert t.actions[0].kind == ActionKind.SUBROUTINE
    assert t.actions[1].verb == "Discard Contents of I Frame"
    assert t.actions[1].kind == ActionKind.PROCESSING
    assert t.actions[2].verb == "F := 1"
    assert t.actions[2].kind == ActionKind.PROCESSING
    assert t.actions[3].verb == "N(r) := V(r)"
    assert t.actions[3].kind == ActionKind.PROCESSING
    assert t.actions[4].verb == "RR"
    assert t.actions[4].kind == ActionKind.SIGNAL_LOWER
    assert t.actions[5].verb == "Clear Acknowledge Pending"
    assert t.actions[5].kind == ActionKind.PROCESSING


def test_t26_i_received_yes_yes_yes_yes_no() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t26_i_received_yes_yes_yes_yes_no"),
        None,
    )
    assert t is not None, "transition t26_i_received_yes_yes_yes_yes_no not found"
    assert t.on == "I_received"
    assert t.next == "Connected"
    assert t.guard == "command and info_field_length_le_N1_and_content_is_octet_aligned and va_le_nr_le_vs and own_receiver_busy and not P_eq_1"
    assert len(t.actions) == 2
    assert t.actions[0].verb == "Check_I_Frame_Acknowledged"
    assert t.actions[0].kind == ActionKind.SUBROUTINE
    assert t.actions[1].verb == "Discard Contents of I Frame"
    assert t.actions[1].kind == ActionKind.PROCESSING


def test_t26_i_received_no() -> None:
    t = next(
        (x for x in DATA_LINK_CONNECTED.transitions if x.id == "t26_i_received_no"),
        None,
    )
    assert t is not None, "transition t26_i_received_no not found"
    assert t.on == "I_received"
    assert t.next == "Connected"
    assert t.guard == "not command"
    assert len(t.actions) == 2
    assert t.actions[0].verb == "DL-ERROR Indication (O)"
    assert t.actions[0].kind == ActionKind.SIGNAL_UPPER
    assert t.actions[1].verb == "Discard I Frame"
    assert t.actions[1].kind == ActionKind.PROCESSING

